import { describe, expect, it } from 'bun:test';
import { classifyPrompt, compileAutomatedPromptPatterns, type PromptFacts } from './prompt-classifier.js';

const facts = (head: string, flags: Partial<PromptFacts> = {}): PromptFacts => ({
  head,
  isMeta: false,
  isSidechain: false,
  isCompactSummary: false,
  ...flags,
});

describe('classifyPrompt', () => {
  it('treats ordinary typed text as human', () => {
    expect(classifyPrompt(facts('fix the failing test in routes.ts'))).toBeNull();
    // A marker mid-text is not a marker: only the leading text decides.
    expect(classifyPrompt(facts('why did I get <task-notification> twice?'))).toBeNull();
  });

  it.each([
    ['<command-message>loop</command-message>', 'loop'],
    ['<command-name>/loop</command-name>', 'loop'],
    ['<<autonomous-loop-dynamic>>', 'loop'],
    ['<task-notification>\n<task-id>x</task-id>', 'task-notification'],
    ['This session is being continued from a previous conversation', 'compaction'],
    ['<local-command-stdout></local-command-stdout>', 'local-command'],
    ['Caveat: The messages below were generated by the user', 'local-command'],
    ['<system-reminder>\nnote', 'system'],
    ['[Request interrupted by user]', 'interrupt'],
    ['<cross-session-message from="x">', 'peer'],
    ['<bash-stdout>total 12\ndrwxr-xr-x</bash-stdout>', 'local-command'],
    ['<bash-stderr>ls: no such file</bash-stderr>', 'local-command'],
  ] as const)('marks %p as %s', (head, rule) => {
    expect(classifyPrompt(facts(head))).toBe(rule);
    expect(classifyPrompt(facts(`\n  ${head}`))).toBe(rule);
  });

  it('the origin kind decides before text: human is human, anything else is not', () => {
    // A self-paced loop re-firing its own skill command, with no origin.
    const wakeup = facts('<command-message>EXAMPLE-sync</command-message>\n<command-name>/EXAMPLE-sync</command-name>', {
      queuePriority: 'later',
    });
    expect(classifyPrompt(wakeup)).toBe('scheduled');
    // The same text typed by a person, on a client that records authorship.
    expect(classifyPrompt(facts(wakeup.head, { originKind: 'human' }))).toBeNull();
    // A person typing /loop to start one is human; the loop's firings are not.
    expect(classifyPrompt(facts('<command-message>loop</command-message>', { originKind: 'human' }))).toBeNull();
    expect(classifyPrompt(facts('<command-message>loop</command-message>', { queuePriority: 'later' }))).toBe('scheduled');
    expect(classifyPrompt(facts('<command-message>loop</command-message>'))).toBe('loop');

    expect(classifyPrompt(facts('anything', { originKind: 'task-notification' }))).toBe('task-notification');
    expect(classifyPrompt(facts('anything', { originKind: 'peer' }))).toBe('peer');
    expect(classifyPrompt(facts('anything', { originKind: 'coordinator' }))).toBe('origin');
    // `<bash-input>` is the person typing; its output is not.
    expect(classifyPrompt(facts('<bash-input>ls -la</bash-input>'))).toBeNull();
  });

  it('transcript flags decide before text', () => {
    expect(classifyPrompt(facts('looks typed', { isMeta: true }))).toBe('meta');
    expect(classifyPrompt(facts('looks typed', { isSidechain: true }))).toBe('sidechain');
    expect(classifyPrompt(facts('looks typed', { isCompactSummary: true }))).toBe('compaction');
  });

  it('applies instance patterns, which the toolkit ships none of', () => {
    const head = '<command-name>/EXAMPLE_nightly-sync</command-name>';
    expect(classifyPrompt(facts(head))).toBeNull();
    const patterns = compileAutomatedPromptPatterns('^<command-name>/EXAMPLE_nightly-sync\n\n^\\[bridge\\] ');
    expect(patterns).toHaveLength(2);
    expect(classifyPrompt(facts(head), patterns)).toBe('instance');
    expect(classifyPrompt(facts('[bridge] hello from chat'), patterns)).toBe('instance');
    expect(classifyPrompt(facts('hello'), patterns)).toBeNull();
  });

  it('an invalid instance pattern throws, naming it', () => {
    expect(() => compileAutomatedPromptPatterns('ok\n(unclosed')).toThrow(/\(unclosed/);
    expect(compileAutomatedPromptPatterns(undefined)).toEqual([]);
  });
});
