import { describe, expect, it } from 'bun:test';
import { classifyPrompt, compileAutomatedPromptPatterns, type PromptFacts } from './prompt-classifier.js';

const facts = (head: string, flags: Partial<PromptFacts> = {}): PromptFacts => ({
  head,
  isMeta: false,
  isSidechain: false,
  isCompactSummary: false,
  ...flags,
});

describe('classifyPrompt', () => {
  it('treats ordinary typed text as human', () => {
    expect(classifyPrompt(facts('fix the failing test in routes.ts'))).toBeNull();
    // A marker mid-text is not a marker: only the leading text decides.
    expect(classifyPrompt(facts('why did I get <task-notification> twice?'))).toBeNull();
  });

  it.each([
    ['<command-message>loop</command-message>', 'loop'],
    ['<command-name>/loop</command-name>', 'loop'],
    ['<<autonomous-loop-dynamic>>', 'loop'],
    ['<task-notification>\n<task-id>x</task-id>', 'task-notification'],
    ['This session is being continued from a previous conversation', 'compaction'],
    ['<local-command-stdout></local-command-stdout>', 'local-command'],
    ['Caveat: The messages below were generated by the user', 'local-command'],
    ['<system-reminder>\nnote', 'system'],
    ['[Request interrupted by user]', 'interrupt'],
    ['<cross-session-message from="x">', 'peer'],
  ] as const)('marks %p as %s', (head, rule) => {
    expect(classifyPrompt(facts(head))).toBe(rule);
    expect(classifyPrompt(facts(`\n  ${head}`))).toBe(rule);
  });

  it('transcript flags decide before text', () => {
    expect(classifyPrompt(facts('looks typed', { isMeta: true }))).toBe('meta');
    expect(classifyPrompt(facts('looks typed', { isSidechain: true }))).toBe('sidechain');
    expect(classifyPrompt(facts('looks typed', { isCompactSummary: true }))).toBe('compaction');
  });

  it('applies instance patterns, which the toolkit ships none of', () => {
    const head = '<command-name>/EXAMPLE_nightly-sync</command-name>';
    expect(classifyPrompt(facts(head))).toBeNull();
    const patterns = compileAutomatedPromptPatterns('^<command-name>/EXAMPLE_nightly-sync\n\n^\\[bridge\\] ');
    expect(patterns).toHaveLength(2);
    expect(classifyPrompt(facts(head), patterns)).toBe('instance');
    expect(classifyPrompt(facts('[bridge] hello from chat'), patterns)).toBe('instance');
    expect(classifyPrompt(facts('hello'), patterns)).toBeNull();
  });

  it('an invalid instance pattern throws, naming it', () => {
    expect(() => compileAutomatedPromptPatterns('ok\n(unclosed')).toThrow(/\(unclosed/);
    expect(compileAutomatedPromptPatterns(undefined)).toEqual([]);
  });
});
