#!/usr/bin/env node
// GENERATED by scripts/build-cli.ts from src/axi/ — do not edit. Run `bun run build:cli`.

// node_modules/.bun/axi-sdk-js@0.1.7/node_modules/axi-sdk-js/dist/cli.js
import { basename } from "node:path";

// node_modules/.bun/axi-sdk-js@0.1.7/node_modules/axi-sdk-js/dist/errors.js
var AxiError = class extends Error {
  code;
  suggestions;
  constructor(message, code, suggestions = []) {
    super(message);
    this.code = code;
    this.suggestions = suggestions;
    this.name = "AxiError";
  }
};
function exitCodeForError(error) {
  if (error instanceof AxiError && error.code === "VALIDATION_ERROR") {
    return 2;
  }
  return 1;
}

// node_modules/.bun/axi-sdk-js@0.1.7/node_modules/axi-sdk-js/dist/output.js
import { homedir } from "node:os";

// node_modules/.bun/@toon-format+toon@2.3.0/node_modules/@toon-format/toon/dist/index.mjs
var NULL_LITERAL = "null";
var DELIMITERS = {
  comma: ",",
  tab: "	",
  pipe: "|"
};
var DEFAULT_DELIMITER = DELIMITERS.comma;
function escapeString(value) {
  return value.replace(/\\/g, `\\\\`).replace(/"/g, `\\"`).replace(/\n/g, `\\n`).replace(/\r/g, `\\r`).replace(/\t/g, `\\t`).replace(/[\u0000-\u001F]/g, (c) => `\\u${c.charCodeAt(0).toString(16).padStart(4, "0")}`);
}
function isBooleanOrNullLiteral(token) {
  return token === "true" || token === "false" || token === "null";
}
function normalizeValue(value) {
  if (value === null) return null;
  if (typeof value === "object" && value !== null && "toJSON" in value && typeof value.toJSON === "function") {
    const next = value.toJSON();
    if (next !== value) return normalizeValue(next);
  }
  if (typeof value === "string" || typeof value === "boolean") return value;
  if (typeof value === "number") {
    if (Object.is(value, -0)) return 0;
    if (!Number.isFinite(value)) return null;
    return value;
  }
  if (typeof value === "bigint") {
    if (value >= Number.MIN_SAFE_INTEGER && value <= Number.MAX_SAFE_INTEGER) return Number(value);
    return value.toString();
  }
  if (value instanceof Date) return value.toISOString();
  if (Array.isArray(value)) return value.map(normalizeValue);
  if (value instanceof Set) return Array.from(value).map(normalizeValue);
  if (value instanceof Map) return Object.fromEntries(Array.from(value, ([k, v]) => [String(k), normalizeValue(v)]));
  if (isPlainObject(value)) {
    const encodedValues = {};
    for (const key in value) if (Object.hasOwn(value, key)) encodedValues[key] = normalizeValue(value[key]);
    return encodedValues;
  }
  return null;
}
function isJsonPrimitive(value) {
  return value === null || typeof value === "string" || typeof value === "number" || typeof value === "boolean";
}
function isJsonArray(value) {
  return Array.isArray(value);
}
function isJsonObject(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}
function isEmptyObject(value) {
  return Object.keys(value).length === 0;
}
function isPlainObject(value) {
  if (value === null || typeof value !== "object") return false;
  const prototype = Object.getPrototypeOf(value);
  return prototype === null || prototype === Object.prototype;
}
function isArrayOfPrimitives(value) {
  return value.length === 0 || value.every((item) => isJsonPrimitive(item));
}
function isArrayOfArrays(value) {
  return value.length === 0 || value.every((item) => isJsonArray(item));
}
function isArrayOfObjects(value) {
  return value.length === 0 || value.every((item) => isJsonObject(item));
}
var NUMERIC_LIKE_PATTERN = /^-?\d+(?:\.\d+)?(?:e[+-]?\d+)?$/i;
var LEADING_ZERO_PATTERN = /^0\d+$/;
function isValidUnquotedKey(key) {
  return /^[A-Z_][\w.]*$/i.test(key);
}
function isIdentifierSegment(key) {
  return /^[A-Z_]\w*$/i.test(key);
}
function isSafeUnquoted(value, delimiter = DEFAULT_DELIMITER) {
  if (!value) return false;
  if (value !== value.trim()) return false;
  if (isBooleanOrNullLiteral(value) || isNumericLike(value)) return false;
  if (value.includes(":")) return false;
  if (value.includes('"') || value.includes("\\")) return false;
  if (/[[\]{}]/.test(value)) return false;
  if (/[\u0000-\u001F]/.test(value)) return false;
  if (value.includes(delimiter)) return false;
  if (value.startsWith("-")) return false;
  return true;
}
function isNumericLike(value) {
  return NUMERIC_LIKE_PATTERN.test(value) || LEADING_ZERO_PATTERN.test(value);
}
function tryFoldKeyChain(key, value, siblings, options, rootLiteralKeys, pathPrefix, flattenDepth) {
  if (options.keyFolding !== "safe") return;
  if (!isJsonObject(value)) return;
  const { segments, tail, leafValue } = collectSingleKeyChain(key, value, flattenDepth ?? options.flattenDepth);
  if (segments.length < 2) return;
  if (!segments.every((seg) => isIdentifierSegment(seg))) return;
  const foldedKey = buildFoldedKey(segments);
  const absolutePath = pathPrefix ? `${pathPrefix}.${foldedKey}` : foldedKey;
  if (siblings.includes(foldedKey)) return;
  if (rootLiteralKeys && rootLiteralKeys.has(absolutePath)) return;
  return {
    foldedKey,
    remainder: tail,
    leafValue,
    segmentCount: segments.length
  };
}
function collectSingleKeyChain(startKey, startValue, maxDepth) {
  const segments = [startKey];
  let currentValue = startValue;
  while (segments.length < maxDepth) {
    if (!isJsonObject(currentValue)) break;
    const keys = Object.keys(currentValue);
    if (keys.length !== 1) break;
    const nextKey = keys[0];
    const nextValue = currentValue[nextKey];
    segments.push(nextKey);
    currentValue = nextValue;
  }
  if (!isJsonObject(currentValue) || isEmptyObject(currentValue)) return {
    segments,
    tail: void 0,
    leafValue: currentValue
  };
  return {
    segments,
    tail: currentValue,
    leafValue: currentValue
  };
}
function buildFoldedKey(segments) {
  return segments.join(".");
}
function encodePrimitive(value, delimiter) {
  if (value === null) return NULL_LITERAL;
  if (typeof value === "boolean") return String(value);
  if (typeof value === "number") return String(value);
  return encodeStringLiteral(value, delimiter);
}
function encodeStringLiteral(value, delimiter = DEFAULT_DELIMITER) {
  if (isSafeUnquoted(value, delimiter)) return value;
  return `"${escapeString(value)}"`;
}
function encodeKey(key) {
  if (isValidUnquotedKey(key)) return key;
  return `"${escapeString(key)}"`;
}
function encodeAndJoinPrimitives(values, delimiter = DEFAULT_DELIMITER) {
  return values.map((v) => encodePrimitive(v, delimiter)).join(delimiter);
}
function formatHeader(length, options) {
  const key = options?.key;
  const fields = options?.fields;
  const delimiter = options?.delimiter ?? ",";
  let header = "";
  if (key != null) header += encodeKey(key);
  header += `[${length}${delimiter !== DEFAULT_DELIMITER ? delimiter : ""}]`;
  if (fields) {
    const quotedFields = fields.map((f) => encodeKey(f));
    header += `{${quotedFields.join(delimiter)}}`;
  }
  header += ":";
  return header;
}
function* encodeJsonValue(value, options, depth) {
  if (isJsonPrimitive(value)) {
    const encodedPrimitive = encodePrimitive(value, options.delimiter);
    if (encodedPrimitive !== "") yield encodedPrimitive;
    return;
  }
  if (isJsonArray(value)) yield* encodeArrayLines(void 0, value, depth, options);
  else if (isJsonObject(value)) yield* encodeObjectLines(value, depth, options);
}
function* encodeObjectLines(value, depth, options, rootLiteralKeys, pathPrefix, remainingDepth) {
  const keys = Object.keys(value);
  if (depth === 0 && !rootLiteralKeys) rootLiteralKeys = new Set(keys.filter((k) => k.includes(".")));
  const effectiveFlattenDepth = remainingDepth ?? options.flattenDepth;
  for (const [key, val] of Object.entries(value)) yield* encodeKeyValuePairLines(key, val, depth, options, keys, rootLiteralKeys, pathPrefix, effectiveFlattenDepth);
}
function* encodeKeyValuePairLines(key, value, depth, options, siblings, rootLiteralKeys, pathPrefix, flattenDepth) {
  const currentPath = pathPrefix ? `${pathPrefix}.${key}` : key;
  const effectiveFlattenDepth = flattenDepth ?? options.flattenDepth;
  if (options.keyFolding === "safe" && siblings) {
    const foldResult = tryFoldKeyChain(key, value, siblings, options, rootLiteralKeys, pathPrefix, effectiveFlattenDepth);
    if (foldResult) {
      const { foldedKey, remainder, leafValue, segmentCount } = foldResult;
      const encodedFoldedKey = encodeKey(foldedKey);
      if (remainder === void 0) {
        if (isJsonPrimitive(leafValue)) {
          yield indentedLine(depth, `${encodedFoldedKey}: ${encodePrimitive(leafValue, options.delimiter)}`, options.indent);
          return;
        } else if (isJsonArray(leafValue)) {
          yield* encodeArrayLines(foldedKey, leafValue, depth, options);
          return;
        } else if (isJsonObject(leafValue) && isEmptyObject(leafValue)) {
          yield indentedLine(depth, `${encodedFoldedKey}:`, options.indent);
          return;
        }
      }
      if (isJsonObject(remainder)) {
        yield indentedLine(depth, `${encodedFoldedKey}:`, options.indent);
        const remainingDepth = effectiveFlattenDepth - segmentCount;
        const foldedPath = pathPrefix ? `${pathPrefix}.${foldedKey}` : foldedKey;
        yield* encodeObjectLines(remainder, depth + 1, options, rootLiteralKeys, foldedPath, remainingDepth);
        return;
      }
    }
  }
  const encodedKey = encodeKey(key);
  if (isJsonPrimitive(value)) yield indentedLine(depth, `${encodedKey}: ${encodePrimitive(value, options.delimiter)}`, options.indent);
  else if (isJsonArray(value)) yield* encodeArrayLines(key, value, depth, options);
  else if (isJsonObject(value)) {
    yield indentedLine(depth, `${encodedKey}:`, options.indent);
    if (!isEmptyObject(value)) yield* encodeObjectLines(value, depth + 1, options, rootLiteralKeys, currentPath, effectiveFlattenDepth);
  }
}
function* encodeArrayLines(key, value, depth, options) {
  if (value.length === 0) {
    yield indentedLine(depth, key != null ? `${encodeKey(key)}: []` : "[]", options.indent);
    return;
  }
  if (isArrayOfPrimitives(value)) {
    yield indentedLine(depth, encodeInlineArrayLine(value, options.delimiter, key), options.indent);
    return;
  }
  if (isArrayOfArrays(value)) {
    if (value.every((arr) => isArrayOfPrimitives(arr))) {
      yield* encodeArrayOfArraysAsListItemsLines(key, value, depth, options);
      return;
    }
  }
  if (isArrayOfObjects(value)) {
    const header = extractTabularHeader(value);
    if (header) yield* encodeArrayOfObjectsAsTabularLines(key, value, header, depth, options);
    else yield* encodeMixedArrayAsListItemsLines(key, value, depth, options);
    return;
  }
  yield* encodeMixedArrayAsListItemsLines(key, value, depth, options);
}
function* encodeArrayOfArraysAsListItemsLines(prefix, values, depth, options) {
  yield indentedLine(depth, formatHeader(values.length, {
    key: prefix,
    delimiter: options.delimiter
  }), options.indent);
  for (const arr of values) if (isArrayOfPrimitives(arr)) {
    const arrayLine = encodeInlineArrayLine(arr, options.delimiter);
    yield indentedListItem(depth + 1, arrayLine, options.indent);
  }
}
function encodeInlineArrayLine(values, delimiter, prefix) {
  const header = formatHeader(values.length, {
    key: prefix,
    delimiter
  });
  const joinedValue = encodeAndJoinPrimitives(values, delimiter);
  if (values.length === 0) return header;
  return `${header} ${joinedValue}`;
}
function* encodeArrayOfObjectsAsTabularLines(prefix, rows, header, depth, options) {
  yield indentedLine(depth, formatHeader(rows.length, {
    key: prefix,
    fields: header,
    delimiter: options.delimiter
  }), options.indent);
  yield* writeTabularRowsLines(rows, header, depth + 1, options);
}
function extractTabularHeader(rows) {
  if (rows.length === 0) return;
  const firstRow = rows[0];
  const firstKeys = Object.keys(firstRow);
  if (firstKeys.length === 0) return;
  if (isTabularArray(rows, firstKeys)) return firstKeys;
}
function isTabularArray(rows, header) {
  for (const row of rows) {
    if (Object.keys(row).length !== header.length) return false;
    for (const key of header) {
      if (!(key in row)) return false;
      if (!isJsonPrimitive(row[key])) return false;
    }
  }
  return true;
}
function* writeTabularRowsLines(rows, header, depth, options) {
  for (const row of rows) yield indentedLine(depth, encodeAndJoinPrimitives(header.map((key) => row[key]), options.delimiter), options.indent);
}
function* encodeMixedArrayAsListItemsLines(prefix, items, depth, options) {
  yield indentedLine(depth, formatHeader(items.length, {
    key: prefix,
    delimiter: options.delimiter
  }), options.indent);
  for (const item of items) yield* encodeListItemValueLines(item, depth + 1, options);
}
function* encodeObjectAsListItemLines(obj, depth, options) {
  if (isEmptyObject(obj)) {
    yield indentedLine(depth, "-", options.indent);
    return;
  }
  const entries = Object.entries(obj);
  const [firstKey, firstValue] = entries[0];
  const restEntries = entries.slice(1);
  if (isJsonArray(firstValue) && isArrayOfObjects(firstValue)) {
    const header = extractTabularHeader(firstValue);
    if (header) {
      yield indentedListItem(depth, formatHeader(firstValue.length, {
        key: firstKey,
        fields: header,
        delimiter: options.delimiter
      }), options.indent);
      yield* writeTabularRowsLines(firstValue, header, depth + 2, options);
      if (restEntries.length > 0) yield* encodeObjectLines(Object.fromEntries(restEntries), depth + 1, options);
      return;
    }
  }
  const encodedKey = encodeKey(firstKey);
  if (isJsonPrimitive(firstValue)) yield indentedListItem(depth, `${encodedKey}: ${encodePrimitive(firstValue, options.delimiter)}`, options.indent);
  else if (isJsonArray(firstValue)) if (firstValue.length === 0) yield indentedListItem(depth, `${encodedKey}: []`, options.indent);
  else if (isArrayOfPrimitives(firstValue)) yield indentedListItem(depth, `${encodedKey}${encodeInlineArrayLine(firstValue, options.delimiter)}`, options.indent);
  else {
    yield indentedListItem(depth, `${encodedKey}${formatHeader(firstValue.length, { delimiter: options.delimiter })}`, options.indent);
    for (const item of firstValue) yield* encodeListItemValueLines(item, depth + 2, options);
  }
  else if (isJsonObject(firstValue)) {
    yield indentedListItem(depth, `${encodedKey}:`, options.indent);
    if (!isEmptyObject(firstValue)) yield* encodeObjectLines(firstValue, depth + 2, options);
  }
  if (restEntries.length > 0) yield* encodeObjectLines(Object.fromEntries(restEntries), depth + 1, options);
}
function* encodeListItemValueLines(value, depth, options) {
  if (isJsonPrimitive(value)) yield indentedListItem(depth, encodePrimitive(value, options.delimiter), options.indent);
  else if (isJsonArray(value)) if (isArrayOfPrimitives(value)) yield indentedListItem(depth, encodeInlineArrayLine(value, options.delimiter), options.indent);
  else {
    yield indentedListItem(depth, formatHeader(value.length, { delimiter: options.delimiter }), options.indent);
    for (const item of value) yield* encodeListItemValueLines(item, depth + 1, options);
  }
  else if (isJsonObject(value)) yield* encodeObjectAsListItemLines(value, depth, options);
}
function indentedLine(depth, content, indentSize) {
  return " ".repeat(indentSize * depth) + content;
}
function indentedListItem(depth, content, indentSize) {
  return indentedLine(depth, "- " + content, indentSize);
}
function applyReplacer(root, replacer) {
  const replacedRoot = replacer("", root, []);
  if (replacedRoot === void 0) return transformChildren(root, replacer, []);
  return transformChildren(normalizeValue(replacedRoot), replacer, []);
}
function transformChildren(value, replacer, path) {
  if (isJsonObject(value)) return transformObject(value, replacer, path);
  if (isJsonArray(value)) return transformArray(value, replacer, path);
  return value;
}
function transformObject(obj, replacer, path) {
  const result = {};
  for (const [key, value] of Object.entries(obj)) {
    const childPath = [...path, key];
    const replacedValue = replacer(key, value, childPath);
    if (replacedValue === void 0) continue;
    result[key] = transformChildren(normalizeValue(replacedValue), replacer, childPath);
  }
  return result;
}
function transformArray(arr, replacer, path) {
  const result = [];
  for (let i = 0; i < arr.length; i++) {
    const value = arr[i];
    const childPath = [...path, i];
    const replacedValue = replacer(String(i), value, childPath);
    if (replacedValue === void 0) continue;
    const normalizedValue = normalizeValue(replacedValue);
    result.push(transformChildren(normalizedValue, replacer, childPath));
  }
  return result;
}
function encode(input, options) {
  return Array.from(encodeLines(input, options)).join("\n");
}
function encodeLines(input, options) {
  const normalizedValue = normalizeValue(input);
  const resolvedOptions = resolveOptions(options);
  return encodeJsonValue(resolvedOptions.replacer ? applyReplacer(normalizedValue, resolvedOptions.replacer) : normalizedValue, resolvedOptions, 0);
}
function resolveOptions(options) {
  return {
    indent: options?.indent ?? 2,
    delimiter: options?.delimiter ?? DEFAULT_DELIMITER,
    keyFolding: options?.keyFolding ?? "off",
    flattenDepth: options?.flattenDepth ?? Number.POSITIVE_INFINITY,
    replacer: options?.replacer
  };
}

// node_modules/.bun/axi-sdk-js@0.1.7/node_modules/axi-sdk-js/dist/output.js
function collapseHomeDirectory(path, homeDir = homedir()) {
  if (!path.startsWith(homeDir)) {
    return path;
  }
  return `~${path.slice(homeDir.length)}`;
}
function homeHeaderOutput(options) {
  return {
    bin: collapseHomeDirectory(options.execPath ?? process.argv[1] ?? "", options.homeDir),
    description: options.description
  };
}
function errorOutput(message, code, suggestions = []) {
  const output = {
    error: message,
    code
  };
  if (suggestions.length > 0) {
    output.help = suggestions;
  }
  return output;
}
function renderOutput(output) {
  if (typeof output === "string") {
    return output;
  }
  return encode(output);
}
function renderError(message, code, suggestions = []) {
  return renderOutput(errorOutput(message, code, suggestions));
}

// node_modules/.bun/axi-sdk-js@0.1.7/node_modules/axi-sdk-js/dist/cli.js
function defaultFormatError(error) {
  if (error instanceof AxiError) {
    return {
      output: `${renderError(error.message, error.code, error.suggestions)}
`,
      exitCode: exitCodeForError(error)
    };
  }
  const message = error instanceof Error ? error.message : String(error);
  return {
    output: `${renderError(message, "UNKNOWN")}
`,
    exitCode: 1
  };
}
function defaultUnknownCommand(command) {
  return `${renderError(`Unknown command: ${command}`, "VALIDATION_ERROR", [
    "Run `--help` to see available commands"
  ])}
`;
}
async function runAxiCli(options) {
  options.initialize?.();
  const stdout = options.stdout ?? process.stdout;
  const argv = options.argv ?? process.argv.slice(2);
  if (argv.length === 1 && argv[0] === "--help") {
    stdout.write(options.topLevelHelp);
    return;
  }
  if (argv.length === 1 && isVersionFlag(argv[0])) {
    if (!options.version) {
      stdout.write(`${renderError("Version is not configured for this tool", "VALIDATION_ERROR")}
`);
      process.exitCode = 2;
      return;
    }
    stdout.write(`${options.version}
`);
    return;
  }
  const command = argv[0];
  if (!command) {
    const context2 = await options.resolveContext?.({
      command: void 0,
      args: []
    });
    await runHandler(options.home, [], context2, stdout, options, true);
    return;
  }
  if (command.startsWith("-")) {
    stdout.write(renderLeadingFlagError(command));
    process.exitCode = 2;
    return;
  }
  const args = argv.slice(1);
  if (args.includes("--help")) {
    const help = options.getCommandHelp?.(command);
    if (help) {
      stdout.write(help);
      return;
    }
  }
  const handler = options.commands[command];
  if (!handler) {
    stdout.write((options.renderUnknownCommand ?? defaultUnknownCommand)(command));
    process.exitCode = 2;
    return;
  }
  const context = await options.resolveContext?.({ command, args });
  await runHandler(handler, args, context, stdout, options, false);
}
async function runHandler(handler, args, context, stdout, options, isHomeView) {
  try {
    const output = await handler(args, context);
    stdout.write(`${renderCommandOutput(output, options, isHomeView)}
`);
  } catch (error) {
    const formatted = (options.formatError ?? defaultFormatError)(error);
    stdout.write(formatted.output);
    process.exitCode = formatted.exitCode;
  }
}
function renderLeadingFlagError(flag) {
  const bin = basename(process.argv[1] ?? "tool") || "tool";
  return `${renderError("Flags must come after the command", "VALIDATION_ERROR", [
    `Run \`${bin} <command> [args] [flags]\``,
    `Move \`${flag}\` after the command instead of before it`
  ])}
`;
}
function isVersionFlag(flag) {
  return flag === "-v" || flag === "-V" || flag === "--version";
}
function renderCommandOutput(output, options, isHomeView) {
  if (!isHomeView) {
    return renderOutput(output);
  }
  const header = homeHeaderOutput({ description: options.description });
  if (typeof output === "string") {
    return `${renderOutput(header)}
${output}`;
  }
  return renderOutput(mergeHomeHeader(header, output));
}
function mergeHomeHeader(header, output) {
  const rest = { ...output };
  delete rest.bin;
  delete rest.description;
  return {
    ...header,
    ...rest
  };
}

// packages/kitchen/src/axi/reference.ts
var DESCRIPTION = "Read and write the kitchen consumption journal and inventory \u2014 log meals, adjust portions, track stock, scan receipts, and seed products/lexicon.";
var COMMAND_GROUPS = [
  {
    group: "Entries",
    commands: [
      { usage: "entries list [--since DATE] [--limit N]", summary: "newest-first consumption entries (base macros + portion_multiplier; effective = base \xD7 multiplier)" },
      { usage: "entries show <ulid>", summary: "one entry with full nutrition, source, and status" },
      {
        usage: 'entries log [note\u2026] [--recipe ULID] [--component "label=grams"]\u2026',
        summary: "log a deliberate, no-model entry (note and/or recipe + component quantities); recipe-referenced entries are computed deterministically"
      },
      {
        usage: "entries patch <ulid> [--note T] [--label T] [--calories N] [--protein N] [--fat N] [--sat-fat N] [--carbs N] [--sodium N] [--portion-basis T] [--multiplier M]",
        summary: "edit an entry: note/label re-queue estimation; any macro sets a terminal manual override; --multiplier rescales the base post-hoc (never re-queues, never changes source)"
      },
      { usage: "entries delete <ulid>", summary: "remove an entry from all rollups" }
    ]
  },
  {
    group: "Inventory",
    commands: [
      { usage: "inventory list [--state S] [--closed] [--limit N]", summary: "on-hand items in eat-first (eat_by ascending) order; --state filters, --closed includes finished/tossed" },
      { usage: "inventory show <ulid>", summary: "one inventory item with derived eat_by / days-until / age" },
      {
        usage: "inventory add [--raw-label T] [--product-ulid U] [--store S] [--acquired-at DATE] [--fraction F] [--state S] [--needs-info] [--shelf-life C] [--notes T] [--ulid U]",
        summary: "create an item directly (manual/verbal purchase or seed); idempotent when --ulid supplied"
      },
      {
        usage: "inventory event <ulid> <opened|finished|tossed> [--fraction F] [--at DATE]",
        summary: "explicit state change; for tossed, --fraction is the AMOUNT TOSSED (partial toss decrements + stays alive, terminal only at zero remainder or when omitted)"
      },
      { usage: 'inventory remark "<free text>" [--at DATE]', summary: "free-text event resolver \u2014 matches a remark to an item and infers opened/finished/tossed; prints matched/unmatched honestly (unmatched is normal, not an error)" },
      { usage: "inventory questions [--limit N]", summary: "open needs-info items as one-time questions" }
    ]
  },
  {
    group: "Receipts",
    commands: [
      { usage: "receipts list [--limit N]", summary: "recent purchase batches with parse status" },
      { usage: "receipts show <ulid>", summary: "one batch plus its parsed line outcomes (matched/unmatched/pending)" },
      {
        usage: "receipts scan <photo\u2026> [--store S] [--purchased-at DATE] [--ulid U]",
        summary: "post a purchase batch from receipt photos (parses asynchronously); meta is sent as a form field per the module's part-type rule"
      }
    ]
  },
  {
    group: "Recipes",
    commands: [
      { usage: "recipes list [--limit N]", summary: "the reselect strip \u2014 merged sheet + pushed + promoted recipes plus recent/frequent logged items" },
      { usage: "recipes push '<recipe json>'", summary: 'agent-authored template: {"name": "...", "components": [{label, default_qty_g, per_100g:{calories, protein_g, sat_fat_g}}]}' },
      { usage: "recipes promote <entry-ulid> --name NAME", summary: "create a reusable recipe from a logged entry" }
    ]
  },
  {
    group: "Products & lexicon",
    commands: [
      { usage: "products list [--q TEXT] [--limit N]", summary: "products (durable item facts); --q substring-matches name/aliases" },
      {
        usage: "products add --name NAME [--shelf-life C] [--aliases a,b] [--package-size S] [--nutrition '<json>'] [--shelf-life-days-unopened N] [--shelf-life-days-opened N]",
        summary: "seed a product"
      },
      { usage: "lexicon list [--store S] [--limit N]", summary: "receipt-line \u2192 product mappings per store" },
      {
        usage: "lexicon add --store S --line-text T --product-ulid U [--package-size S] [--shelf-life C]",
        summary: "map a store's receipt line to a product (upserts on store+line; future receipts auto-resolve)"
      }
    ]
  }
];
function commandReferenceText() {
  return COMMAND_GROUPS.map((g) => {
    const items = g.commands.map((c) => `  ${c.usage}
      ${c.summary}`).join("\n");
    return `${g.group}:
${items}`;
  }).join("\n\n");
}
function discoveryHelp(invocation) {
  return `Run \`${invocation} --help\` for the full command list, or \`${invocation} <group> --help\` for usage on any command group`;
}
var SHELF_LIFE_CLASSES = [
  "pantry",
  "frozen",
  "fridge_long",
  "fridge_short",
  "produce",
  "very_perishable",
  "unknown"
];

// packages/kitchen/src/axi/invocation.ts
import { accessSync, constants } from "node:fs";
import { homedir as homedir2 } from "node:os";
import { fileURLToPath } from "node:url";
var cached;
function cliInvocation() {
  if (cached) return cached;
  let bundle;
  try {
    bundle = fileURLToPath(import.meta.url);
  } catch {
    bundle = process.argv[1] ?? "kitchen-axi";
  }
  const shim = bundle.replace(/\.mjs$/, "");
  try {
    if (shim !== bundle) {
      accessSync(shim, constants.X_OK);
      cached = quote(collapseHome(shim));
      return cached;
    }
  } catch {
  }
  cached = `node ${quote(collapseHome(bundle))}`;
  return cached;
}
function collapseHome(p) {
  const home = homedir2();
  return home && p.startsWith(`${home}/`) ? `~${p.slice(home.length)}` : p;
}
function quote(p) {
  return /\s/.test(p) ? `"${p}"` : p;
}

// packages/kitchen/src/axi/client.ts
import { readFile } from "node:fs/promises";
import { basename as basename2, extname } from "node:path";
var DEFAULT_SERVER = "http://localhost:2529";
function resolveServer(env = process.env) {
  const value = env.CLAUDE_ASSIST_SERVER?.trim();
  return (value || DEFAULT_SERVER).replace(/\/+$/, "");
}
function buildUrl(server, path, query) {
  let url = `${server}${path}`;
  if (query) {
    const qs = new URLSearchParams();
    for (const [k, v] of Object.entries(query)) {
      if (v === void 0 || v === null || v === "") continue;
      if (Array.isArray(v)) {
        for (const item of v) if (item !== void 0 && item !== null && item !== "") qs.append(k, String(item));
      } else {
        qs.append(k, String(v));
      }
    }
    const s = qs.toString();
    if (s) url += `?${s}`;
  }
  return url;
}
function suggestForStatus(status) {
  if (status === 404) return ["Check the ulid \u2014 try a `list` command to look one up"];
  if (status === 400) return ["Check required params and value formats for this command"];
  if (status === 409) return ["This resource is terminal (a manual override or a finished/tossed item) and can't be overwritten"];
  if (status === 503) return ["The server is up but this feature is disabled (e.g. no model API key configured)"];
  return [];
}
async function send(method, path, opts = {}) {
  const server = resolveServer();
  const url = buildUrl(server, path, opts.query);
  const hasJsonBody = opts.body !== void 0 && opts.body !== null;
  const init = { method, headers: hasJsonBody ? { "Content-Type": "application/json" } : {} };
  if (opts.form) init.body = opts.form;
  else if (hasJsonBody) init.body = JSON.stringify(opts.body);
  let res;
  try {
    res = await fetch(url, init);
  } catch (err) {
    throw new AxiError(
      `Cannot reach claude-assist server at ${server} (${err.message})`,
      "HTTP_ERROR",
      ["Set CLAUDE_ASSIST_SERVER or start the server (cd apps/server && docker-compose up -d)"]
    );
  }
  return res;
}
async function parseError(res) {
  const text = await res.text();
  let message = res.statusText || `HTTP ${res.status}`;
  if (text) {
    try {
      const data = JSON.parse(text);
      if (data && typeof data === "object" && data.error) message = data.error;
      else if (data && typeof data === "object" && data.message) message = data.message;
    } catch {
      message = text.slice(0, 200);
    }
  }
  throw new AxiError(`API error (${res.status}): ${message}`, "HTTP_ERROR", suggestForStatus(res.status));
}
async function parseBody(res) {
  const text = await res.text();
  if (!text) return null;
  try {
    return JSON.parse(text);
  } catch {
    return text;
  }
}
var MIME_BY_EXT = {
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".png": "image/png",
  ".webp": "image/webp",
  ".heic": "image/heic",
  ".heif": "image/heif",
  ".gif": "image/gif"
};
function mimeForPath(path) {
  return MIME_BY_EXT[extname(path).toLowerCase()] ?? "application/octet-stream";
}
async function buildMultipartForm(metaField, meta, photoPaths) {
  const form = new FormData();
  form.append(metaField, JSON.stringify(meta));
  for (const p of photoPaths) {
    const data = await readFile(p);
    form.append("photos", new Blob([data], { type: mimeForPath(p) }), basename2(p));
  }
  return form;
}
var api = {
  async get(path, query) {
    const res = await send("GET", path, { query });
    if (!res.ok) await parseError(res);
    return parseBody(res);
  },
  async post(path, body, query) {
    const res = await send("POST", path, { body, query });
    if (!res.ok) await parseError(res);
    return parseBody(res);
  },
  async postForm(path, form) {
    const res = await send("POST", path, { form });
    if (!res.ok) await parseError(res);
    return parseBody(res);
  },
  async patch(path, body) {
    const res = await send("PATCH", path, { body });
    if (!res.ok) await parseError(res);
    return parseBody(res);
  },
  async del(path) {
    const res = await send("DELETE", path);
    if (!res.ok) await parseError(res);
    return { ok: true, status: res.status };
  }
};

// packages/kitchen/src/axi/args.ts
function parseArgs(args, booleanFlags = []) {
  const positionals = [];
  const flags = {};
  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg.startsWith("--")) {
      const name = arg.slice(2);
      if (booleanFlags.includes(name)) {
        flags[name] = true;
      } else {
        const value = args[++i];
        if (value === void 0) {
          throw new AxiError(`Flag --${name} requires a value`, "VALIDATION_ERROR");
        }
        flags[name] = value;
      }
    } else {
      positionals.push(arg);
    }
  }
  return { positionals, flags };
}
function collectFlag(args, name, booleanFlags = []) {
  const values = [];
  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (!arg.startsWith("--")) continue;
    const key = arg.slice(2);
    if (booleanFlags.includes(key)) continue;
    const value = args[++i];
    if (key === name && value !== void 0) values.push(value);
  }
  return values;
}
function requireFlag(flags, name, usage) {
  const v = flags[name];
  if (typeof v !== "string" || v === "") {
    throw new AxiError(`--${name} is required`, "VALIDATION_ERROR", [usage]);
  }
  return v;
}
function requirePositional(positionals, index, label, usage) {
  const v = positionals[index];
  if (!v) throw new AxiError(`${label} is required`, "VALIDATION_ERROR", [usage]);
  return v;
}
var DATE_ONLY = /^\d{4}-\d{2}-\d{2}$/;
var ISO_DATETIME = /^\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}(:\d{2}(\.\d+)?)?(Z|[+-]\d{2}:?\d{2})?$/;
function validateDate(value, flag, usage) {
  const wellFormed = DATE_ONLY.test(value) || ISO_DATETIME.test(value);
  if (!wellFormed || Number.isNaN(Date.parse(value))) {
    throw new AxiError(`Invalid date for ${flag}: ${value}`, "VALIDATION_ERROR", [
      "Use YYYY-MM-DD (e.g. 2026-04-29) or a full ISO 8601 timestamp (e.g. 2026-04-29T14:30:00Z)",
      usage
    ]);
  }
  return value;
}
function parseNumberFlag(value, flag, usage, opts = {}) {
  const n = Number(value);
  if (!Number.isFinite(n)) {
    throw new AxiError(`--${flag} must be a number (got ${value})`, "VALIDATION_ERROR", [usage]);
  }
  if (opts.min !== void 0 && n < opts.min) {
    throw new AxiError(`--${flag} must be >= ${opts.min} (got ${n})`, "VALIDATION_ERROR", [usage]);
  }
  if (opts.max !== void 0 && n > opts.max) {
    throw new AxiError(`--${flag} must be <= ${opts.max} (got ${n})`, "VALIDATION_ERROR", [usage]);
  }
  return n;
}
function parseJson(value, label, usage) {
  try {
    return JSON.parse(value);
  } catch (err) {
    throw new AxiError(`${label} must be valid JSON: ${err.message}`, "VALIDATION_ERROR", [usage]);
  }
}
function splitCsv(value) {
  return value.split(",").map((s) => s.trim()).filter(Boolean);
}
function rawJson(data) {
  return JSON.stringify(data, null, 2);
}

// packages/kitchen/src/axi/toon.ts
function field(key, as) {
  return { type: "field", key, as };
}
function joinArray(key, subkey, as, empty = "none") {
  return { type: "joinArray", key, subkey, as, empty };
}
function count(key, as) {
  return { type: "count", key, as };
}
function custom(as, fn) {
  return { type: "custom", as, fn };
}
function outputKey(def) {
  if (def.type === "custom") return def.as;
  return def.as ?? def.key;
}
function extract(item, schema) {
  const result = {};
  for (const def of schema) {
    const key = outputKey(def);
    switch (def.type) {
      case "field":
        result[key] = item[def.key] ?? null;
        break;
      case "pluck":
        result[key] = item[def.key]?.[def.subkey] ?? null;
        break;
      case "joinArray": {
        const arr = item[def.key];
        if (Array.isArray(arr) && arr.length > 0) {
          result[key] = arr.map(
            (x) => def.subkey && x && typeof x === "object" ? x[def.subkey] : x
          ).join(",");
        } else {
          result[key] = def.empty ?? "none";
        }
        break;
      }
      case "count": {
        const arr = item[def.key];
        result[key] = Array.isArray(arr) ? arr.length : 0;
        break;
      }
      case "relativeTime":
        result[key] = formatRelativeTime(item[def.key]);
        break;
      case "dateOnly":
        result[key] = formatDateOnly(item[def.key]);
        break;
      case "boolYesNo":
        result[key] = item[def.key] ? "yes" : "no";
        break;
      case "truncate":
        result[key] = truncateText(item[def.key], def.limit).value;
        break;
      case "custom":
        result[key] = def.fn(item);
        break;
    }
  }
  return result;
}
function renderList(label, items, schema) {
  return encode({ [label]: items.map((item) => extract(item, schema)) });
}
function renderDetail(label, item, schema) {
  return encode({ [label]: extract(item, schema) });
}
function renderObject(obj) {
  return encode(obj);
}
function renderHelp(lines) {
  const clean = lines.filter(Boolean);
  if (clean.length === 0) return "";
  return `help[${clean.length}]:
${clean.map((l) => `  ${l}`).join("\n")}`;
}
function renderOutput2(blocks) {
  return blocks.filter(Boolean).join("\n");
}
var DEFAULT_TRUNCATE = 280;
function truncateText(text, limit = DEFAULT_TRUNCATE) {
  if (typeof text !== "string") return { value: text ?? null, truncated: false, total: 0 };
  if (text.length <= limit) return { value: text, truncated: false, total: text.length };
  return {
    value: `${text.slice(0, limit)}\u2026 (truncated, ${text.length} chars total)`,
    truncated: true,
    total: text.length
  };
}
function formatDateOnly(value) {
  if (!value) return null;
  const d = new Date(value);
  if (isNaN(d.getTime())) return String(value);
  return d.toISOString().slice(0, 10);
}
function formatRelativeTime(value) {
  if (!value) return "unknown";
  const then = new Date(value).getTime();
  if (isNaN(then)) return "unknown";
  const diffSec = Math.floor((Date.now() - then) / 1e3);
  const past = diffSec >= 0;
  const s = Math.abs(diffSec);
  const fmt = (n, unit) => past ? `${n}${unit} ago` : `in ${n}${unit}`;
  if (s < 60) return past ? "just now" : "soon";
  const min = Math.floor(s / 60);
  if (min < 60) return fmt(min, "m");
  const hr = Math.floor(min / 60);
  if (hr < 24) return fmt(hr, "h");
  const day = Math.floor(hr / 24);
  if (day < 30) return fmt(day, "d");
  const mon = Math.floor(day / 30);
  if (mon < 12) return fmt(mon, "mo");
  return fmt(Math.floor(mon / 12), "y");
}

// packages/kitchen/src/axi/format.ts
var MACRO_KEYS = ["calories", "protein_g", "fat_g", "sat_fat_g", "carbs_g", "sodium_mg"];
function effectiveMacro(entry, key) {
  const base = entry[key];
  if (base === null || base === void 0) return null;
  const mult = typeof entry.portion_multiplier === "number" ? entry.portion_multiplier : 1;
  return round(base * mult);
}
function sumEffective(entries) {
  const totals = { calories: 0, protein_g: 0, fat_g: 0, sat_fat_g: 0, carbs_g: 0, sodium_mg: 0 };
  for (const e of entries) {
    const mult = typeof e.portion_multiplier === "number" ? e.portion_multiplier : 1;
    for (const key of MACRO_KEYS) {
      const base = e[key];
      if (typeof base === "number") totals[key] += base * mult;
    }
  }
  for (const key of MACRO_KEYS) totals[key] = round(totals[key]);
  return totals;
}
function round(n) {
  return Math.round(n * 10) / 10;
}
var ENTRY_ROW_SCHEMA = [
  { type: "field", key: "ulid" },
  { type: "dateOnly", key: "logged_at", as: "logged" },
  { type: "field", key: "label" },
  { type: "field", key: "status" },
  { type: "field", key: "source" },
  { type: "field", key: "portion_multiplier", as: "mult" },
  custom("kcal", (e) => effectiveMacro(e, "calories")),
  custom("protein", (e) => effectiveMacro(e, "protein_g"))
];

// packages/kitchen/src/axi/commands/home.ts
var HOME_HELP = `kitchen-axi [--eat-first N] [--json]

  The no-arg view: today's entries + effective macro totals, pending-estimate
  count, the top eat-first inventory items, and the open needs-info question
  count.

  --eat-first N   how many eat-first items to show (default 3)
  --json          raw JSON`;
var EAT_FIRST_SCHEMA = [
  field("product_name", "name"),
  field("state"),
  field("eat_by"),
  field("days_until_eat_by", "days_left"),
  field("on_hand_fraction", "on_hand")
];
function startOfTodayIso() {
  const now = /* @__PURE__ */ new Date();
  return new Date(now.getFullYear(), now.getMonth(), now.getDate()).toISOString();
}
async function homeCommand(args) {
  const { flags } = parseArgs(args, ["json"]);
  const server = resolveServer();
  const cli = cliInvocation();
  const eatFirstN = typeof flags["eat-first"] === "string" ? Math.max(parseInt(flags["eat-first"], 10) || 3, 1) : 3;
  let entries = null;
  let items = [];
  let questionCount = 0;
  let reachable = true;
  try {
    const [entriesRes, invRes, qRes] = await Promise.all([
      api.get("/api/kitchen/entries", { since: startOfTodayIso() }),
      api.get("/api/kitchen/inventory", { limit: eatFirstN }),
      api.get("/api/kitchen/inventory/questions", { limit: 1 })
    ]);
    entries = Array.isArray(entriesRes?.entries) ? entriesRes.entries : [];
    items = Array.isArray(invRes?.items) ? invRes.items : [];
    questionCount = typeof qRes?.count === "number" ? qRes.count : 0;
  } catch {
    reachable = false;
  }
  if (flags.json) {
    return rawJson({ server, today: entries, eat_first: items, questions: questionCount });
  }
  if (!reachable || entries === null) {
    return renderOutput2([
      renderObject({ server }),
      "The server is not reachable. Set CLAUDE_ASSIST_SERVER or start it (cd apps/server && docker-compose up -d).",
      renderHelp([discoveryHelp(cli)])
    ]);
  }
  const pending = entries.filter((e) => e.status === "estimating").length;
  const failed = entries.filter((e) => e.status === "failed").length;
  const totals = sumEffective(entries);
  const today = renderObject({
    server,
    date: startOfTodayIso().slice(0, 10),
    entries: entries.length,
    pending_estimates: pending,
    ...failed ? { failed } : {},
    kcal: totals.calories,
    protein_g: totals.protein_g,
    fat_g: totals.fat_g,
    sat_fat_g: totals.sat_fat_g,
    carbs_g: totals.carbs_g,
    sodium_mg: totals.sodium_mg,
    open_questions: questionCount
  });
  const blocks = [today];
  if (items.length) {
    blocks.push(renderList("eat_first", items, EAT_FIRST_SCHEMA));
  } else {
    blocks.push("eat_first: no on-hand items");
  }
  blocks.push(
    renderHelp([
      `Run \`${cli} entries list\` for today's log, \`${cli} entries log "<meal>"\` to log`,
      questionCount ? `Run \`${cli} inventory questions\` to answer ${questionCount} open needs-info item(s)` : "",
      `Run \`${cli} inventory list\` for full stock, \`${cli} recipes list\` for the reselect strip`,
      discoveryHelp(cli)
    ])
  );
  return renderOutput2(blocks);
}

// packages/kitchen/src/ulid.ts
import { createHash, randomBytes } from "node:crypto";
var ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";
function encodeTime(timeMs) {
  if (!Number.isFinite(timeMs) || timeMs < 0 || timeMs > 2 ** 48 - 1) {
    throw new Error(`ULID timestamp out of range: ${timeMs}`);
  }
  let ms = Math.floor(timeMs);
  let out = "";
  for (let i = 0; i < 10; i++) {
    out = ALPHABET[ms % 32] + out;
    ms = Math.floor(ms / 32);
  }
  return out;
}
function encodeBytes(bytes) {
  if (bytes.length < 10) throw new Error("Need at least 10 bytes of entropy");
  let bits = 0;
  let acc = 0;
  let out = "";
  for (let i = 0; i < 10; i++) {
    acc = acc << 8 | bytes[i];
    bits += 8;
    while (bits >= 5) {
      out += ALPHABET[acc >>> bits - 5 & 31];
      bits -= 5;
    }
  }
  return out;
}
function generateUlid(timeMs = Date.now()) {
  return encodeTime(timeMs) + encodeBytes(randomBytes(10));
}

// packages/kitchen/src/axi/commands/entries.ts
var ENTRIES_HELP = `kitchen-axi entries <subcommand> [args] [--json]

  list [--since DATE] [--limit N]      newest-first consumption entries
  show <ulid>                          one entry, full nutrition/source/status
  log [note\u2026] [--recipe ULID]          log a deliberate no-model entry
       [--component "label=grams"]\u2026      (repeatable; recipe \u2192 deterministic macros)
  patch <ulid> [flags]                 edit note/label (re-queue), macro override
                                         (terminal), or --multiplier M (post-hoc rescale)
  delete <ulid>                        remove from all rollups

  Macros on the wire are the BASE; effective = base \xD7 portion_multiplier. A
  macro flag on patch sets a terminal manual override; --multiplier only
  rescales, never re-queues estimation or changes source.`;
var DETAIL_SCHEMA = [
  field("ulid"),
  field("logged_at", "logged"),
  field("note"),
  field("label"),
  field("status"),
  field("source"),
  field("portion_multiplier", "mult"),
  field("calories", "base_kcal"),
  field("protein_g", "base_protein"),
  field("fat_g", "base_fat"),
  field("sat_fat_g", "base_sat_fat"),
  field("carbs_g", "base_carbs"),
  field("sodium_mg", "base_sodium"),
  custom("eff_kcal", (e) => effectiveMacro(e, "calories")),
  custom("eff_protein", (e) => effectiveMacro(e, "protein_g")),
  field("confidence"),
  field("portion_basis"),
  field("recipe_ulid"),
  field("last_error")
];
async function entriesCommand(args) {
  const sub = args[0];
  const rest = args.slice(1);
  switch (sub) {
    case "list":
    case void 0:
      return listEntries(sub === void 0 ? args : rest);
    case "show":
      return showEntry(rest);
    case "log":
      return logEntry(rest);
    case "patch":
      return patchEntry(rest);
    case "delete":
      return deleteEntry(rest);
    default:
      throw new AxiError(`Unknown entries subcommand: ${sub}`, "VALIDATION_ERROR", [ENTRIES_HELP]);
  }
}
async function listEntries(args) {
  const { flags } = parseArgs(args, ["json"]);
  const since = typeof flags.since === "string" ? validateDate(flags.since, "--since", ENTRIES_HELP) : void 0;
  const limit = typeof flags.limit === "string" ? String(parseNumberFlag(flags.limit, "limit", ENTRIES_HELP, { min: 1 })) : void 0;
  const result = await api.get("/api/kitchen/entries", { since, limit });
  if (flags.json) return rawJson(result);
  const entries = result?.entries ?? [];
  return renderList("entries", entries, ENTRY_ROW_SCHEMA);
}
async function showEntry(args) {
  const { positionals, flags } = parseArgs(args, ["json"]);
  const ulid = requirePositional(positionals, 0, "entry ulid", ENTRIES_HELP);
  const entry = await api.get(`/api/kitchen/entries/${encodeURIComponent(ulid)}`);
  if (flags.json) return rawJson(entry);
  return renderDetail("entry", entry, DETAIL_SCHEMA);
}
function parseComponent(raw) {
  const eq = raw.lastIndexOf("=");
  if (eq <= 0) {
    throw new AxiError(`--component must be "label=grams" (got ${raw})`, "VALIDATION_ERROR", [ENTRIES_HELP]);
  }
  const label = raw.slice(0, eq).trim();
  const qty = Number(raw.slice(eq + 1).trim());
  if (!label || !Number.isFinite(qty) || qty < 0) {
    throw new AxiError(`--component must be "label=grams" with a non-negative number (got ${raw})`, "VALIDATION_ERROR", [ENTRIES_HELP]);
  }
  return { label, quantity_g: qty };
}
async function logEntry(args) {
  const { positionals, flags } = parseArgs(args, ["json"]);
  const note = positionals.join(" ").trim();
  const recipe = typeof flags.recipe === "string" ? flags.recipe : void 0;
  const components = collectFlag(args, "component").map(parseComponent);
  if (!note && !recipe) {
    throw new AxiError("entries log needs a note and/or --recipe", "VALIDATION_ERROR", [ENTRIES_HELP]);
  }
  const entry = { ulid: generateUlid() };
  if (note) entry.note = note;
  if (recipe) entry.recipe_ulid = recipe;
  if (components.length) entry.component_quantities = components;
  const form = new FormData();
  form.append("entry", JSON.stringify(entry));
  const record = await api.postForm("/api/kitchen/entries", form);
  if (flags.json) return rawJson(record);
  const cli = cliInvocation();
  return renderOutput2([
    renderDetail("logged", record, DETAIL_SCHEMA),
    renderHelp([
      record?.status === "estimating" ? `Estimating \u2014 run \`${cli} entries show ${record?.ulid}\` to see the result` : `Run \`${cli} entries patch ${record?.ulid} --multiplier 0.5\` to rescale, or --calories N to override`
    ])
  ]);
}
async function patchEntry(args) {
  const { positionals, flags } = parseArgs(args, ["json"]);
  const ulid = requirePositional(positionals, 0, "entry ulid", ENTRIES_HELP);
  const body = {};
  if (typeof flags.note === "string") body.note = flags.note;
  if (typeof flags.label === "string") body.label = flags.label;
  if (typeof flags["portion-basis"] === "string") body.portion_basis = flags["portion-basis"];
  const macroFlags = [
    ["calories", "calories"],
    ["protein", "protein_g"],
    ["fat", "fat_g"],
    ["sat-fat", "sat_fat_g"],
    ["carbs", "carbs_g"],
    ["sodium", "sodium_mg"]
  ];
  for (const [flag, key] of macroFlags) {
    if (typeof flags[flag] === "string") body[key] = parseNumberFlag(flags[flag], flag, ENTRIES_HELP, { min: 0 });
  }
  if (typeof flags.multiplier === "string") {
    body.portion_multiplier = parseNumberFlag(flags.multiplier, "multiplier", ENTRIES_HELP, { min: 1e-4, max: 20 });
  }
  if (Object.keys(body).length === 0) {
    throw new AxiError("entries patch needs at least one field to change", "VALIDATION_ERROR", [ENTRIES_HELP]);
  }
  const updated = await api.patch(`/api/kitchen/entries/${encodeURIComponent(ulid)}`, body);
  if (flags.json) return rawJson(updated);
  return renderDetail("entry", updated, DETAIL_SCHEMA);
}
async function deleteEntry(args) {
  const { positionals, flags } = parseArgs(args, ["json"]);
  const ulid = requirePositional(positionals, 0, "entry ulid", ENTRIES_HELP);
  await api.del(`/api/kitchen/entries/${encodeURIComponent(ulid)}`);
  if (flags.json) return rawJson({ deleted: ulid });
  return renderObject({ deleted: ulid });
}

// packages/kitchen/src/axi/commands/inventory.ts
var INVENTORY_HELP = `kitchen-axi inventory <subcommand> [args] [--json]

  list [--state S] [--closed] [--limit N]   on-hand items, eat-first (eat_by asc)
  show <ulid>                               one item with derived eat_by/age
  add [flags]                               create an item (manual/verbal/seed)
  event <ulid> <opened|finished|tossed>     explicit state change
       [--fraction F] [--at DATE]
  remark "<free text>" [--at DATE]          free-text event resolver (honest match)
  questions [--limit N]                     open needs-info items as questions

  states: stocked, open, finished, tossed. For 'event \u2026 tossed', --fraction is
  the AMOUNT TOSSED \u2014 a partial toss decrements on_hand_fraction and keeps the
  item alive (self-heals at the next event); it goes terminal only at zero
  remainder or when --fraction is omitted (full toss). 'opened' --fraction is
  the absolute remaining fraction; 'finished' ignores --fraction (always zeroed).`;
var ITEM_ROW_SCHEMA = [
  field("ulid"),
  field("product_name", "name"),
  field("state"),
  field("on_hand_fraction", "on_hand"),
  field("eat_by"),
  field("days_until_eat_by", "days_left"),
  field("store"),
  { type: "boolYesNo", key: "needs_info" }
];
var ITEM_DETAIL_SCHEMA = [
  field("ulid"),
  field("product_ulid"),
  field("product_name", "name"),
  field("raw_label"),
  field("store"),
  field("state"),
  field("on_hand_fraction", "on_hand"),
  { type: "boolYesNo", key: "needs_info" },
  field("acquired_at"),
  field("opened_at"),
  field("closed_at"),
  field("eat_by"),
  field("days_until_eat_by", "days_left"),
  field("age_days"),
  field("shelf_life_class", "shelf_life"),
  field("notes")
];
var QUESTION_SCHEMA = [
  field("item_ulid", "ulid"),
  field("raw_label"),
  field("store"),
  field("acquired_at"),
  field("question")
];
var EVENT_TYPES = ["opened", "finished", "tossed"];
async function inventoryCommand(args) {
  const sub = args[0];
  const rest = args.slice(1);
  switch (sub) {
    case "list":
    case void 0:
      return listItems(sub === void 0 ? args : rest);
    case "show":
      return showItem(rest);
    case "add":
      return addItem(rest);
    case "event":
      return itemEvent(rest);
    case "remark":
      return remark(rest);
    case "questions":
      return questions(rest);
    default:
      throw new AxiError(`Unknown inventory subcommand: ${sub}`, "VALIDATION_ERROR", [INVENTORY_HELP]);
  }
}
async function listItems(args) {
  const { flags } = parseArgs(args, ["json", "closed"]);
  const state = typeof flags.state === "string" ? flags.state : void 0;
  const limit = typeof flags.limit === "string" ? String(parseNumberFlag(flags.limit, "limit", INVENTORY_HELP, { min: 1 })) : void 0;
  const result = await api.get("/api/kitchen/inventory", {
    state,
    limit,
    include_closed: flags.closed ? "true" : void 0
  });
  if (flags.json) return rawJson(result);
  const items = result?.items ?? [];
  return renderList("items", items, ITEM_ROW_SCHEMA);
}
async function showItem(args) {
  const { positionals, flags } = parseArgs(args, ["json"]);
  const ulid = requirePositional(positionals, 0, "item ulid", INVENTORY_HELP);
  const item = await api.get(`/api/kitchen/inventory/${encodeURIComponent(ulid)}`);
  if (flags.json) return rawJson(item);
  return renderDetail("item", item, ITEM_DETAIL_SCHEMA);
}
async function addItem(args) {
  const { flags } = parseArgs(args, ["json", "needs-info"]);
  const body = {};
  if (typeof flags.ulid === "string") body.ulid = flags.ulid;
  if (typeof flags["product-ulid"] === "string") body.product_ulid = flags["product-ulid"];
  if (typeof flags["raw-label"] === "string") body.raw_label = flags["raw-label"];
  if (typeof flags.store === "string") body.store = flags.store;
  if (typeof flags["batch-ulid"] === "string") body.batch_ulid = flags["batch-ulid"];
  if (typeof flags["acquired-at"] === "string") body.acquired_at = validateDate(flags["acquired-at"], "--acquired-at", INVENTORY_HELP);
  if (typeof flags.fraction === "string") body.on_hand_fraction = parseNumberFlag(flags.fraction, "fraction", INVENTORY_HELP, { min: 0, max: 1 });
  if (typeof flags.state === "string") body.state = flags.state;
  if (flags["needs-info"]) body.needs_info = true;
  if (typeof flags["shelf-life"] === "string") body.shelf_life_class = validateShelfLife(flags["shelf-life"]);
  if (typeof flags.notes === "string") body.notes = flags.notes;
  if (Object.keys(body).length === 0) {
    throw new AxiError("inventory add needs at least one field (e.g. --raw-label)", "VALIDATION_ERROR", [INVENTORY_HELP]);
  }
  const item = await api.post("/api/kitchen/inventory", body);
  if (flags.json) return rawJson(item);
  return renderDetail("item", item, ITEM_DETAIL_SCHEMA);
}
async function itemEvent(args) {
  const { positionals, flags } = parseArgs(args, ["json"]);
  const ulid = requirePositional(positionals, 0, "item ulid", INVENTORY_HELP);
  const type = requirePositional(positionals, 1, "event type", INVENTORY_HELP);
  if (!EVENT_TYPES.includes(type)) {
    throw new AxiError(`event type must be one of: ${EVENT_TYPES.join(", ")}`, "VALIDATION_ERROR", [INVENTORY_HELP]);
  }
  const body = { type };
  if (typeof flags.fraction === "string") body.fraction = parseNumberFlag(flags.fraction, "fraction", INVENTORY_HELP, { min: 0, max: 1 });
  if (typeof flags.at === "string") body.at = validateDate(flags.at, "--at", INVENTORY_HELP);
  const item = await api.post(`/api/kitchen/inventory/${encodeURIComponent(ulid)}/events`, body);
  if (flags.json) return rawJson(item);
  return renderDetail("item", item, ITEM_DETAIL_SCHEMA);
}
async function remark(args) {
  const { positionals, flags } = parseArgs(args, ["json"]);
  const text = positionals.join(" ").trim();
  if (!text) throw new AxiError("inventory remark needs free text", "VALIDATION_ERROR", [INVENTORY_HELP]);
  const body = { remark: text };
  if (typeof flags.at === "string") body.at = validateDate(flags.at, "--at", INVENTORY_HELP);
  const result = await api.post("/api/kitchen/inventory/events", body);
  if (flags.json) return rawJson(result);
  const cli = cliInvocation();
  if (!result?.matched) {
    return renderOutput2([
      renderObject({ matched: false }),
      renderHelp([`No open/stocked item matched "${text}" \u2014 this is normal; use \`${cli} inventory list\` then \`${cli} inventory event <ulid> \u2026\` to act explicitly`])
    ]);
  }
  return renderOutput2([
    renderObject({
      matched: true,
      event_type: result.event?.type ?? null,
      event_fraction: result.event?.fraction ?? null
    }),
    renderDetail("item", result.item, ITEM_DETAIL_SCHEMA)
  ]);
}
async function questions(args) {
  const { flags } = parseArgs(args, ["json"]);
  const limit = typeof flags.limit === "string" ? String(parseNumberFlag(flags.limit, "limit", INVENTORY_HELP, { min: 1 })) : void 0;
  const result = await api.get("/api/kitchen/inventory/questions", { limit });
  if (flags.json) return rawJson(result);
  const q = result?.questions ?? [];
  return renderList("questions", q, QUESTION_SCHEMA);
}
function validateShelfLife(value) {
  if (!SHELF_LIFE_CLASSES.includes(value)) {
    throw new AxiError(`--shelf-life must be one of: ${SHELF_LIFE_CLASSES.join(", ")}`, "VALIDATION_ERROR", [INVENTORY_HELP]);
  }
  return value;
}

// packages/kitchen/src/axi/commands/receipts.ts
import { existsSync } from "node:fs";
var RECEIPTS_HELP = `kitchen-axi receipts <subcommand> [args] [--json]

  list [--limit N]                          recent purchase batches + parse status
  show <ulid>                               one batch + parsed line outcomes
  scan <photo\u2026> [--store S]                 post a batch from receipt photos
       [--purchased-at DATE] [--ulid U]       (parses asynchronously)

  scan posts immediately (status 'parsing') and is idempotent on --ulid (one is
  generated when omitted). The receipt meta is sent as a multipart form FIELD,
  photos as file parts. A cheap model then extracts lines; known lines (via the
  store lexicon) become stocked items, unknown lines become needs-info items.`;
var BATCH_ROW_SCHEMA = [
  field("ulid"),
  field("store"),
  field("purchased_at", "purchased"),
  field("status"),
  field("parse_attempts", "attempts"),
  field("last_error")
];
var LINE_SCHEMA = [
  field("raw_text", "line"),
  field("match_outcome", "outcome"),
  field("product_ulid"),
  field("inventory_item_ulid", "item_ulid")
];
async function receiptsCommand(args) {
  const sub = args[0];
  const rest = args.slice(1);
  switch (sub) {
    case "list":
    case void 0:
      return listBatches(sub === void 0 ? args : rest);
    case "show":
      return showBatch(rest);
    case "scan":
      return scanReceipt(rest);
    default:
      throw new AxiError(`Unknown receipts subcommand: ${sub}`, "VALIDATION_ERROR", [RECEIPTS_HELP]);
  }
}
async function listBatches(args) {
  const { flags } = parseArgs(args, ["json"]);
  const limit = typeof flags.limit === "string" ? String(parseNumberFlag(flags.limit, "limit", RECEIPTS_HELP, { min: 1 })) : void 0;
  const result = await api.get("/api/kitchen/receipts", { limit });
  if (flags.json) return rawJson(result);
  const batches = result?.batches ?? [];
  return renderList("batches", batches, BATCH_ROW_SCHEMA);
}
async function showBatch(args) {
  const { positionals, flags } = parseArgs(args, ["json"]);
  const ulid = requirePositional(positionals, 0, "batch ulid", RECEIPTS_HELP);
  const result = await api.get(`/api/kitchen/receipts/${encodeURIComponent(ulid)}`);
  if (flags.json) return rawJson(result);
  const lines = result?.lines ?? [];
  return renderOutput2([
    renderDetail("batch", result?.batch ?? {}, BATCH_ROW_SCHEMA),
    renderList("lines", lines, LINE_SCHEMA)
  ]);
}
async function scanReceipt(args) {
  const { positionals, flags } = parseArgs(args, ["json"]);
  const photos = positionals;
  if (photos.length === 0) {
    throw new AxiError("receipts scan needs at least one photo path", "VALIDATION_ERROR", [RECEIPTS_HELP]);
  }
  for (const p of photos) {
    if (!existsSync(p)) throw new AxiError(`Photo not found: ${p}`, "VALIDATION_ERROR", [RECEIPTS_HELP]);
  }
  const meta = { ulid: typeof flags.ulid === "string" ? flags.ulid : generateUlid() };
  if (typeof flags.store === "string") meta.store = flags.store;
  if (typeof flags["purchased-at"] === "string") meta.purchased_at = validateDate(flags["purchased-at"], "--purchased-at", RECEIPTS_HELP);
  const form = await buildMultipartForm("receipt", meta, photos);
  const batch = await api.postForm("/api/kitchen/receipts", form);
  if (flags.json) return rawJson(batch);
  const cli = cliInvocation();
  return renderOutput2([
    renderDetail("batch", batch, BATCH_ROW_SCHEMA),
    renderHelp([`Parsing asynchronously \u2014 run \`${cli} receipts show ${batch?.ulid}\` to see extracted lines`])
  ]);
}

// packages/kitchen/src/axi/commands/recipes.ts
var RECIPES_HELP = `kitchen-axi recipes <subcommand> [args] [--json]

  list [--limit N]                  the reselect strip: merged sheet + pushed +
                                      promoted recipes, plus recent logged items
  push '<recipe json>'              agent-authored template; body is
                                      {"name": "...", "components": [
                                        {"label": "...", "default_qty_g": N,
                                         "per_100g": {"calories": N, "protein_g": N,
                                                      "sat_fat_g": N}} ]}
  promote <entry-ulid> --name NAME  create a reusable recipe from a logged entry`;
var RECIPE_SCHEMA = [
  field("ulid"),
  field("name"),
  field("source"),
  count("components", "n_components")
];
var RECENT_SCHEMA = [
  field("label"),
  field("log_count", "logged"),
  field("calories", "kcal"),
  field("protein_g", "protein"),
  { type: "dateOnly", key: "last_logged_at", as: "last" }
];
async function recipesCommand(args) {
  const sub = args[0];
  const rest = args.slice(1);
  switch (sub) {
    case "list":
    case void 0:
      return listRecipes(sub === void 0 ? args : rest);
    case "push":
      return pushRecipe(rest);
    case "promote":
      return promote(rest);
    default:
      throw new AxiError(`Unknown recipes subcommand: ${sub}`, "VALIDATION_ERROR", [RECIPES_HELP]);
  }
}
async function listRecipes(args) {
  const { flags } = parseArgs(args, ["json"]);
  const limit = typeof flags.limit === "string" ? String(parseNumberFlag(flags.limit, "limit", RECIPES_HELP, { min: 1 })) : void 0;
  const strip = await api.get("/api/kitchen/reselect", { limit });
  if (flags.json) return rawJson(strip);
  const recipes = strip?.recipes ?? [];
  const recent = strip?.recent ?? [];
  return renderOutput2([
    renderList("recipes", recipes, RECIPE_SCHEMA),
    renderList("recent", recent, RECENT_SCHEMA)
  ]);
}
async function pushRecipe(args) {
  const { positionals, flags } = parseArgs(args, ["json"]);
  const jsonArg = positionals[0];
  if (!jsonArg) {
    throw new AxiError("recipes push needs a recipe JSON body", "VALIDATION_ERROR", [RECIPES_HELP]);
  }
  const body = parseJson(jsonArg, "recipe", RECIPES_HELP);
  const recipe = await api.post("/api/kitchen/recipes", body);
  if (flags.json) return rawJson(recipe);
  return renderDetail("recipe", recipe, [...RECIPE_SCHEMA, custom("components", (r) => JSON.stringify(r.components ?? []))]);
}
async function promote(args) {
  const { positionals, flags } = parseArgs(args, ["json"]);
  const ulid = requirePositional(positionals, 0, "entry ulid", RECIPES_HELP);
  const name = requireFlag(flags, "name", RECIPES_HELP);
  const recipe = await api.post(`/api/kitchen/entries/${encodeURIComponent(ulid)}/promote`, { name });
  if (flags.json) return rawJson(recipe);
  return renderDetail("recipe", recipe, RECIPE_SCHEMA);
}

// packages/kitchen/src/axi/commands/products.ts
var PRODUCTS_HELP = `kitchen-axi products <subcommand> [args] [--json]

  list [--q TEXT] [--limit N]       products (durable item facts); --q matches
                                      name/aliases (substring)
  add --name NAME [flags]           seed a product
       [--shelf-life C] [--aliases a,b] [--package-size S]
       [--nutrition '<json>'] [--shelf-life-days-unopened N]
       [--shelf-life-days-opened N]

  shelf-life classes: ${SHELF_LIFE_CLASSES.join(", ")}
  --nutrition is a JSON object of per-100g macros, e.g.
    '{"calories": 52, "protein_g": 0.3, "carbs_g": 14}'`;
var PRODUCT_ROW_SCHEMA = [
  field("ulid"),
  field("name"),
  field("shelf_life_class", "shelf_life"),
  joinArray("aliases", void 0, "aliases"),
  field("package_size", "pkg")
];
var PRODUCT_DETAIL_SCHEMA = [
  field("ulid"),
  field("name"),
  field("shelf_life_class", "shelf_life"),
  joinArray("aliases", void 0, "aliases"),
  field("package_size", "pkg"),
  field("shelf_life_days_unopened", "days_unopened"),
  field("shelf_life_days_opened", "days_opened"),
  {
    type: "custom",
    as: "nutrition_per_100g",
    fn: (p) => p.nutrition_per_100g ? JSON.stringify(p.nutrition_per_100g) : null
  }
];
async function productsCommand(args) {
  const sub = args[0];
  const rest = args.slice(1);
  switch (sub) {
    case "list":
    case void 0:
      return listProducts(sub === void 0 ? args : rest);
    case "add":
      return addProduct(rest);
    default:
      throw new AxiError(`Unknown products subcommand: ${sub}`, "VALIDATION_ERROR", [PRODUCTS_HELP]);
  }
}
async function listProducts(args) {
  const { flags } = parseArgs(args, ["json"]);
  const q = typeof flags.q === "string" ? flags.q : void 0;
  const limit = typeof flags.limit === "string" ? String(parseNumberFlag(flags.limit, "limit", PRODUCTS_HELP, { min: 1 })) : void 0;
  const result = await api.get("/api/kitchen/products", { q, limit });
  if (flags.json) return rawJson(result);
  const products = result?.products ?? [];
  return renderList("products", products, PRODUCT_ROW_SCHEMA);
}
async function addProduct(args) {
  const { flags } = parseArgs(args, ["json"]);
  const name = requireFlag(flags, "name", PRODUCTS_HELP);
  const body = { name };
  if (typeof flags["shelf-life"] === "string") body.shelf_life_class = validateShelfLife2(flags["shelf-life"]);
  if (typeof flags.aliases === "string") body.aliases = splitCsv(flags.aliases);
  if (typeof flags["package-size"] === "string") body.package_size = flags["package-size"];
  if (typeof flags.nutrition === "string") body.nutrition_per_100g = parseJson(flags.nutrition, "--nutrition", PRODUCTS_HELP);
  if (typeof flags["shelf-life-days-unopened"] === "string") body.shelf_life_days_unopened = parseNumberFlag(flags["shelf-life-days-unopened"], "shelf-life-days-unopened", PRODUCTS_HELP, { min: 0 });
  if (typeof flags["shelf-life-days-opened"] === "string") body.shelf_life_days_opened = parseNumberFlag(flags["shelf-life-days-opened"], "shelf-life-days-opened", PRODUCTS_HELP, { min: 0 });
  const product = await api.post("/api/kitchen/products", body);
  if (flags.json) return rawJson(product);
  return renderDetail("product", product, PRODUCT_DETAIL_SCHEMA);
}
function validateShelfLife2(value) {
  if (!SHELF_LIFE_CLASSES.includes(value)) {
    throw new AxiError(`--shelf-life must be one of: ${SHELF_LIFE_CLASSES.join(", ")}`, "VALIDATION_ERROR", [PRODUCTS_HELP]);
  }
  return value;
}

// packages/kitchen/src/axi/commands/lexicon.ts
var LEXICON_HELP = `kitchen-axi lexicon <subcommand> [args] [--json]

  list [--store S] [--limit N]              receipt-line \u2192 product mappings
  add --store S --line-text T               map a store's receipt line to a
      --product-ulid U [--package-size S]     product; upserts on (store, line);
      [--shelf-life C]                        future receipts auto-resolve it

  shelf-life classes: ${SHELF_LIFE_CLASSES.join(", ")}`;
var LEXICON_SCHEMA = [
  field("store"),
  field("line_text", "line"),
  field("product_ulid"),
  field("package_size", "pkg"),
  field("shelf_life_class", "shelf_life")
];
async function lexiconCommand(args) {
  const sub = args[0];
  const rest = args.slice(1);
  switch (sub) {
    case "list":
    case void 0:
      return listLexicon(sub === void 0 ? args : rest);
    case "add":
      return addLexicon(rest);
    default:
      throw new AxiError(`Unknown lexicon subcommand: ${sub}`, "VALIDATION_ERROR", [LEXICON_HELP]);
  }
}
async function listLexicon(args) {
  const { flags } = parseArgs(args, ["json"]);
  const store = typeof flags.store === "string" ? flags.store : void 0;
  const limit = typeof flags.limit === "string" ? String(parseNumberFlag(flags.limit, "limit", LEXICON_HELP, { min: 1 })) : void 0;
  const result = await api.get("/api/kitchen/lexicon", { store, limit });
  if (flags.json) return rawJson(result);
  const lines = result?.lines ?? [];
  return renderList("lexicon", lines, LEXICON_SCHEMA);
}
async function addLexicon(args) {
  const { flags } = parseArgs(args, ["json"]);
  const body = {
    store: requireFlag(flags, "store", LEXICON_HELP),
    line_text: requireFlag(flags, "line-text", LEXICON_HELP),
    product_ulid: requireFlag(flags, "product-ulid", LEXICON_HELP)
  };
  if (typeof flags["package-size"] === "string") body.package_size = flags["package-size"];
  if (typeof flags["shelf-life"] === "string") body.shelf_life_class = validateShelfLife3(flags["shelf-life"]);
  const line = await api.post("/api/kitchen/lexicon", body);
  if (flags.json) return rawJson(line);
  return renderDetail("lexicon", line, LEXICON_SCHEMA);
}
function validateShelfLife3(value) {
  if (!SHELF_LIFE_CLASSES.includes(value)) {
    throw new AxiError(`--shelf-life must be one of: ${SHELF_LIFE_CLASSES.join(", ")}`, "VALIDATION_ERROR", [LEXICON_HELP]);
  }
  return value;
}

// packages/kitchen/src/axi/cli.ts
var VERSION = true ? "35ff6ec" : "dev";
var CLI = cliInvocation();
var TOP_HELP = `usage: ${CLI} [group] [subcommand] [args] [flags]
       ${CLI}                 # no args \u2192 home (today's totals + eat-first + questions)

commands:

${commandReferenceText()}

flags: --help, -v/--version, --json (raw output on most commands)

env: CLAUDE_ASSIST_SERVER (default http://localhost:2529)

examples:
  ${CLI}
  ${CLI} entries log "chicken and rice bowl"
  ${CLI} entries patch 01J\u2026 --multiplier 0.5
  ${CLI} inventory remark "opened the oat milk"
  ${CLI} receipts scan ./receipt-front.jpg ./receipt-back.jpg --store "Corner Market"
`;
var COMMAND_HELP = {
  home: HOME_HELP,
  entries: ENTRIES_HELP,
  inventory: INVENTORY_HELP,
  receipts: RECEIPTS_HELP,
  recipes: RECIPES_HELP,
  products: PRODUCTS_HELP,
  lexicon: LEXICON_HELP
};
var COMMANDS = {
  home: (args) => homeCommand(args),
  entries: (args) => entriesCommand(args),
  inventory: (args) => inventoryCommand(args),
  receipts: (args) => receiptsCommand(args),
  recipes: (args) => recipesCommand(args),
  products: (args) => productsCommand(args),
  lexicon: (args) => lexiconCommand(args)
};
async function main(argv) {
  await runAxiCli({
    description: DESCRIPTION,
    version: VERSION,
    ...argv ? { argv } : {},
    topLevelHelp: TOP_HELP,
    home: (args) => homeCommand(args),
    commands: COMMANDS,
    getCommandHelp: (command) => COMMAND_HELP[command]
  });
}

// packages/kitchen/src/axi/bin.ts
await main();
