#!/usr/bin/env node
// GENERATED by scripts/build-cli.ts from src/axi/ — do not edit. Run `bun run build:cli`.

// packages/pages/src/axi/bin.ts
import { readFile } from "node:fs/promises";

// packages/pages/src/axi/index.ts
var DEFAULT_SERVER = "http://localhost:2529";
function resolveServer(env = process.env) {
  const value = env.CLAUDE_ASSIST_SERVER?.trim();
  return (value || DEFAULT_SERVER).replace(/\/+$/, "");
}
function toonValue(value) {
  if (value === null || value === void 0) return "null";
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  const s = value instanceof Date ? value.toISOString() : String(value);
  if (s === "" || /[",:\n{}[\]]/.test(s) || /^\s|\s$/.test(s)) return JSON.stringify(s);
  return s;
}
function renderObject(label, obj) {
  const lines = [`${label}:`];
  for (const [key, value] of Object.entries(obj)) {
    lines.push(`  ${key}: ${toonValue(value)}`);
  }
  return lines.join("\n");
}
function renderTable(label, rows, cols) {
  const keys = cols ?? Object.keys(rows[0] ?? {});
  if (rows.length === 0) return `${label}[0]`;
  const header = `${label}[${rows.length}]{${keys.join(",")}}:`;
  const body = rows.map((row) => `  ${keys.map((k) => toonValue(row[k])).join(",")}`);
  return [header, ...body].join("\n");
}
function renderHelp(lines) {
  const clean = lines.filter(Boolean);
  if (clean.length === 0) return "";
  return `help[${clean.length}]:
${clean.map((l) => `  ${l}`).join("\n")}`;
}
function renderOutput(blocks) {
  return blocks.filter(Boolean).join("\n");
}
function formatRelativeTime(value, nowMs = Date.now()) {
  if (!value) return "unknown";
  const then = new Date(value).getTime();
  if (isNaN(then)) return "unknown";
  const diffSec = Math.floor((nowMs - then) / 1e3);
  const past = diffSec >= 0;
  const s = Math.abs(diffSec);
  const fmt = (n, unit) => past ? `${n}${unit} ago` : `in ${n}${unit}`;
  if (s < 60) return past ? "just now" : "soon";
  const min = Math.floor(s / 60);
  if (min < 60) return fmt(min, "m");
  const hr = Math.floor(min / 60);
  if (hr < 24) return fmt(hr, "h");
  const day = Math.floor(hr / 24);
  if (day < 30) return fmt(day, "d");
  const mon = Math.floor(day / 30);
  if (mon < 12) return fmt(mon, "mo");
  return fmt(Math.floor(mon / 12), "y");
}
function parseFlags(argv, valueFlags, boolFlags = []) {
  const positional = [];
  const flags = {};
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (!arg.startsWith("--")) {
      positional.push(arg);
      continue;
    }
    const name = arg.slice(2);
    if (boolFlags.includes(name)) {
      flags[name] = true;
    } else if (valueFlags.includes(name)) {
      const value = argv[++i];
      if (value === void 0) throw new Error(`missing value for --${name}`);
      flags[name] = value;
    } else {
      throw new Error(`unknown flag --${name}`);
    }
  }
  return { positional, flags };
}
function extractHtmlTitle(html) {
  const match = html.match(/<title[^>]*>([^<]*)<\/title>/i);
  const title = match?.[1]?.trim();
  return title ? title : null;
}
function titleFromSlug(slug) {
  return slug.split("-").map((word) => word ? word[0].toUpperCase() + word.slice(1) : word).join(" ");
}

// packages/pages/src/axi/reference.ts
var DESCRIPTION = "Publish self-contained HTML pages and worksheets to stable URLs, and collect structured responses back from them.";
var COMMAND_GROUPS = [
  {
    group: "Publish",
    commands: [
      {
        usage: "publish <file> --slug <slug> [--title <title>] [--digest-optin]",
        summary: "publish (or republish) a self-contained HTML file; prints the stable URL. Republishing a slug adds a version at the same URL. --title defaults to the file's <title>, then the slug"
      },
      {
        usage: "publish-worksheet <definition.json> --slug <slug> [--title <title>] [--digest-optin]",
        summary: "publish a WORKSHEET \u2014 weighable components whose real quantities the human states, with totals computed server-side. Use this for anything that collects measured amounts; a hand-authored HTML form re-implements arithmetic the module already owns. Pass `-` to read the definition from stdin"
      },
      {
        usage: "archive <slug>",
        summary: "remove a page from the index (all storage retained; republishing revives it)"
      }
    ]
  },
  {
    group: "Collect",
    commands: [
      {
        usage: "list",
        summary: "active pages, newest first, with their response backlog"
      },
      {
        usage: "responses <slug> [--since <iso>] [--unprocessed]",
        summary: "read a page's response queue (oldest first)"
      },
      {
        usage: "mark-processed <slug> <id> --by <name>",
        summary: "mark one response handled (append-only: never alters the payload)"
      }
    ]
  }
];
var WORKSHEET_SHAPE = `{
  "kind": "worksheet", "version": 1,
  "heading": "\u2026", "intro": "\u2026",          // optional
  "basis": 100, "unit": "g",              // per-N reference basis, quantity unit
  "fields":     [ { "key": "calories", "label": "Calories", "precision": 0 } ],
  "components": [ { "label": "\u2026", "quantity": 200,
                    "per_basis": { "calories": 130 }, "note": "\u2026" } ],
  "steps": ["\u2026"],                         // optional instructions
  "submit_label": "\u2026",                    // optional
  "cook_mode": { \u2026 }                      // optional; opaque to this CLI \u2014
}                                         //   see the consuming module's spec`;

// packages/pages/src/axi/bin.ts
function buildHelp() {
  const groups = COMMAND_GROUPS.map((group) => {
    const items = group.commands.map((c) => `  ${c.usage}
      ${c.summary.replace(/\s+/g, " ")}`).join("\n");
    return `${group.group.toLowerCase()}:
${items}`;
  }).join("\n\n");
  return `usage: pages-axi <command> [args] [flags]

${DESCRIPTION}

${groups}

worksheet definition shape (for publish-worksheet):
${WORKSHEET_SHAPE.split("\n").map((l) => `  ${l}`).join("\n")}

env: CLAUDE_ASSIST_SERVER (default http://localhost:2529)

examples:
  pages-axi                                        # home view: pages + backlog
  pages-axi publish ./review.html --slug design-review
  pages-axi publish-worksheet ./prep.json --slug prep-today
  pages-axi responses design-review --unprocessed
  pages-axi mark-processed design-review 3 --by my-session
`;
}
var server = resolveServer();
function fail(message, code = 1) {
  console.error(`pages-axi: ${message}`);
  process.exit(code);
}
async function api(method, path, body) {
  let response;
  try {
    response = await fetch(`${server}${path}`, {
      method,
      headers: body !== void 0 ? { "Content-Type": "application/json" } : {},
      ...body !== void 0 ? { body: JSON.stringify(body) } : {},
      signal: AbortSignal.timeout(3e4)
    });
  } catch (error) {
    fail(
      `cannot reach server at ${server} (${error instanceof Error ? error.message : String(error)}) \u2014 set CLAUDE_ASSIST_SERVER or start the server`
    );
  }
  const text = await response.text();
  if (!response.ok) {
    let message = text.slice(0, 300);
    try {
      const parsed = JSON.parse(text);
      if (parsed?.error) message = parsed.error;
    } catch {
    }
    fail(`server returned ${response.status}: ${message}`);
  }
  return text ? JSON.parse(text) : null;
}
async function readInput(file) {
  if (file === "-") {
    const chunks = [];
    for await (const chunk of process.stdin) chunks.push(chunk);
    return Buffer.concat(chunks).toString("utf8");
  }
  try {
    return await readFile(file, "utf8");
  } catch {
    fail(`file not found or unreadable: ${file}`, 2);
  }
}
function reportPublished(result, extraHelp = []) {
  console.log(
    renderOutput([
      renderObject("published", {
        slug: result.slug,
        title: result.title,
        url: result.url,
        version: result.version,
        created: result.created,
        ...result.worksheet ? { worksheet: result.worksheet } : {},
        ...result.cook_mode ? { cook_mode: result.cook_mode } : {}
      }),
      renderHelp([
        `Run \`pages-axi responses ${result.slug}\` to read collected responses`,
        `Republish with the same --slug to push a new version at the same URL`,
        ...extraHelp
      ])
    ])
  );
}
async function publish(argv) {
  const { positional, flags } = parseFlags(argv, ["slug", "title"], ["digest-optin"]);
  const file = positional[0];
  const slug = flags.slug;
  if (!file || !slug) fail("usage: pages-axi publish <file> --slug <slug> [--title <title>]", 2);
  const html = await readInput(file);
  if (!html.trim()) fail(`file is empty: ${file}`, 2);
  const title = flags.title ?? extractHtmlTitle(html) ?? titleFromSlug(slug);
  reportPublished(
    await api("POST", "/api/pages", {
      slug,
      title,
      html,
      ...flags["digest-optin"] ? { digest_optin: true } : {}
    })
  );
}
async function publishWorksheet(argv) {
  const { positional, flags } = parseFlags(argv, ["slug", "title"], ["digest-optin"]);
  const file = positional[0];
  const slug = flags.slug;
  if (!file || !slug) {
    fail("usage: pages-axi publish-worksheet <definition.json> --slug <slug> [--title <title>]", 2);
  }
  const raw = await readInput(file);
  if (!raw.trim()) fail(`definition is empty: ${file}`, 2);
  let worksheet;
  try {
    worksheet = JSON.parse(raw);
  } catch (error) {
    fail(
      `definition is not valid JSON (${error instanceof Error ? error.message : String(error)})

expected shape:
${WORKSHEET_SHAPE}`,
      2
    );
  }
  const title = flags.title ?? titleFromSlug(slug);
  reportPublished(
    await api("POST", "/api/pages", {
      slug,
      title,
      worksheet,
      ...flags["digest-optin"] ? { digest_optin: true } : {}
    }),
    ["A submission computes its totals server-side \u2014 the page never states results"]
  );
}
async function fetchPages() {
  const result = await api("GET", "/api/pages");
  return result.pages ?? [];
}
function pageRows(pages) {
  return pages.map((p) => ({
    slug: p.slug,
    title: p.title,
    updated: formatRelativeTime(p.updated_at),
    responses: p.response_count ?? 0,
    unprocessed: p.unprocessed_count ?? 0,
    url: p.url
  }));
}
var PAGE_COLUMNS = ["slug", "title", "updated", "responses", "unprocessed", "url"];
async function list() {
  const pages = await fetchPages();
  const rows = pageRows(pages);
  console.log(
    renderOutput([
      renderTable("pages", rows, PAGE_COLUMNS),
      renderHelp(
        rows.length > 0 ? [`Run \`pages-axi responses <slug>\` to read a page's response queue`] : [`Run \`pages-axi publish <file> --slug <slug>\` to publish a page`]
      )
    ])
  );
}
async function home() {
  const pages = await fetchPages();
  const backlog = pages.reduce((sum, p) => sum + (p.unprocessed_count ?? 0), 0);
  const waiting = pages.filter((p) => (p.unprocessed_count ?? 0) > 0);
  console.log(
    renderOutput([
      renderObject("pages-axi", {
        server,
        active_pages: pages.length,
        unprocessed_responses: backlog
      }),
      renderTable("pages", pageRows(pages).slice(0, 10), PAGE_COLUMNS),
      renderHelp([
        // Cap the per-page nudges: an instance with a long backlog would
        // otherwise bury the rest of the help under one line per page.
        ...waiting.slice(0, 3).map(
          (p) => `Run \`pages-axi responses ${p.slug} --unprocessed\` \u2014 ${p.unprocessed_count} waiting`
        ),
        ...waiting.length > 3 ? [`${waiting.length - 3} more pages have unhandled responses \u2014 \`pages-axi list\``] : [],
        `Run \`pages-axi publish-worksheet <def.json> --slug <slug>\` to collect measured quantities`,
        `Run \`pages-axi --help\` for the full command list`
      ])
    ])
  );
}
async function responses(argv) {
  const { positional, flags } = parseFlags(argv, ["since"], ["unprocessed"]);
  const slug = positional[0];
  if (!slug) fail("usage: pages-axi responses <slug> [--since <iso>] [--unprocessed]", 2);
  const query = new URLSearchParams();
  if (flags.since) query.set("since", flags.since);
  if (flags.unprocessed) query.set("unprocessed", "true");
  const qs = query.toString();
  const result = await api(
    "GET",
    `/api/pages/${encodeURIComponent(slug)}/responses${qs ? `?${qs}` : ""}`
  );
  const rows = result.responses.map((r) => ({
    id: r.id,
    payload: JSON.stringify(r.payload),
    anchor: r.anchor ?? "",
    note: r.note ?? "",
    received: formatRelativeTime(r.created_at),
    processed_by: r.processed_by ?? ""
  }));
  console.log(
    renderOutput([
      renderTable("responses", rows, ["id", "payload", "anchor", "note", "received", "processed_by"]),
      renderHelp(
        rows.length > 0 ? [`Run \`pages-axi mark-processed ${slug} <id> --by <name>\` after handling one`] : []
      )
    ])
  );
}
async function markProcessed(argv) {
  const { positional, flags } = parseFlags(argv, ["by"]);
  const [slug, id] = positional;
  const by = flags.by;
  if (!slug || !id || !by) fail("usage: pages-axi mark-processed <slug> <id> --by <name>", 2);
  const result = await api(
    "POST",
    `/api/pages/${encodeURIComponent(slug)}/responses/${encodeURIComponent(id)}/processed`,
    { processed_by: by }
  );
  console.log(
    renderObject("processed", {
      id: result.id,
      processed_by: result.processed_by,
      processed_at: result.processed_at
    })
  );
}
async function archive(argv) {
  const { positional } = parseFlags(argv, []);
  const slug = positional[0];
  if (!slug) fail("usage: pages-axi archive <slug>", 2);
  const result = await api("POST", `/api/pages/${encodeURIComponent(slug)}/archive`);
  console.log(
    renderOutput([
      renderObject("archived", { slug: result.slug, archived_at: result.archived_at }),
      renderHelp([`Republish the slug to reactivate it at the same URL`])
    ])
  );
}
var [command, ...rest] = process.argv.slice(2);
try {
  switch (command) {
    case "publish":
      await publish(rest);
      break;
    case "publish-worksheet":
      await publishWorksheet(rest);
      break;
    case "list":
      await list();
      break;
    case "responses":
      await responses(rest);
      break;
    case "mark-processed":
      await markProcessed(rest);
      break;
    case "archive":
      await archive(rest);
      break;
    case void 0:
      await home();
      break;
    case "-h":
    case "--help":
    case "help":
      console.log(buildHelp());
      break;
    default:
      fail(`unknown command: ${command}

${buildHelp()}`, 2);
  }
} catch (error) {
  fail(error instanceof Error ? error.message : String(error), 2);
}
