#!/usr/bin/env node
// GENERATED by scripts/build-cli.ts from src/axi/ — do not edit. Run `bun run build:cli`.

// node_modules/.bun/axi-sdk-js@0.1.7/node_modules/axi-sdk-js/dist/cli.js
import { basename } from "node:path";

// node_modules/.bun/axi-sdk-js@0.1.7/node_modules/axi-sdk-js/dist/errors.js
var AxiError = class extends Error {
  code;
  suggestions;
  constructor(message, code, suggestions = []) {
    super(message);
    this.code = code;
    this.suggestions = suggestions;
    this.name = "AxiError";
  }
};
function exitCodeForError(error) {
  if (error instanceof AxiError && error.code === "VALIDATION_ERROR") {
    return 2;
  }
  return 1;
}

// node_modules/.bun/axi-sdk-js@0.1.7/node_modules/axi-sdk-js/dist/output.js
import { homedir } from "node:os";

// node_modules/.bun/@toon-format+toon@2.3.0/node_modules/@toon-format/toon/dist/index.mjs
var NULL_LITERAL = "null";
var DELIMITERS = {
  comma: ",",
  tab: "	",
  pipe: "|"
};
var DEFAULT_DELIMITER = DELIMITERS.comma;
function escapeString(value) {
  return value.replace(/\\/g, `\\\\`).replace(/"/g, `\\"`).replace(/\n/g, `\\n`).replace(/\r/g, `\\r`).replace(/\t/g, `\\t`).replace(/[\u0000-\u001F]/g, (c) => `\\u${c.charCodeAt(0).toString(16).padStart(4, "0")}`);
}
function isBooleanOrNullLiteral(token) {
  return token === "true" || token === "false" || token === "null";
}
function normalizeValue(value) {
  if (value === null) return null;
  if (typeof value === "object" && value !== null && "toJSON" in value && typeof value.toJSON === "function") {
    const next = value.toJSON();
    if (next !== value) return normalizeValue(next);
  }
  if (typeof value === "string" || typeof value === "boolean") return value;
  if (typeof value === "number") {
    if (Object.is(value, -0)) return 0;
    if (!Number.isFinite(value)) return null;
    return value;
  }
  if (typeof value === "bigint") {
    if (value >= Number.MIN_SAFE_INTEGER && value <= Number.MAX_SAFE_INTEGER) return Number(value);
    return value.toString();
  }
  if (value instanceof Date) return value.toISOString();
  if (Array.isArray(value)) return value.map(normalizeValue);
  if (value instanceof Set) return Array.from(value).map(normalizeValue);
  if (value instanceof Map) return Object.fromEntries(Array.from(value, ([k, v]) => [String(k), normalizeValue(v)]));
  if (isPlainObject(value)) {
    const encodedValues = {};
    for (const key in value) if (Object.hasOwn(value, key)) encodedValues[key] = normalizeValue(value[key]);
    return encodedValues;
  }
  return null;
}
function isJsonPrimitive(value) {
  return value === null || typeof value === "string" || typeof value === "number" || typeof value === "boolean";
}
function isJsonArray(value) {
  return Array.isArray(value);
}
function isJsonObject(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}
function isEmptyObject(value) {
  return Object.keys(value).length === 0;
}
function isPlainObject(value) {
  if (value === null || typeof value !== "object") return false;
  const prototype = Object.getPrototypeOf(value);
  return prototype === null || prototype === Object.prototype;
}
function isArrayOfPrimitives(value) {
  return value.length === 0 || value.every((item) => isJsonPrimitive(item));
}
function isArrayOfArrays(value) {
  return value.length === 0 || value.every((item) => isJsonArray(item));
}
function isArrayOfObjects(value) {
  return value.length === 0 || value.every((item) => isJsonObject(item));
}
var NUMERIC_LIKE_PATTERN = /^-?\d+(?:\.\d+)?(?:e[+-]?\d+)?$/i;
var LEADING_ZERO_PATTERN = /^0\d+$/;
function isValidUnquotedKey(key) {
  return /^[A-Z_][\w.]*$/i.test(key);
}
function isIdentifierSegment(key) {
  return /^[A-Z_]\w*$/i.test(key);
}
function isSafeUnquoted(value, delimiter = DEFAULT_DELIMITER) {
  if (!value) return false;
  if (value !== value.trim()) return false;
  if (isBooleanOrNullLiteral(value) || isNumericLike(value)) return false;
  if (value.includes(":")) return false;
  if (value.includes('"') || value.includes("\\")) return false;
  if (/[[\]{}]/.test(value)) return false;
  if (/[\u0000-\u001F]/.test(value)) return false;
  if (value.includes(delimiter)) return false;
  if (value.startsWith("-")) return false;
  return true;
}
function isNumericLike(value) {
  return NUMERIC_LIKE_PATTERN.test(value) || LEADING_ZERO_PATTERN.test(value);
}
function tryFoldKeyChain(key, value, siblings, options, rootLiteralKeys, pathPrefix, flattenDepth) {
  if (options.keyFolding !== "safe") return;
  if (!isJsonObject(value)) return;
  const { segments, tail, leafValue } = collectSingleKeyChain(key, value, flattenDepth ?? options.flattenDepth);
  if (segments.length < 2) return;
  if (!segments.every((seg) => isIdentifierSegment(seg))) return;
  const foldedKey = buildFoldedKey(segments);
  const absolutePath = pathPrefix ? `${pathPrefix}.${foldedKey}` : foldedKey;
  if (siblings.includes(foldedKey)) return;
  if (rootLiteralKeys && rootLiteralKeys.has(absolutePath)) return;
  return {
    foldedKey,
    remainder: tail,
    leafValue,
    segmentCount: segments.length
  };
}
function collectSingleKeyChain(startKey, startValue, maxDepth) {
  const segments = [startKey];
  let currentValue = startValue;
  while (segments.length < maxDepth) {
    if (!isJsonObject(currentValue)) break;
    const keys = Object.keys(currentValue);
    if (keys.length !== 1) break;
    const nextKey = keys[0];
    const nextValue = currentValue[nextKey];
    segments.push(nextKey);
    currentValue = nextValue;
  }
  if (!isJsonObject(currentValue) || isEmptyObject(currentValue)) return {
    segments,
    tail: void 0,
    leafValue: currentValue
  };
  return {
    segments,
    tail: currentValue,
    leafValue: currentValue
  };
}
function buildFoldedKey(segments) {
  return segments.join(".");
}
function encodePrimitive(value, delimiter) {
  if (value === null) return NULL_LITERAL;
  if (typeof value === "boolean") return String(value);
  if (typeof value === "number") return String(value);
  return encodeStringLiteral(value, delimiter);
}
function encodeStringLiteral(value, delimiter = DEFAULT_DELIMITER) {
  if (isSafeUnquoted(value, delimiter)) return value;
  return `"${escapeString(value)}"`;
}
function encodeKey(key) {
  if (isValidUnquotedKey(key)) return key;
  return `"${escapeString(key)}"`;
}
function encodeAndJoinPrimitives(values, delimiter = DEFAULT_DELIMITER) {
  return values.map((v) => encodePrimitive(v, delimiter)).join(delimiter);
}
function formatHeader(length, options) {
  const key = options?.key;
  const fields = options?.fields;
  const delimiter = options?.delimiter ?? ",";
  let header = "";
  if (key != null) header += encodeKey(key);
  header += `[${length}${delimiter !== DEFAULT_DELIMITER ? delimiter : ""}]`;
  if (fields) {
    const quotedFields = fields.map((f) => encodeKey(f));
    header += `{${quotedFields.join(delimiter)}}`;
  }
  header += ":";
  return header;
}
function* encodeJsonValue(value, options, depth) {
  if (isJsonPrimitive(value)) {
    const encodedPrimitive = encodePrimitive(value, options.delimiter);
    if (encodedPrimitive !== "") yield encodedPrimitive;
    return;
  }
  if (isJsonArray(value)) yield* encodeArrayLines(void 0, value, depth, options);
  else if (isJsonObject(value)) yield* encodeObjectLines(value, depth, options);
}
function* encodeObjectLines(value, depth, options, rootLiteralKeys, pathPrefix, remainingDepth) {
  const keys = Object.keys(value);
  if (depth === 0 && !rootLiteralKeys) rootLiteralKeys = new Set(keys.filter((k) => k.includes(".")));
  const effectiveFlattenDepth = remainingDepth ?? options.flattenDepth;
  for (const [key, val] of Object.entries(value)) yield* encodeKeyValuePairLines(key, val, depth, options, keys, rootLiteralKeys, pathPrefix, effectiveFlattenDepth);
}
function* encodeKeyValuePairLines(key, value, depth, options, siblings, rootLiteralKeys, pathPrefix, flattenDepth) {
  const currentPath = pathPrefix ? `${pathPrefix}.${key}` : key;
  const effectiveFlattenDepth = flattenDepth ?? options.flattenDepth;
  if (options.keyFolding === "safe" && siblings) {
    const foldResult = tryFoldKeyChain(key, value, siblings, options, rootLiteralKeys, pathPrefix, effectiveFlattenDepth);
    if (foldResult) {
      const { foldedKey, remainder, leafValue, segmentCount } = foldResult;
      const encodedFoldedKey = encodeKey(foldedKey);
      if (remainder === void 0) {
        if (isJsonPrimitive(leafValue)) {
          yield indentedLine(depth, `${encodedFoldedKey}: ${encodePrimitive(leafValue, options.delimiter)}`, options.indent);
          return;
        } else if (isJsonArray(leafValue)) {
          yield* encodeArrayLines(foldedKey, leafValue, depth, options);
          return;
        } else if (isJsonObject(leafValue) && isEmptyObject(leafValue)) {
          yield indentedLine(depth, `${encodedFoldedKey}:`, options.indent);
          return;
        }
      }
      if (isJsonObject(remainder)) {
        yield indentedLine(depth, `${encodedFoldedKey}:`, options.indent);
        const remainingDepth = effectiveFlattenDepth - segmentCount;
        const foldedPath = pathPrefix ? `${pathPrefix}.${foldedKey}` : foldedKey;
        yield* encodeObjectLines(remainder, depth + 1, options, rootLiteralKeys, foldedPath, remainingDepth);
        return;
      }
    }
  }
  const encodedKey = encodeKey(key);
  if (isJsonPrimitive(value)) yield indentedLine(depth, `${encodedKey}: ${encodePrimitive(value, options.delimiter)}`, options.indent);
  else if (isJsonArray(value)) yield* encodeArrayLines(key, value, depth, options);
  else if (isJsonObject(value)) {
    yield indentedLine(depth, `${encodedKey}:`, options.indent);
    if (!isEmptyObject(value)) yield* encodeObjectLines(value, depth + 1, options, rootLiteralKeys, currentPath, effectiveFlattenDepth);
  }
}
function* encodeArrayLines(key, value, depth, options) {
  if (value.length === 0) {
    yield indentedLine(depth, key != null ? `${encodeKey(key)}: []` : "[]", options.indent);
    return;
  }
  if (isArrayOfPrimitives(value)) {
    yield indentedLine(depth, encodeInlineArrayLine(value, options.delimiter, key), options.indent);
    return;
  }
  if (isArrayOfArrays(value)) {
    if (value.every((arr) => isArrayOfPrimitives(arr))) {
      yield* encodeArrayOfArraysAsListItemsLines(key, value, depth, options);
      return;
    }
  }
  if (isArrayOfObjects(value)) {
    const header = extractTabularHeader(value);
    if (header) yield* encodeArrayOfObjectsAsTabularLines(key, value, header, depth, options);
    else yield* encodeMixedArrayAsListItemsLines(key, value, depth, options);
    return;
  }
  yield* encodeMixedArrayAsListItemsLines(key, value, depth, options);
}
function* encodeArrayOfArraysAsListItemsLines(prefix, values, depth, options) {
  yield indentedLine(depth, formatHeader(values.length, {
    key: prefix,
    delimiter: options.delimiter
  }), options.indent);
  for (const arr of values) if (isArrayOfPrimitives(arr)) {
    const arrayLine = encodeInlineArrayLine(arr, options.delimiter);
    yield indentedListItem(depth + 1, arrayLine, options.indent);
  }
}
function encodeInlineArrayLine(values, delimiter, prefix) {
  const header = formatHeader(values.length, {
    key: prefix,
    delimiter
  });
  const joinedValue = encodeAndJoinPrimitives(values, delimiter);
  if (values.length === 0) return header;
  return `${header} ${joinedValue}`;
}
function* encodeArrayOfObjectsAsTabularLines(prefix, rows, header, depth, options) {
  yield indentedLine(depth, formatHeader(rows.length, {
    key: prefix,
    fields: header,
    delimiter: options.delimiter
  }), options.indent);
  yield* writeTabularRowsLines(rows, header, depth + 1, options);
}
function extractTabularHeader(rows) {
  if (rows.length === 0) return;
  const firstRow = rows[0];
  const firstKeys = Object.keys(firstRow);
  if (firstKeys.length === 0) return;
  if (isTabularArray(rows, firstKeys)) return firstKeys;
}
function isTabularArray(rows, header) {
  for (const row of rows) {
    if (Object.keys(row).length !== header.length) return false;
    for (const key of header) {
      if (!(key in row)) return false;
      if (!isJsonPrimitive(row[key])) return false;
    }
  }
  return true;
}
function* writeTabularRowsLines(rows, header, depth, options) {
  for (const row of rows) yield indentedLine(depth, encodeAndJoinPrimitives(header.map((key) => row[key]), options.delimiter), options.indent);
}
function* encodeMixedArrayAsListItemsLines(prefix, items, depth, options) {
  yield indentedLine(depth, formatHeader(items.length, {
    key: prefix,
    delimiter: options.delimiter
  }), options.indent);
  for (const item of items) yield* encodeListItemValueLines(item, depth + 1, options);
}
function* encodeObjectAsListItemLines(obj, depth, options) {
  if (isEmptyObject(obj)) {
    yield indentedLine(depth, "-", options.indent);
    return;
  }
  const entries = Object.entries(obj);
  const [firstKey, firstValue] = entries[0];
  const restEntries = entries.slice(1);
  if (isJsonArray(firstValue) && isArrayOfObjects(firstValue)) {
    const header = extractTabularHeader(firstValue);
    if (header) {
      yield indentedListItem(depth, formatHeader(firstValue.length, {
        key: firstKey,
        fields: header,
        delimiter: options.delimiter
      }), options.indent);
      yield* writeTabularRowsLines(firstValue, header, depth + 2, options);
      if (restEntries.length > 0) yield* encodeObjectLines(Object.fromEntries(restEntries), depth + 1, options);
      return;
    }
  }
  const encodedKey = encodeKey(firstKey);
  if (isJsonPrimitive(firstValue)) yield indentedListItem(depth, `${encodedKey}: ${encodePrimitive(firstValue, options.delimiter)}`, options.indent);
  else if (isJsonArray(firstValue)) if (firstValue.length === 0) yield indentedListItem(depth, `${encodedKey}: []`, options.indent);
  else if (isArrayOfPrimitives(firstValue)) yield indentedListItem(depth, `${encodedKey}${encodeInlineArrayLine(firstValue, options.delimiter)}`, options.indent);
  else {
    yield indentedListItem(depth, `${encodedKey}${formatHeader(firstValue.length, { delimiter: options.delimiter })}`, options.indent);
    for (const item of firstValue) yield* encodeListItemValueLines(item, depth + 2, options);
  }
  else if (isJsonObject(firstValue)) {
    yield indentedListItem(depth, `${encodedKey}:`, options.indent);
    if (!isEmptyObject(firstValue)) yield* encodeObjectLines(firstValue, depth + 2, options);
  }
  if (restEntries.length > 0) yield* encodeObjectLines(Object.fromEntries(restEntries), depth + 1, options);
}
function* encodeListItemValueLines(value, depth, options) {
  if (isJsonPrimitive(value)) yield indentedListItem(depth, encodePrimitive(value, options.delimiter), options.indent);
  else if (isJsonArray(value)) if (isArrayOfPrimitives(value)) yield indentedListItem(depth, encodeInlineArrayLine(value, options.delimiter), options.indent);
  else {
    yield indentedListItem(depth, formatHeader(value.length, { delimiter: options.delimiter }), options.indent);
    for (const item of value) yield* encodeListItemValueLines(item, depth + 1, options);
  }
  else if (isJsonObject(value)) yield* encodeObjectAsListItemLines(value, depth, options);
}
function indentedLine(depth, content, indentSize) {
  return " ".repeat(indentSize * depth) + content;
}
function indentedListItem(depth, content, indentSize) {
  return indentedLine(depth, "- " + content, indentSize);
}
function applyReplacer(root, replacer) {
  const replacedRoot = replacer("", root, []);
  if (replacedRoot === void 0) return transformChildren(root, replacer, []);
  return transformChildren(normalizeValue(replacedRoot), replacer, []);
}
function transformChildren(value, replacer, path) {
  if (isJsonObject(value)) return transformObject(value, replacer, path);
  if (isJsonArray(value)) return transformArray(value, replacer, path);
  return value;
}
function transformObject(obj, replacer, path) {
  const result = {};
  for (const [key, value] of Object.entries(obj)) {
    const childPath = [...path, key];
    const replacedValue = replacer(key, value, childPath);
    if (replacedValue === void 0) continue;
    result[key] = transformChildren(normalizeValue(replacedValue), replacer, childPath);
  }
  return result;
}
function transformArray(arr, replacer, path) {
  const result = [];
  for (let i = 0; i < arr.length; i++) {
    const value = arr[i];
    const childPath = [...path, i];
    const replacedValue = replacer(String(i), value, childPath);
    if (replacedValue === void 0) continue;
    const normalizedValue = normalizeValue(replacedValue);
    result.push(transformChildren(normalizedValue, replacer, childPath));
  }
  return result;
}
function encode(input, options) {
  return Array.from(encodeLines(input, options)).join("\n");
}
function encodeLines(input, options) {
  const normalizedValue = normalizeValue(input);
  const resolvedOptions = resolveOptions(options);
  return encodeJsonValue(resolvedOptions.replacer ? applyReplacer(normalizedValue, resolvedOptions.replacer) : normalizedValue, resolvedOptions, 0);
}
function resolveOptions(options) {
  return {
    indent: options?.indent ?? 2,
    delimiter: options?.delimiter ?? DEFAULT_DELIMITER,
    keyFolding: options?.keyFolding ?? "off",
    flattenDepth: options?.flattenDepth ?? Number.POSITIVE_INFINITY,
    replacer: options?.replacer
  };
}

// node_modules/.bun/axi-sdk-js@0.1.7/node_modules/axi-sdk-js/dist/output.js
function collapseHomeDirectory(path, homeDir = homedir()) {
  if (!path.startsWith(homeDir)) {
    return path;
  }
  return `~${path.slice(homeDir.length)}`;
}
function homeHeaderOutput(options) {
  return {
    bin: collapseHomeDirectory(options.execPath ?? process.argv[1] ?? "", options.homeDir),
    description: options.description
  };
}
function errorOutput(message, code, suggestions = []) {
  const output = {
    error: message,
    code
  };
  if (suggestions.length > 0) {
    output.help = suggestions;
  }
  return output;
}
function renderOutput(output) {
  if (typeof output === "string") {
    return output;
  }
  return encode(output);
}
function renderError(message, code, suggestions = []) {
  return renderOutput(errorOutput(message, code, suggestions));
}

// node_modules/.bun/axi-sdk-js@0.1.7/node_modules/axi-sdk-js/dist/cli.js
function defaultFormatError(error) {
  if (error instanceof AxiError) {
    return {
      output: `${renderError(error.message, error.code, error.suggestions)}
`,
      exitCode: exitCodeForError(error)
    };
  }
  const message = error instanceof Error ? error.message : String(error);
  return {
    output: `${renderError(message, "UNKNOWN")}
`,
    exitCode: 1
  };
}
function defaultUnknownCommand(command) {
  return `${renderError(`Unknown command: ${command}`, "VALIDATION_ERROR", [
    "Run `--help` to see available commands"
  ])}
`;
}
async function runAxiCli(options) {
  options.initialize?.();
  const stdout = options.stdout ?? process.stdout;
  const argv = options.argv ?? process.argv.slice(2);
  if (argv.length === 1 && argv[0] === "--help") {
    stdout.write(options.topLevelHelp);
    return;
  }
  if (argv.length === 1 && isVersionFlag(argv[0])) {
    if (!options.version) {
      stdout.write(`${renderError("Version is not configured for this tool", "VALIDATION_ERROR")}
`);
      process.exitCode = 2;
      return;
    }
    stdout.write(`${options.version}
`);
    return;
  }
  const command = argv[0];
  if (!command) {
    const context2 = await options.resolveContext?.({
      command: void 0,
      args: []
    });
    await runHandler(options.home, [], context2, stdout, options, true);
    return;
  }
  if (command.startsWith("-")) {
    stdout.write(renderLeadingFlagError(command));
    process.exitCode = 2;
    return;
  }
  const args = argv.slice(1);
  if (args.includes("--help")) {
    const help = options.getCommandHelp?.(command);
    if (help) {
      stdout.write(help);
      return;
    }
  }
  const handler = options.commands[command];
  if (!handler) {
    stdout.write((options.renderUnknownCommand ?? defaultUnknownCommand)(command));
    process.exitCode = 2;
    return;
  }
  const context = await options.resolveContext?.({ command, args });
  await runHandler(handler, args, context, stdout, options, false);
}
async function runHandler(handler, args, context, stdout, options, isHomeView) {
  try {
    const output = await handler(args, context);
    stdout.write(`${renderCommandOutput(output, options, isHomeView)}
`);
  } catch (error) {
    const formatted = (options.formatError ?? defaultFormatError)(error);
    stdout.write(formatted.output);
    process.exitCode = formatted.exitCode;
  }
}
function renderLeadingFlagError(flag) {
  const bin = basename(process.argv[1] ?? "tool") || "tool";
  return `${renderError("Flags must come after the command", "VALIDATION_ERROR", [
    `Run \`${bin} <command> [args] [flags]\``,
    `Move \`${flag}\` after the command instead of before it`
  ])}
`;
}
function isVersionFlag(flag) {
  return flag === "-v" || flag === "-V" || flag === "--version";
}
function renderCommandOutput(output, options, isHomeView) {
  if (!isHomeView) {
    return renderOutput(output);
  }
  const header = homeHeaderOutput({ description: options.description });
  if (typeof output === "string") {
    return `${renderOutput(header)}
${output}`;
  }
  return renderOutput(mergeHomeHeader(header, output));
}
function mergeHomeHeader(header, output) {
  const rest = { ...output };
  delete rest.bin;
  delete rest.description;
  return {
    ...header,
    ...rest
  };
}

// packages/google/src/axi/google/reference.ts
var DESCRIPTION = "Set up and manage Google accounts (OAuth) for Gmail sync and triage \u2014 create/list accounts, complete authorization, edit settings, and manage name aliases.";
var COMMAND_GROUPS = [
  {
    group: "Accounts",
    commands: [
      { usage: "accounts", summary: "list all Google accounts with credential + sync/triage status" },
      { usage: "account get <id>", summary: "full account detail including settings" },
      {
        usage: "account create --identifier ID --email EMAIL [--name NAME]",
        summary: "create an account and return an OAuth authUrl for the user to authorize"
      },
      {
        usage: "account update <id> [--name TEXT] [--primary] [--triage-instructions TEXT] [--label-prefix TEXT] [--label-prefix-todo TEXT] [--sync-start-date DATE]",
        summary: "update display name / primary flag / triage + label settings"
      },
      { usage: "account reauth <id>", summary: "mint a fresh OAuth authUrl for an existing account" },
      { usage: "account delete <id>", summary: "revoke tokens and delete the account (cascades to its emails/aliases)" }
    ]
  },
  {
    group: "Aliases",
    commands: [
      { usage: "aliases <account-id>", summary: "list name aliases used for commitment/sender disambiguation" },
      {
        usage: "aliases add <account-id> --alias NAME [--not-owner] [--refers-to NAME] [--notes TEXT]",
        summary: "add a name alias (default marks it as referring to the account owner)"
      },
      { usage: "aliases remove <account-id> <alias-id>", summary: "delete a name alias" }
    ]
  }
];
function commandReferenceText() {
  return COMMAND_GROUPS.map((g) => {
    const items = g.commands.map((c) => `  ${c.usage}
      ${c.summary}`).join("\n");
    return `${g.group}:
${items}`;
  }).join("\n\n");
}
function discoveryHelp(invocation) {
  return `Run \`${invocation} --help\` for the full command list, or \`${invocation} <command> --help\` for usage on any command`;
}

// packages/google/src/axi/invocation.ts
import { accessSync, constants } from "node:fs";
import { homedir as homedir2 } from "node:os";
import { fileURLToPath } from "node:url";
var cached;
function cliInvocation() {
  if (cached) return cached;
  let bundle;
  try {
    bundle = fileURLToPath(import.meta.url);
  } catch {
    bundle = process.argv[1] ?? "google-axi";
  }
  const shim = bundle.replace(/\.mjs$/, "");
  try {
    if (shim !== bundle) {
      accessSync(shim, constants.X_OK);
      cached = quote(collapseHome(shim));
      return cached;
    }
  } catch {
  }
  cached = `node ${quote(collapseHome(bundle))}`;
  return cached;
}
function collapseHome(p) {
  const home = homedir2();
  return home && p.startsWith(`${home}/`) ? `~${p.slice(home.length)}` : p;
}
function quote(p) {
  return /\s/.test(p) ? `"${p}"` : p;
}

// packages/google/src/axi/client.ts
var DEFAULT_SERVER = "http://localhost:2529";
function resolveServer() {
  const env = process.env.CLAUDE_ASSIST_SERVER?.trim();
  return (env || DEFAULT_SERVER).replace(/\/+$/, "");
}
function buildUrl(server, path, query) {
  let url = `${server}${path}`;
  if (query) {
    const qs = new URLSearchParams();
    for (const [k, v] of Object.entries(query)) {
      if (v === void 0 || v === null || v === "") continue;
      if (Array.isArray(v)) {
        for (const item of v) if (item !== void 0 && item !== null && item !== "") qs.append(k, String(item));
      } else {
        qs.append(k, String(v));
      }
    }
    const s = qs.toString();
    if (s) url += `?${s}`;
  }
  return url;
}
function suggestForStatus(status) {
  if (status === 404) return ["Check the id \u2014 try `search` to look one up"];
  if (status === 400) return ["Check required params and value formats for this command"];
  if (status === 503) return ["The server is up but this feature may be disabled (e.g. ANTHROPIC_API_KEY not set)"];
  return [];
}
async function send(method, path, opts = {}) {
  const server = resolveServer();
  const url = buildUrl(server, path, opts.query);
  const hasBody = opts.body !== void 0 && opts.body !== null;
  const init = { method, headers: hasBody ? { "Content-Type": "application/json" } : {} };
  if (hasBody) init.body = JSON.stringify(opts.body);
  let res;
  try {
    res = await fetch(url, init);
  } catch (err) {
    throw new AxiError(
      `Cannot reach claude-assist server at ${server} (${err.message})`,
      "HTTP_ERROR",
      ["Set CLAUDE_ASSIST_SERVER or start the server (cd apps/server && docker-compose up -d)"]
    );
  }
  return res;
}
async function parseError(res) {
  const text = await res.text();
  let message = res.statusText || `HTTP ${res.status}`;
  if (text) {
    try {
      const data = JSON.parse(text);
      if (data && typeof data === "object" && data.error) message = data.error;
      else if (data && typeof data === "object" && data.message) message = data.message;
    } catch {
      message = text.slice(0, 200);
    }
  }
  throw new AxiError(`API error (${res.status}): ${message}`, "HTTP_ERROR", suggestForStatus(res.status));
}
var api = {
  async get(path, query) {
    const res = await send("GET", path, { query });
    if (!res.ok) await parseError(res);
    const text = await res.text();
    if (!text) return null;
    try {
      return JSON.parse(text);
    } catch {
      return text;
    }
  },
  /** GET an endpoint that returns text/plain (e.g. transcripts). */
  async getText(path, query) {
    const res = await send("GET", path, { query });
    if (!res.ok) await parseError(res);
    return res.text();
  },
  async post(path, body, query) {
    return mutate("POST", path, body, query);
  },
  async patch(path, body) {
    return mutate("PATCH", path, body);
  },
  async del(path) {
    return mutate("DELETE", path);
  }
};
async function mutate(method, path, body, query) {
  const res = await send(method, path, { body, query });
  if (!res.ok) await parseError(res);
  const text = await res.text();
  if (!text) return null;
  try {
    return JSON.parse(text);
  } catch {
    return text;
  }
}

// packages/google/src/axi/args.ts
function parseArgs(args, booleanFlags = []) {
  const positionals = [];
  const flags = {};
  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg.startsWith("--")) {
      const name = arg.slice(2);
      if (booleanFlags.includes(name)) {
        flags[name] = true;
      } else {
        const value = args[++i];
        if (value === void 0) {
          throw new AxiError(`Flag --${name} requires a value`, "VALIDATION_ERROR");
        }
        flags[name] = value;
      }
    } else {
      positionals.push(arg);
    }
  }
  return { positionals, flags };
}
function requireFlag(flags, name, usage) {
  const v = flags[name];
  if (typeof v !== "string" || v === "") {
    throw new AxiError(`--${name} is required`, "VALIDATION_ERROR", [usage]);
  }
  return v;
}
function requirePositional(positionals, index, label, usage) {
  const v = positionals[index];
  if (!v) throw new AxiError(`${label} is required`, "VALIDATION_ERROR", [usage]);
  return v;
}
var DATE_ONLY = /^\d{4}-\d{2}-\d{2}$/;
var ISO_DATETIME = /^\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}(:\d{2}(\.\d+)?)?(Z|[+-]\d{2}:?\d{2})?$/;
function validateDate(value, flag, usage) {
  const wellFormed = DATE_ONLY.test(value) || ISO_DATETIME.test(value);
  if (!wellFormed || Number.isNaN(Date.parse(value))) {
    throw new AxiError(`Invalid date for ${flag}: ${value}`, "VALIDATION_ERROR", [
      "Use YYYY-MM-DD (e.g. 2026-04-29) or a full ISO 8601 timestamp (e.g. 2026-04-29T14:30:00Z)",
      usage
    ]);
  }
  return value;
}
function rawJson(data) {
  return JSON.stringify(data, null, 2);
}

// packages/google/src/axi/toon.ts
function field(key, as) {
  return { type: "field", key, as };
}
function custom(as, fn) {
  return { type: "custom", as, fn };
}
function outputKey(def) {
  if (def.type === "custom") return def.as;
  return def.as ?? def.key;
}
function extract(item, schema) {
  const result = {};
  for (const def of schema) {
    const key = outputKey(def);
    switch (def.type) {
      case "field":
        result[key] = item[def.key] ?? null;
        break;
      case "pluck":
        result[key] = item[def.key]?.[def.subkey] ?? null;
        break;
      case "joinArray": {
        const arr = item[def.key];
        if (Array.isArray(arr) && arr.length > 0) {
          result[key] = arr.map(
            (x) => def.subkey && x && typeof x === "object" ? x[def.subkey] : x
          ).join(",");
        } else {
          result[key] = def.empty ?? "none";
        }
        break;
      }
      case "count": {
        const arr = item[def.key];
        result[key] = Array.isArray(arr) ? arr.length : 0;
        break;
      }
      case "relativeTime":
        result[key] = formatRelativeTime(item[def.key]);
        break;
      case "dateOnly":
        result[key] = formatDateOnly(item[def.key]);
        break;
      case "boolYesNo":
        result[key] = item[def.key] ? "yes" : "no";
        break;
      case "truncate":
        result[key] = truncateText(item[def.key], def.limit).value;
        break;
      case "custom":
        result[key] = def.fn(item);
        break;
    }
  }
  return result;
}
function renderList(label, items, schema) {
  return encode({ [label]: items.map((item) => extract(item, schema)) });
}
function renderDetail(label, item, schema) {
  return encode({ [label]: extract(item, schema) });
}
function renderObject(obj) {
  return encode(obj);
}
function renderHelp(lines) {
  const clean = lines.filter(Boolean);
  if (clean.length === 0) return "";
  return `help[${clean.length}]:
${clean.map((l) => `  ${l}`).join("\n")}`;
}
function renderOutput2(blocks) {
  return blocks.filter(Boolean).join("\n");
}
var DEFAULT_TRUNCATE = 280;
function truncateText(text, limit = DEFAULT_TRUNCATE) {
  if (typeof text !== "string") return { value: text ?? null, truncated: false, total: 0 };
  if (text.length <= limit) return { value: text, truncated: false, total: text.length };
  return {
    value: `${text.slice(0, limit)}\u2026 (truncated, ${text.length} chars total)`,
    truncated: true,
    total: text.length
  };
}
function formatDateOnly(value) {
  if (!value) return null;
  const d = new Date(value);
  if (isNaN(d.getTime())) return String(value);
  return d.toISOString().slice(0, 10);
}
function formatRelativeTime(value) {
  if (!value) return "unknown";
  const then = new Date(value).getTime();
  if (isNaN(then)) return "unknown";
  const diffSec = Math.floor((Date.now() - then) / 1e3);
  const past = diffSec >= 0;
  const s = Math.abs(diffSec);
  const fmt = (n, unit) => past ? `${n}${unit} ago` : `in ${n}${unit}`;
  if (s < 60) return past ? "just now" : "soon";
  const min = Math.floor(s / 60);
  if (min < 60) return fmt(min, "m");
  const hr = Math.floor(min / 60);
  if (hr < 24) return fmt(hr, "h");
  const day = Math.floor(hr / 24);
  if (day < 30) return fmt(day, "d");
  const mon = Math.floor(day / 30);
  if (mon < 12) return fmt(mon, "mo");
  return fmt(Math.floor(mon / 12), "y");
}

// packages/google/src/axi/google/commands/home.ts
var SCHEMA = [
  field("id"),
  field("identifier"),
  field("email"),
  { type: "boolYesNo", key: "has_credentials", as: "authed" },
  { type: "boolYesNo", key: "is_primary", as: "primary" },
  custom("last_sync", (a) => a.email_last_sync_at ?? "never")
];
async function homeCommand(args) {
  const { flags } = parseArgs(args, ["json"]);
  const server = resolveServer();
  const cli = cliInvocation();
  let accounts = null;
  try {
    const res = await api.get("/api/google/accounts");
    accounts = Array.isArray(res) ? res : [];
  } catch {
    accounts = null;
  }
  if (flags.json) return rawJson({ server, accounts });
  const blocks = [];
  if (accounts === null) {
    blocks.push(renderObject({ server, status: "unreachable" }));
    blocks.push("The server is not reachable. Set CLAUDE_ASSIST_SERVER or start it (cd apps/server && docker-compose up -d).");
  } else if (accounts.length === 0) {
    blocks.push(renderObject({ server, accounts: 0 }));
    blocks.push(`No Google accounts configured yet.`);
  } else {
    const needAuth = accounts.filter((a) => !a.has_credentials).length;
    blocks.push(`accounts: ${accounts.length}${needAuth ? `, ${needAuth} need authorization` : ", all authorized"}`);
    blocks.push(renderList("accounts", accounts, SCHEMA));
  }
  blocks.push(
    renderHelp([
      `Run \`${cli} account create --identifier <id> --email <addr>\` to connect a Gmail account`,
      `Run \`${cli} account reauth <id>\` if an account needs re-authorization`,
      `Run \`${cli} aliases <account-id>\` to manage name aliases; use \`gmail-axi\` for the inbox itself`,
      discoveryHelp(cli)
    ])
  );
  return renderOutput2(blocks);
}

// packages/google/src/axi/google/commands/accounts.ts
var ACCOUNTS_HELP = `google-axi accounts [--json]

  List all Google accounts with credential, sync, and triage status.`;
var LIST_SCHEMA = [
  field("id"),
  field("identifier"),
  field("email"),
  field("display_name", "name"),
  { type: "boolYesNo", key: "is_primary", as: "primary" },
  { type: "boolYesNo", key: "has_credentials", as: "authed" },
  field("email_last_sync_at", "last_sync"),
  custom("syncing", (a) => a.email_sync_status?.syncing ? "yes" : "no")
];
async function accountsCommand(args) {
  const { flags } = parseArgs(args, ["json"]);
  const rows = await api.get("/api/google/accounts");
  if (flags.json) return rawJson(rows);
  if (!Array.isArray(rows) || rows.length === 0) {
    const cli = cliInvocation();
    return renderOutput2([
      "accounts: none configured",
      renderHelp([`Run \`${cli} account create --identifier <id> --email <addr>\` to add one`])
    ]);
  }
  const needAuth = rows.filter((a) => !a.has_credentials).length;
  return renderOutput2([
    `count: ${rows.length}${needAuth ? `, ${needAuth} need authorization` : ""}`,
    renderList("accounts", rows, LIST_SCHEMA)
  ]);
}
var DETAIL_SCHEMA = [
  field("id"),
  field("identifier"),
  field("email"),
  field("display_name", "name"),
  { type: "boolYesNo", key: "is_primary", as: "primary" },
  { type: "boolYesNo", key: "has_credentials", as: "authed" },
  field("email_last_sync_at", "last_sync"),
  field("email_sync_start_date", "sync_start"),
  field("email_label_prefix", "label_prefix"),
  field("email_label_prefix_todo", "label_prefix_todo"),
  field("email_triage_instructions", "triage_instructions")
];
async function accountCommand(args) {
  const verb = args[0];
  const rest = args.slice(1);
  switch (verb) {
    case "get":
      return getAccount(rest);
    case "create":
      return createAccount(rest);
    case "update":
      return updateAccount(rest);
    case "reauth":
      return reauthAccount(rest);
    case "delete":
      return deleteAccount(rest);
    default:
      throw new AxiError(`Unknown account subcommand: ${verb ?? "(none)"}`, "VALIDATION_ERROR", [
        "Use: account get|create|update|reauth|delete"
      ]);
  }
}
async function getAccount(args) {
  const { positionals, flags } = parseArgs(args, ["json"]);
  const id = requirePositional(positionals, 0, "account id", "google-axi account get <id>");
  const account = await api.get(`/api/google/accounts/${encodeURIComponent(id)}`);
  if (flags.json) return rawJson(account);
  return renderDetail("account", account, DETAIL_SCHEMA);
}
async function createAccount(args) {
  const { flags } = parseArgs(args, ["json"]);
  const usage = "google-axi account create --identifier ID --email EMAIL [--name NAME]";
  const identifier = requireFlag(flags, "identifier", usage);
  const email = requireFlag(flags, "email", usage);
  const body = { identifier, email };
  if (typeof flags.name === "string") body.display_name = flags.name;
  const result = await api.post("/api/google/accounts", body);
  if (flags.json) return rawJson(result);
  return renderOutput2([
    renderObject({ created: "account", id: result.id, identifier: result.identifier, email: result.email }),
    `Open this URL in a browser to authorize, then the account is ready to sync:`,
    String(result.authUrl ?? "")
  ]);
}
async function updateAccount(args) {
  const { positionals, flags } = parseArgs(args, ["json", "primary"]);
  const usage = "google-axi account update <id> [--name ...] [--primary] [--triage-instructions ...] ...";
  const id = requirePositional(positionals, 0, "account id", usage);
  const body = {};
  if (typeof flags.name === "string") body.display_name = flags.name;
  if (flags.primary) body.is_primary = true;
  if (typeof flags["triage-instructions"] === "string") body.email_triage_instructions = flags["triage-instructions"];
  if (typeof flags["label-prefix"] === "string") body.email_label_prefix = flags["label-prefix"];
  if (typeof flags["label-prefix-todo"] === "string") body.email_label_prefix_todo = flags["label-prefix-todo"];
  if (typeof flags["sync-start-date"] === "string")
    body.email_sync_start_date = validateDate(flags["sync-start-date"], "--sync-start-date", usage);
  if (Object.keys(body).length === 0) {
    throw new AxiError("Nothing to update \u2014 pass at least one field", "VALIDATION_ERROR", [usage]);
  }
  const result = await api.patch(`/api/google/accounts/${encodeURIComponent(id)}`, body);
  if (flags.json) return rawJson(result);
  return renderObject({ updated: result.id, identifier: result.identifier });
}
async function reauthAccount(args) {
  const { positionals, flags } = parseArgs(args, ["json"]);
  const id = requirePositional(positionals, 0, "account id", "google-axi account reauth <id>");
  const result = await api.post(`/api/google/accounts/${encodeURIComponent(id)}/reauth`);
  if (flags.json) return rawJson(result);
  return renderOutput2([`Open this URL in a browser to re-authorize account ${id}:`, String(result.authUrl ?? "")]);
}
async function deleteAccount(args) {
  const { positionals, flags } = parseArgs(args, ["json"]);
  const id = requirePositional(positionals, 0, "account id", "google-axi account delete <id>");
  const result = await api.del(`/api/google/accounts/${encodeURIComponent(id)}`);
  if (flags.json) return rawJson(result);
  return renderObject({ deleted: id, success: result?.success ?? true });
}

// packages/google/src/axi/google/commands/aliases.ts
var ALIASES_HELP = `google-axi aliases <account-id>                                  # list
google-axi aliases add <account-id> --alias NAME [--not-owner] [--refers-to NAME] [--notes TEXT]
google-axi aliases remove <account-id> <alias-id>

  Name aliases help disambiguate who an email is from/to and who commitments
  refer to. By default a new alias is marked as referring to the account owner;
  pass --not-owner (with --refers-to) for someone else.`;
var SCHEMA2 = [
  field("id"),
  field("alias"),
  { type: "boolYesNo", key: "is_owner", as: "owner" },
  field("refers_to"),
  field("notes")
];
async function aliasesCommand(args) {
  const verb = args[0];
  if (verb === "add") return addAlias(args.slice(1));
  if (verb === "remove") return removeAlias(args.slice(1));
  return listAliases(args);
}
async function listAliases(args) {
  const { positionals, flags } = parseArgs(args, ["json"]);
  const accountId = requirePositional(positionals, 0, "account id", "google-axi aliases <account-id>");
  const rows = await api.get(`/api/google/accounts/${encodeURIComponent(accountId)}/aliases`);
  if (flags.json) return rawJson(rows);
  if (!Array.isArray(rows) || rows.length === 0) {
    const cli = cliInvocation();
    return renderOutput2([
      "aliases: none",
      renderHelp([`Run \`${cli} aliases add ${accountId} --alias "<name>"\` to add one`])
    ]);
  }
  return renderOutput2([`count: ${rows.length}`, renderList("aliases", rows, SCHEMA2)]);
}
async function addAlias(args) {
  const { positionals, flags } = parseArgs(args, ["json", "not-owner"]);
  const usage = "google-axi aliases add <account-id> --alias NAME [--not-owner] [--refers-to NAME] [--notes TEXT]";
  const accountId = requirePositional(positionals, 0, "account id", usage);
  const alias = requireFlag(flags, "alias", usage);
  const body = { alias, is_owner: !flags["not-owner"] };
  if (typeof flags["refers-to"] === "string") body.refers_to = flags["refers-to"];
  if (typeof flags.notes === "string") body.notes = flags.notes;
  if (flags["not-owner"] && !body.refers_to) {
    throw new AxiError("--not-owner requires --refers-to <name>", "VALIDATION_ERROR", [usage]);
  }
  const created = await api.post(`/api/google/accounts/${encodeURIComponent(accountId)}/aliases`, body);
  if (flags.json) return rawJson(created);
  return renderObject({ created: "alias", id: created.id, alias: created.alias, refers_to: created.refers_to });
}
async function removeAlias(args) {
  const { positionals, flags } = parseArgs(args, ["json"]);
  const usage = "google-axi aliases remove <account-id> <alias-id>";
  const accountId = requirePositional(positionals, 0, "account id", usage);
  const aliasId = requirePositional(positionals, 1, "alias id", usage);
  const result = await api.del(
    `/api/google/accounts/${encodeURIComponent(accountId)}/aliases/${encodeURIComponent(aliasId)}`
  );
  if (flags.json) return rawJson(result);
  return renderObject({ removed: aliasId, success: result?.success ?? true });
}

// packages/google/src/axi/google/cli.ts
var VERSION = true ? "d42cebd" : "dev";
var CLI = cliInvocation();
var TOP_HELP = `usage: ${CLI} [command] [args] [flags]
       ${CLI}                 # no args \u2192 home (accounts + auth status)

commands:

${commandReferenceText()}

flags: --help, -v/--version, --json (raw output)

env: CLAUDE_ASSIST_SERVER (default http://localhost:2529)

examples:
  ${CLI}
  ${CLI} account create --identifier chris --email chris@example.com
  ${CLI} account reauth 1
  ${CLI} aliases add 1 --alias "Chris A"
`;
var COMMAND_HELP = {
  accounts: ACCOUNTS_HELP,
  account: `google-axi account get|create|update|reauth|delete <id> [...]

  Manage a single Google account. See \`--help\` for the field flags on each verb.`,
  aliases: ALIASES_HELP
};
var COMMANDS = {
  accounts: accountsCommand,
  account: accountCommand,
  aliases: aliasesCommand
};
async function main(argv) {
  await runAxiCli({
    description: DESCRIPTION,
    version: VERSION,
    ...argv ? { argv } : {},
    topLevelHelp: TOP_HELP,
    home: homeCommand,
    commands: COMMANDS,
    getCommandHelp: (command) => COMMAND_HELP[command]
  });
}

// packages/google/src/axi/bin-google.ts
await main();
