/**
 * Build the self-contained `*-axi.mjs` bundles committed under each skill's
 * scripts/ directory. All dependencies (axi-sdk-js, @toon-format/toon) are
 * inlined so the artifact runs under plain `node` ≥ 20 on a machine that only
 * has the skill installed — no npm install, no node_modules.
 *
 *   bun scripts/build-cli.ts            # write every bundle
 *   bun scripts/build-cli.ts --check    # fail if any committed bundle is stale
 *
 * The CLI version is injected from `git describe`. Because committing the
 * bundle changes the git sha (and CI checkouts may lack tags), --check
 * normalizes the embedded version literal out before comparing, so version
 * drift never fails the check while any real src/axi/ change still does.
 */
import * as esbuild from "esbuild";
import { readFileSync, chmodSync } from "node:fs";
import { execSync } from "node:child_process";

interface Target {
  entry: string;
  outfile: string;
}

const TARGETS: Target[] = [
  { entry: "packages/sessions/src/axi/bin.ts", outfile: "skills/assist-sessions/scripts/sessions-axi.mjs" },
  { entry: "packages/google/src/axi/bin-gmail.ts", outfile: "skills/assist-gmail/scripts/gmail-axi.mjs" },
  { entry: "packages/google/src/axi/bin-google.ts", outfile: "skills/assist-google-setup/scripts/google-axi.mjs" },
  { entry: "packages/kitchen/src/axi/bin.ts", outfile: "skills/assist-kitchen/scripts/kitchen-axi.mjs" },
  { entry: "packages/pages/src/axi/bin.ts", outfile: "skills/assist-pages/scripts/pages-axi.mjs" },
];

const check = process.argv.includes("--check");

function gitVersion(): string {
  try {
    return execSync("git describe --tags --always", { encoding: "utf8" }).trim() || "dev";
  } catch {
    return "dev";
  }
}

/** Replace the embedded version literal so --check ignores version drift. */
function normalizeVersion(source: string): string {
  return source.replace(/"[^"]*" : "dev"/, '"__VERSION__" : "dev"');
}

const VERSION = gitVersion();
let stale = false;

for (const { entry, outfile } of TARGETS) {
  const result = await esbuild.build({
    entryPoints: [entry],
    outfile,
    bundle: true,
    platform: "node",
    format: "esm",
    target: "node20",
    legalComments: "none",
    define: { __AXI_VERSION__: JSON.stringify(VERSION) },
    banner: {
      js: "#!/usr/bin/env node\n// GENERATED by scripts/build-cli.ts from src/axi/ — do not edit. Run `bun run build:cli`.",
    },
    write: !check,
  });

  if (check) {
    const generated = result.outputFiles![0]!.text;
    const committed = readFileSync(outfile, "utf8");
    if (normalizeVersion(generated) !== normalizeVersion(committed)) {
      console.error(`${outfile} is out of date — run \`bun run build:cli\` and commit the result`);
      stale = true;
    } else {
      console.log(`${outfile} is up to date`);
    }
  } else {
    chmodSync(outfile, 0o755);
    console.log(`Wrote ${outfile}`);
  }
}

if (stale) process.exit(1);
