#!/usr/bin/env node
// GENERATED by scripts/build-cli.ts from src/axi/ — do not edit. Run `bun run build:cli`.

// node_modules/.bun/axi-sdk-js@0.1.7/node_modules/axi-sdk-js/dist/cli.js
import { basename } from "node:path";

// node_modules/.bun/axi-sdk-js@0.1.7/node_modules/axi-sdk-js/dist/errors.js
var AxiError = class extends Error {
  code;
  suggestions;
  constructor(message, code, suggestions = []) {
    super(message);
    this.code = code;
    this.suggestions = suggestions;
    this.name = "AxiError";
  }
};
function exitCodeForError(error) {
  if (error instanceof AxiError && error.code === "VALIDATION_ERROR") {
    return 2;
  }
  return 1;
}

// node_modules/.bun/axi-sdk-js@0.1.7/node_modules/axi-sdk-js/dist/output.js
import { homedir } from "node:os";

// node_modules/.bun/@toon-format+toon@2.3.0/node_modules/@toon-format/toon/dist/index.mjs
var NULL_LITERAL = "null";
var DELIMITERS = {
  comma: ",",
  tab: "	",
  pipe: "|"
};
var DEFAULT_DELIMITER = DELIMITERS.comma;
function escapeString(value) {
  return value.replace(/\\/g, `\\\\`).replace(/"/g, `\\"`).replace(/\n/g, `\\n`).replace(/\r/g, `\\r`).replace(/\t/g, `\\t`).replace(/[\u0000-\u001F]/g, (c) => `\\u${c.charCodeAt(0).toString(16).padStart(4, "0")}`);
}
function isBooleanOrNullLiteral(token) {
  return token === "true" || token === "false" || token === "null";
}
function normalizeValue(value) {
  if (value === null) return null;
  if (typeof value === "object" && value !== null && "toJSON" in value && typeof value.toJSON === "function") {
    const next = value.toJSON();
    if (next !== value) return normalizeValue(next);
  }
  if (typeof value === "string" || typeof value === "boolean") return value;
  if (typeof value === "number") {
    if (Object.is(value, -0)) return 0;
    if (!Number.isFinite(value)) return null;
    return value;
  }
  if (typeof value === "bigint") {
    if (value >= Number.MIN_SAFE_INTEGER && value <= Number.MAX_SAFE_INTEGER) return Number(value);
    return value.toString();
  }
  if (value instanceof Date) return value.toISOString();
  if (Array.isArray(value)) return value.map(normalizeValue);
  if (value instanceof Set) return Array.from(value).map(normalizeValue);
  if (value instanceof Map) return Object.fromEntries(Array.from(value, ([k, v]) => [String(k), normalizeValue(v)]));
  if (isPlainObject(value)) {
    const encodedValues = {};
    for (const key in value) if (Object.hasOwn(value, key)) encodedValues[key] = normalizeValue(value[key]);
    return encodedValues;
  }
  return null;
}
function isJsonPrimitive(value) {
  return value === null || typeof value === "string" || typeof value === "number" || typeof value === "boolean";
}
function isJsonArray(value) {
  return Array.isArray(value);
}
function isJsonObject(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}
function isEmptyObject(value) {
  return Object.keys(value).length === 0;
}
function isPlainObject(value) {
  if (value === null || typeof value !== "object") return false;
  const prototype = Object.getPrototypeOf(value);
  return prototype === null || prototype === Object.prototype;
}
function isArrayOfPrimitives(value) {
  return value.length === 0 || value.every((item) => isJsonPrimitive(item));
}
function isArrayOfArrays(value) {
  return value.length === 0 || value.every((item) => isJsonArray(item));
}
function isArrayOfObjects(value) {
  return value.length === 0 || value.every((item) => isJsonObject(item));
}
var NUMERIC_LIKE_PATTERN = /^-?\d+(?:\.\d+)?(?:e[+-]?\d+)?$/i;
var LEADING_ZERO_PATTERN = /^0\d+$/;
function isValidUnquotedKey(key) {
  return /^[A-Z_][\w.]*$/i.test(key);
}
function isIdentifierSegment(key) {
  return /^[A-Z_]\w*$/i.test(key);
}
function isSafeUnquoted(value, delimiter = DEFAULT_DELIMITER) {
  if (!value) return false;
  if (value !== value.trim()) return false;
  if (isBooleanOrNullLiteral(value) || isNumericLike(value)) return false;
  if (value.includes(":")) return false;
  if (value.includes('"') || value.includes("\\")) return false;
  if (/[[\]{}]/.test(value)) return false;
  if (/[\u0000-\u001F]/.test(value)) return false;
  if (value.includes(delimiter)) return false;
  if (value.startsWith("-")) return false;
  return true;
}
function isNumericLike(value) {
  return NUMERIC_LIKE_PATTERN.test(value) || LEADING_ZERO_PATTERN.test(value);
}
function tryFoldKeyChain(key, value, siblings, options, rootLiteralKeys, pathPrefix, flattenDepth) {
  if (options.keyFolding !== "safe") return;
  if (!isJsonObject(value)) return;
  const { segments, tail, leafValue } = collectSingleKeyChain(key, value, flattenDepth ?? options.flattenDepth);
  if (segments.length < 2) return;
  if (!segments.every((seg) => isIdentifierSegment(seg))) return;
  const foldedKey = buildFoldedKey(segments);
  const absolutePath = pathPrefix ? `${pathPrefix}.${foldedKey}` : foldedKey;
  if (siblings.includes(foldedKey)) return;
  if (rootLiteralKeys && rootLiteralKeys.has(absolutePath)) return;
  return {
    foldedKey,
    remainder: tail,
    leafValue,
    segmentCount: segments.length
  };
}
function collectSingleKeyChain(startKey, startValue, maxDepth) {
  const segments = [startKey];
  let currentValue = startValue;
  while (segments.length < maxDepth) {
    if (!isJsonObject(currentValue)) break;
    const keys = Object.keys(currentValue);
    if (keys.length !== 1) break;
    const nextKey = keys[0];
    const nextValue = currentValue[nextKey];
    segments.push(nextKey);
    currentValue = nextValue;
  }
  if (!isJsonObject(currentValue) || isEmptyObject(currentValue)) return {
    segments,
    tail: void 0,
    leafValue: currentValue
  };
  return {
    segments,
    tail: currentValue,
    leafValue: currentValue
  };
}
function buildFoldedKey(segments) {
  return segments.join(".");
}
function encodePrimitive(value, delimiter) {
  if (value === null) return NULL_LITERAL;
  if (typeof value === "boolean") return String(value);
  if (typeof value === "number") return String(value);
  return encodeStringLiteral(value, delimiter);
}
function encodeStringLiteral(value, delimiter = DEFAULT_DELIMITER) {
  if (isSafeUnquoted(value, delimiter)) return value;
  return `"${escapeString(value)}"`;
}
function encodeKey(key) {
  if (isValidUnquotedKey(key)) return key;
  return `"${escapeString(key)}"`;
}
function encodeAndJoinPrimitives(values, delimiter = DEFAULT_DELIMITER) {
  return values.map((v) => encodePrimitive(v, delimiter)).join(delimiter);
}
function formatHeader(length, options) {
  const key = options?.key;
  const fields = options?.fields;
  const delimiter = options?.delimiter ?? ",";
  let header = "";
  if (key != null) header += encodeKey(key);
  header += `[${length}${delimiter !== DEFAULT_DELIMITER ? delimiter : ""}]`;
  if (fields) {
    const quotedFields = fields.map((f) => encodeKey(f));
    header += `{${quotedFields.join(delimiter)}}`;
  }
  header += ":";
  return header;
}
function* encodeJsonValue(value, options, depth) {
  if (isJsonPrimitive(value)) {
    const encodedPrimitive = encodePrimitive(value, options.delimiter);
    if (encodedPrimitive !== "") yield encodedPrimitive;
    return;
  }
  if (isJsonArray(value)) yield* encodeArrayLines(void 0, value, depth, options);
  else if (isJsonObject(value)) yield* encodeObjectLines(value, depth, options);
}
function* encodeObjectLines(value, depth, options, rootLiteralKeys, pathPrefix, remainingDepth) {
  const keys = Object.keys(value);
  if (depth === 0 && !rootLiteralKeys) rootLiteralKeys = new Set(keys.filter((k) => k.includes(".")));
  const effectiveFlattenDepth = remainingDepth ?? options.flattenDepth;
  for (const [key, val] of Object.entries(value)) yield* encodeKeyValuePairLines(key, val, depth, options, keys, rootLiteralKeys, pathPrefix, effectiveFlattenDepth);
}
function* encodeKeyValuePairLines(key, value, depth, options, siblings, rootLiteralKeys, pathPrefix, flattenDepth) {
  const currentPath = pathPrefix ? `${pathPrefix}.${key}` : key;
  const effectiveFlattenDepth = flattenDepth ?? options.flattenDepth;
  if (options.keyFolding === "safe" && siblings) {
    const foldResult = tryFoldKeyChain(key, value, siblings, options, rootLiteralKeys, pathPrefix, effectiveFlattenDepth);
    if (foldResult) {
      const { foldedKey, remainder, leafValue, segmentCount } = foldResult;
      const encodedFoldedKey = encodeKey(foldedKey);
      if (remainder === void 0) {
        if (isJsonPrimitive(leafValue)) {
          yield indentedLine(depth, `${encodedFoldedKey}: ${encodePrimitive(leafValue, options.delimiter)}`, options.indent);
          return;
        } else if (isJsonArray(leafValue)) {
          yield* encodeArrayLines(foldedKey, leafValue, depth, options);
          return;
        } else if (isJsonObject(leafValue) && isEmptyObject(leafValue)) {
          yield indentedLine(depth, `${encodedFoldedKey}:`, options.indent);
          return;
        }
      }
      if (isJsonObject(remainder)) {
        yield indentedLine(depth, `${encodedFoldedKey}:`, options.indent);
        const remainingDepth = effectiveFlattenDepth - segmentCount;
        const foldedPath = pathPrefix ? `${pathPrefix}.${foldedKey}` : foldedKey;
        yield* encodeObjectLines(remainder, depth + 1, options, rootLiteralKeys, foldedPath, remainingDepth);
        return;
      }
    }
  }
  const encodedKey = encodeKey(key);
  if (isJsonPrimitive(value)) yield indentedLine(depth, `${encodedKey}: ${encodePrimitive(value, options.delimiter)}`, options.indent);
  else if (isJsonArray(value)) yield* encodeArrayLines(key, value, depth, options);
  else if (isJsonObject(value)) {
    yield indentedLine(depth, `${encodedKey}:`, options.indent);
    if (!isEmptyObject(value)) yield* encodeObjectLines(value, depth + 1, options, rootLiteralKeys, currentPath, effectiveFlattenDepth);
  }
}
function* encodeArrayLines(key, value, depth, options) {
  if (value.length === 0) {
    yield indentedLine(depth, key != null ? `${encodeKey(key)}: []` : "[]", options.indent);
    return;
  }
  if (isArrayOfPrimitives(value)) {
    yield indentedLine(depth, encodeInlineArrayLine(value, options.delimiter, key), options.indent);
    return;
  }
  if (isArrayOfArrays(value)) {
    if (value.every((arr) => isArrayOfPrimitives(arr))) {
      yield* encodeArrayOfArraysAsListItemsLines(key, value, depth, options);
      return;
    }
  }
  if (isArrayOfObjects(value)) {
    const header = extractTabularHeader(value);
    if (header) yield* encodeArrayOfObjectsAsTabularLines(key, value, header, depth, options);
    else yield* encodeMixedArrayAsListItemsLines(key, value, depth, options);
    return;
  }
  yield* encodeMixedArrayAsListItemsLines(key, value, depth, options);
}
function* encodeArrayOfArraysAsListItemsLines(prefix, values, depth, options) {
  yield indentedLine(depth, formatHeader(values.length, {
    key: prefix,
    delimiter: options.delimiter
  }), options.indent);
  for (const arr of values) if (isArrayOfPrimitives(arr)) {
    const arrayLine = encodeInlineArrayLine(arr, options.delimiter);
    yield indentedListItem(depth + 1, arrayLine, options.indent);
  }
}
function encodeInlineArrayLine(values, delimiter, prefix) {
  const header = formatHeader(values.length, {
    key: prefix,
    delimiter
  });
  const joinedValue = encodeAndJoinPrimitives(values, delimiter);
  if (values.length === 0) return header;
  return `${header} ${joinedValue}`;
}
function* encodeArrayOfObjectsAsTabularLines(prefix, rows, header, depth, options) {
  yield indentedLine(depth, formatHeader(rows.length, {
    key: prefix,
    fields: header,
    delimiter: options.delimiter
  }), options.indent);
  yield* writeTabularRowsLines(rows, header, depth + 1, options);
}
function extractTabularHeader(rows) {
  if (rows.length === 0) return;
  const firstRow = rows[0];
  const firstKeys = Object.keys(firstRow);
  if (firstKeys.length === 0) return;
  if (isTabularArray(rows, firstKeys)) return firstKeys;
}
function isTabularArray(rows, header) {
  for (const row of rows) {
    if (Object.keys(row).length !== header.length) return false;
    for (const key of header) {
      if (!(key in row)) return false;
      if (!isJsonPrimitive(row[key])) return false;
    }
  }
  return true;
}
function* writeTabularRowsLines(rows, header, depth, options) {
  for (const row of rows) yield indentedLine(depth, encodeAndJoinPrimitives(header.map((key) => row[key]), options.delimiter), options.indent);
}
function* encodeMixedArrayAsListItemsLines(prefix, items, depth, options) {
  yield indentedLine(depth, formatHeader(items.length, {
    key: prefix,
    delimiter: options.delimiter
  }), options.indent);
  for (const item of items) yield* encodeListItemValueLines(item, depth + 1, options);
}
function* encodeObjectAsListItemLines(obj, depth, options) {
  if (isEmptyObject(obj)) {
    yield indentedLine(depth, "-", options.indent);
    return;
  }
  const entries = Object.entries(obj);
  const [firstKey, firstValue] = entries[0];
  const restEntries = entries.slice(1);
  if (isJsonArray(firstValue) && isArrayOfObjects(firstValue)) {
    const header = extractTabularHeader(firstValue);
    if (header) {
      yield indentedListItem(depth, formatHeader(firstValue.length, {
        key: firstKey,
        fields: header,
        delimiter: options.delimiter
      }), options.indent);
      yield* writeTabularRowsLines(firstValue, header, depth + 2, options);
      if (restEntries.length > 0) yield* encodeObjectLines(Object.fromEntries(restEntries), depth + 1, options);
      return;
    }
  }
  const encodedKey = encodeKey(firstKey);
  if (isJsonPrimitive(firstValue)) yield indentedListItem(depth, `${encodedKey}: ${encodePrimitive(firstValue, options.delimiter)}`, options.indent);
  else if (isJsonArray(firstValue)) if (firstValue.length === 0) yield indentedListItem(depth, `${encodedKey}: []`, options.indent);
  else if (isArrayOfPrimitives(firstValue)) yield indentedListItem(depth, `${encodedKey}${encodeInlineArrayLine(firstValue, options.delimiter)}`, options.indent);
  else {
    yield indentedListItem(depth, `${encodedKey}${formatHeader(firstValue.length, { delimiter: options.delimiter })}`, options.indent);
    for (const item of firstValue) yield* encodeListItemValueLines(item, depth + 2, options);
  }
  else if (isJsonObject(firstValue)) {
    yield indentedListItem(depth, `${encodedKey}:`, options.indent);
    if (!isEmptyObject(firstValue)) yield* encodeObjectLines(firstValue, depth + 2, options);
  }
  if (restEntries.length > 0) yield* encodeObjectLines(Object.fromEntries(restEntries), depth + 1, options);
}
function* encodeListItemValueLines(value, depth, options) {
  if (isJsonPrimitive(value)) yield indentedListItem(depth, encodePrimitive(value, options.delimiter), options.indent);
  else if (isJsonArray(value)) if (isArrayOfPrimitives(value)) yield indentedListItem(depth, encodeInlineArrayLine(value, options.delimiter), options.indent);
  else {
    yield indentedListItem(depth, formatHeader(value.length, { delimiter: options.delimiter }), options.indent);
    for (const item of value) yield* encodeListItemValueLines(item, depth + 1, options);
  }
  else if (isJsonObject(value)) yield* encodeObjectAsListItemLines(value, depth, options);
}
function indentedLine(depth, content, indentSize) {
  return " ".repeat(indentSize * depth) + content;
}
function indentedListItem(depth, content, indentSize) {
  return indentedLine(depth, "- " + content, indentSize);
}
function applyReplacer(root, replacer) {
  const replacedRoot = replacer("", root, []);
  if (replacedRoot === void 0) return transformChildren(root, replacer, []);
  return transformChildren(normalizeValue(replacedRoot), replacer, []);
}
function transformChildren(value, replacer, path) {
  if (isJsonObject(value)) return transformObject(value, replacer, path);
  if (isJsonArray(value)) return transformArray(value, replacer, path);
  return value;
}
function transformObject(obj, replacer, path) {
  const result = {};
  for (const [key, value] of Object.entries(obj)) {
    const childPath = [...path, key];
    const replacedValue = replacer(key, value, childPath);
    if (replacedValue === void 0) continue;
    result[key] = transformChildren(normalizeValue(replacedValue), replacer, childPath);
  }
  return result;
}
function transformArray(arr, replacer, path) {
  const result = [];
  for (let i = 0; i < arr.length; i++) {
    const value = arr[i];
    const childPath = [...path, i];
    const replacedValue = replacer(String(i), value, childPath);
    if (replacedValue === void 0) continue;
    const normalizedValue = normalizeValue(replacedValue);
    result.push(transformChildren(normalizedValue, replacer, childPath));
  }
  return result;
}
function encode(input, options) {
  return Array.from(encodeLines(input, options)).join("\n");
}
function encodeLines(input, options) {
  const normalizedValue = normalizeValue(input);
  const resolvedOptions = resolveOptions(options);
  return encodeJsonValue(resolvedOptions.replacer ? applyReplacer(normalizedValue, resolvedOptions.replacer) : normalizedValue, resolvedOptions, 0);
}
function resolveOptions(options) {
  return {
    indent: options?.indent ?? 2,
    delimiter: options?.delimiter ?? DEFAULT_DELIMITER,
    keyFolding: options?.keyFolding ?? "off",
    flattenDepth: options?.flattenDepth ?? Number.POSITIVE_INFINITY,
    replacer: options?.replacer
  };
}

// node_modules/.bun/axi-sdk-js@0.1.7/node_modules/axi-sdk-js/dist/output.js
function collapseHomeDirectory(path, homeDir = homedir()) {
  if (!path.startsWith(homeDir)) {
    return path;
  }
  return `~${path.slice(homeDir.length)}`;
}
function homeHeaderOutput(options) {
  return {
    bin: collapseHomeDirectory(options.execPath ?? process.argv[1] ?? "", options.homeDir),
    description: options.description
  };
}
function errorOutput(message, code, suggestions = []) {
  const output = {
    error: message,
    code
  };
  if (suggestions.length > 0) {
    output.help = suggestions;
  }
  return output;
}
function renderOutput(output) {
  if (typeof output === "string") {
    return output;
  }
  return encode(output);
}
function renderError(message, code, suggestions = []) {
  return renderOutput(errorOutput(message, code, suggestions));
}

// node_modules/.bun/axi-sdk-js@0.1.7/node_modules/axi-sdk-js/dist/cli.js
function defaultFormatError(error) {
  if (error instanceof AxiError) {
    return {
      output: `${renderError(error.message, error.code, error.suggestions)}
`,
      exitCode: exitCodeForError(error)
    };
  }
  const message = error instanceof Error ? error.message : String(error);
  return {
    output: `${renderError(message, "UNKNOWN")}
`,
    exitCode: 1
  };
}
function defaultUnknownCommand(command) {
  return `${renderError(`Unknown command: ${command}`, "VALIDATION_ERROR", [
    "Run `--help` to see available commands"
  ])}
`;
}
async function runAxiCli(options) {
  options.initialize?.();
  const stdout = options.stdout ?? process.stdout;
  const argv = options.argv ?? process.argv.slice(2);
  if (argv.length === 1 && argv[0] === "--help") {
    stdout.write(options.topLevelHelp);
    return;
  }
  if (argv.length === 1 && isVersionFlag(argv[0])) {
    if (!options.version) {
      stdout.write(`${renderError("Version is not configured for this tool", "VALIDATION_ERROR")}
`);
      process.exitCode = 2;
      return;
    }
    stdout.write(`${options.version}
`);
    return;
  }
  const command = argv[0];
  if (!command) {
    const context2 = await options.resolveContext?.({
      command: void 0,
      args: []
    });
    await runHandler(options.home, [], context2, stdout, options, true);
    return;
  }
  if (command.startsWith("-")) {
    stdout.write(renderLeadingFlagError(command));
    process.exitCode = 2;
    return;
  }
  const args = argv.slice(1);
  if (args.includes("--help")) {
    const help = options.getCommandHelp?.(command);
    if (help) {
      stdout.write(help);
      return;
    }
  }
  const handler = options.commands[command];
  if (!handler) {
    stdout.write((options.renderUnknownCommand ?? defaultUnknownCommand)(command));
    process.exitCode = 2;
    return;
  }
  const context = await options.resolveContext?.({ command, args });
  await runHandler(handler, args, context, stdout, options, false);
}
async function runHandler(handler, args, context, stdout, options, isHomeView) {
  try {
    const output = await handler(args, context);
    stdout.write(`${renderCommandOutput(output, options, isHomeView)}
`);
  } catch (error) {
    const formatted = (options.formatError ?? defaultFormatError)(error);
    stdout.write(formatted.output);
    process.exitCode = formatted.exitCode;
  }
}
function renderLeadingFlagError(flag) {
  const bin = basename(process.argv[1] ?? "tool") || "tool";
  return `${renderError("Flags must come after the command", "VALIDATION_ERROR", [
    `Run \`${bin} <command> [args] [flags]\``,
    `Move \`${flag}\` after the command instead of before it`
  ])}
`;
}
function isVersionFlag(flag) {
  return flag === "-v" || flag === "-V" || flag === "--version";
}
function renderCommandOutput(output, options, isHomeView) {
  if (!isHomeView) {
    return renderOutput(output);
  }
  const header = homeHeaderOutput({ description: options.description });
  if (typeof output === "string") {
    return `${renderOutput(header)}
${output}`;
  }
  return renderOutput(mergeHomeHeader(header, output));
}
function mergeHomeHeader(header, output) {
  const rest = { ...output };
  delete rest.bin;
  delete rest.description;
  return {
    ...header,
    ...rest
  };
}

// packages/sessions/src/axi/reference.ts
var DESCRIPTION = "Search and recall context from past Claude Code sessions across machines \u2014 by topic (full-text search), by time period (cross-session transcripts), and by activity.";
var COMMAND_GROUPS = [
  {
    group: "Recall",
    commands: [
      {
        usage: "search [--query TEXT] [--project PATH] [--days N | --since DATE --until DATE | --forever] [--tools a,b] [--files-read frag] [--files-written frag] [--machine ID] [--min-user-messages N] [--include-empty] [--limit N] [--offset N]",
        summary: "find sessions by topic/tool/file (tools & files are substring matches); defaults to last 30 days, hides subagent sessions at --min-user-messages 2"
      },
      {
        usage: "transcript <session-id> [--after DATE] [--before DATE] [--include-tools]",
        summary: "compact, token-efficient transcript of one session (optionally trimmed to a time window)"
      },
      {
        usage: "transcript --after DATE --before DATE [--group project|time] [--project PATH] [--min-user-messages N] [--include-tools]",
        summary: 'cross-session transcript for a time range \u2014 the primary tool for "what did I work on <when>?"'
      },
      {
        usage: 'grep <session-id> --tool Bash --match "text" [--in target|text|tool] [--context N]',
        summary: "find tool calls / text within a transcript \u2014 windowed matches + anchors"
      },
      {
        usage: "grep --tool Edit --match routes.ts [--project P] [--days N]",
        summary: "no id \u2192 cross-session tool-call discovery over the index"
      },
      {
        usage: "transcript <session-id> --around <uuid> [--before N] [--after M]",
        summary: "explore a variable range of messages around an anchor (the grep follow-up)"
      },
      { usage: "details <session-id> [--raw]", summary: "session metadata; --raw adds the parsed raw messages" },
      { usage: "activity [--days N]", summary: "when work happened \u2014 active time blocks per session (default 7 days)" }
    ]
  },
  {
    group: "Overview",
    commands: [
      { usage: "stats [--days N] [--machine ID]", summary: "usage statistics: top tools, models, tokens, per-machine counts" },
      { usage: "machines", summary: "list registered machines with sync status" }
    ]
  },
  {
    group: "Manage",
    commands: [
      { usage: "outlines [<session-id>...]", summary: "generate AI outlines for sessions missing/stale ones (needs the server's model invoker)" },
      { usage: "outlines progress", summary: "check background outline-generation progress" },
      { usage: "sync [--force]", summary: "trigger an immediate local session sync (--force re-parses all)" },
      { usage: "share <session-id>", summary: "mint a shareable auth code for a session transcript" }
    ]
  }
];
function commandReferenceText() {
  return COMMAND_GROUPS.map((g) => {
    const items = g.commands.map((c) => `  ${c.usage}
      ${c.summary}`).join("\n");
    return `${g.group}:
${items}`;
  }).join("\n\n");
}
function discoveryHelp(invocation) {
  return `Run \`${invocation} --help\` for the full command list, or \`${invocation} <command> --help\` for usage on any command`;
}

// packages/sessions/src/axi/invocation.ts
import { accessSync, constants } from "node:fs";
import { homedir as homedir2 } from "node:os";
import { fileURLToPath } from "node:url";
var cached;
function cliInvocation() {
  if (cached) return cached;
  let bundle;
  try {
    bundle = fileURLToPath(import.meta.url);
  } catch {
    bundle = process.argv[1] ?? "sessions-axi";
  }
  const shim = bundle.replace(/\.mjs$/, "");
  try {
    if (shim !== bundle) {
      accessSync(shim, constants.X_OK);
      cached = quote(collapseHome(shim));
      return cached;
    }
  } catch {
  }
  cached = `node ${quote(collapseHome(bundle))}`;
  return cached;
}
function collapseHome(p) {
  const home = homedir2();
  return home && p.startsWith(`${home}/`) ? `~${p.slice(home.length)}` : p;
}
function quote(p) {
  return /\s/.test(p) ? `"${p}"` : p;
}

// packages/sessions/src/axi/commands/home.ts
import { execSync } from "node:child_process";
import { basename as basename2 } from "node:path";
import { homedir as homedir3 } from "node:os";

// packages/sessions/src/axi/client.ts
var DEFAULT_SERVER = "http://localhost:2529";
function resolveServer() {
  const env = process.env.CLAUDE_ASSIST_SERVER?.trim();
  return (env || DEFAULT_SERVER).replace(/\/+$/, "");
}
function buildUrl(server, path, query) {
  let url = `${server}${path}`;
  if (query) {
    const qs = new URLSearchParams();
    for (const [k, v] of Object.entries(query)) {
      if (v === void 0 || v === null || v === "") continue;
      if (Array.isArray(v)) {
        for (const item of v) if (item !== void 0 && item !== null && item !== "") qs.append(k, String(item));
      } else {
        qs.append(k, String(v));
      }
    }
    const s = qs.toString();
    if (s) url += `?${s}`;
  }
  return url;
}
function suggestForStatus(status) {
  if (status === 404) return ["Check the id \u2014 try `search` to look one up"];
  if (status === 400) return ["Check required params and value formats for this command"];
  if (status === 503) return ["The server is up but this feature may be disabled (e.g. the model invoker is unavailable)"];
  return [];
}
async function send(method, path, opts = {}) {
  const server = resolveServer();
  const url = buildUrl(server, path, opts.query);
  const hasBody = opts.body !== void 0 && opts.body !== null;
  const init = { method, headers: hasBody ? { "Content-Type": "application/json" } : {} };
  if (hasBody) init.body = JSON.stringify(opts.body);
  let res;
  try {
    res = await fetch(url, init);
  } catch (err) {
    throw new AxiError(
      `Cannot reach claude-assist server at ${server} (${err.message})`,
      "HTTP_ERROR",
      ["Set CLAUDE_ASSIST_SERVER or start the server (cd apps/server && docker-compose up -d)"]
    );
  }
  return res;
}
async function parseError(res) {
  const text = await res.text();
  let message = res.statusText || `HTTP ${res.status}`;
  if (text) {
    try {
      const data = JSON.parse(text);
      if (data && typeof data === "object" && data.error) message = data.error;
      else if (data && typeof data === "object" && data.message) message = data.message;
    } catch {
      message = text.slice(0, 200);
    }
  }
  throw new AxiError(`API error (${res.status}): ${message}`, "HTTP_ERROR", suggestForStatus(res.status));
}
var api = {
  async get(path, query) {
    const res = await send("GET", path, { query });
    if (!res.ok) await parseError(res);
    const text = await res.text();
    if (!text) return null;
    try {
      return JSON.parse(text);
    } catch {
      return text;
    }
  },
  /** GET an endpoint that returns text/plain (e.g. transcripts). */
  async getText(path, query) {
    const res = await send("GET", path, { query });
    if (!res.ok) await parseError(res);
    return res.text();
  },
  async post(path, body, query) {
    const res = await send("POST", path, { body, query });
    if (!res.ok) await parseError(res);
    const text = await res.text();
    if (!text) return null;
    try {
      return JSON.parse(text);
    } catch {
      return text;
    }
  }
};

// packages/sessions/src/axi/args.ts
function parseArgs(args, booleanFlags = []) {
  const positionals = [];
  const flags = {};
  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg.startsWith("--")) {
      const name = arg.slice(2);
      if (booleanFlags.includes(name)) {
        flags[name] = true;
      } else {
        const value = args[++i];
        if (value === void 0) {
          throw new AxiError(`Flag --${name} requires a value`, "VALIDATION_ERROR");
        }
        flags[name] = value;
      }
    } else {
      positionals.push(arg);
    }
  }
  return { positionals, flags };
}
function requirePositional(positionals, index, label, usage) {
  const v = positionals[index];
  if (!v) throw new AxiError(`${label} is required`, "VALIDATION_ERROR", [usage]);
  return v;
}
var DATE_ONLY = /^\d{4}-\d{2}-\d{2}$/;
var ISO_DATETIME = /^\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}(:\d{2}(\.\d+)?)?(Z|[+-]\d{2}:?\d{2})?$/;
function validateDate(value, flag, usage) {
  const wellFormed = DATE_ONLY.test(value) || ISO_DATETIME.test(value);
  if (!wellFormed || Number.isNaN(Date.parse(value))) {
    throw new AxiError(`Invalid date for ${flag}: ${value}`, "VALIDATION_ERROR", [
      "Use YYYY-MM-DD (e.g. 2026-04-29) or a full ISO 8601 timestamp (e.g. 2026-04-29T14:30:00Z)",
      usage
    ]);
  }
  return value;
}
function rawJson(data) {
  return JSON.stringify(data, null, 2);
}

// packages/sessions/src/axi/toon.ts
function field(key, as) {
  return { type: "field", key, as };
}
function count(key, as) {
  return { type: "count", key, as };
}
function relativeTime(key, as) {
  return { type: "relativeTime", key, as };
}
function truncate(key, limit, as) {
  return { type: "truncate", key, limit, as };
}
function custom(as, fn) {
  return { type: "custom", as, fn };
}
function outputKey(def) {
  if (def.type === "custom") return def.as;
  return def.as ?? def.key;
}
function extract(item, schema) {
  const result = {};
  for (const def of schema) {
    const key = outputKey(def);
    switch (def.type) {
      case "field":
        result[key] = item[def.key] ?? null;
        break;
      case "pluck":
        result[key] = item[def.key]?.[def.subkey] ?? null;
        break;
      case "joinArray": {
        const arr = item[def.key];
        if (Array.isArray(arr) && arr.length > 0) {
          result[key] = arr.map(
            (x) => def.subkey && x && typeof x === "object" ? x[def.subkey] : x
          ).join(",");
        } else {
          result[key] = def.empty ?? "none";
        }
        break;
      }
      case "count": {
        const arr = item[def.key];
        result[key] = Array.isArray(arr) ? arr.length : 0;
        break;
      }
      case "relativeTime":
        result[key] = formatRelativeTime(item[def.key]);
        break;
      case "dateOnly":
        result[key] = formatDateOnly(item[def.key]);
        break;
      case "boolYesNo":
        result[key] = item[def.key] ? "yes" : "no";
        break;
      case "truncate":
        result[key] = truncateText(item[def.key], def.limit).value;
        break;
      case "custom":
        result[key] = def.fn(item);
        break;
    }
  }
  return result;
}
function renderList(label, items, schema) {
  return encode({ [label]: items.map((item) => extract(item, schema)) });
}
function renderDetail(label, item, schema) {
  return encode({ [label]: extract(item, schema) });
}
function renderObject(obj) {
  return encode(obj);
}
function renderHelp(lines) {
  const clean = lines.filter(Boolean);
  if (clean.length === 0) return "";
  return `help[${clean.length}]:
${clean.map((l) => `  ${l}`).join("\n")}`;
}
function renderOutput2(blocks) {
  return blocks.filter(Boolean).join("\n");
}
var DEFAULT_TRUNCATE = 280;
function truncateText(text, limit = DEFAULT_TRUNCATE) {
  if (typeof text !== "string") return { value: text ?? null, truncated: false, total: 0 };
  if (text.length <= limit) return { value: text, truncated: false, total: text.length };
  return {
    value: `${text.slice(0, limit)}\u2026 (truncated, ${text.length} chars total)`,
    truncated: true,
    total: text.length
  };
}
function formatDateOnly(value) {
  if (!value) return null;
  const d = new Date(value);
  if (isNaN(d.getTime())) return String(value);
  return d.toISOString().slice(0, 10);
}
function formatRelativeTime(value) {
  if (!value) return "unknown";
  const then = new Date(value).getTime();
  if (isNaN(then)) return "unknown";
  const diffSec = Math.floor((Date.now() - then) / 1e3);
  const past = diffSec >= 0;
  const s = Math.abs(diffSec);
  const fmt = (n, unit) => past ? `${n}${unit} ago` : `in ${n}${unit}`;
  if (s < 60) return past ? "just now" : "soon";
  const min = Math.floor(s / 60);
  if (min < 60) return fmt(min, "m");
  const hr = Math.floor(min / 60);
  if (hr < 24) return fmt(hr, "h");
  const day = Math.floor(hr / 24);
  if (day < 30) return fmt(day, "d");
  const mon = Math.floor(day / 30);
  if (mon < 12) return fmt(mon, "mo");
  return fmt(Math.floor(mon / 12), "y");
}

// packages/sessions/src/axi/commands/home.ts
function lastActivityMs(s) {
  return new Date(s.ended_at ?? s.started_at).getTime() || 0;
}
var RECENT_SCHEMA = [
  field("id"),
  custom("title", (s) => s.title ?? s.session_name ?? null),
  field("machine"),
  relativeTime("started_at", "started"),
  custom("last_activity", (s) => formatRelativeTime(s.ended_at ?? s.started_at))
];
var MACHINE_SCHEMA = [
  field("machine_id", "machine"),
  { type: "boolYesNo", key: "is_localhost", as: "localhost" },
  field("session_count", "sessions"),
  relativeTime("last_sync_at", "last_sync")
];
function detectGitProject() {
  try {
    const root = execSync("git rev-parse --show-toplevel", {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"]
    }).trim();
    if (!root) return null;
    return { name: basename2(root), root };
  } catch {
    return null;
  }
}
function collapseHome2(p) {
  const home = homedir3();
  return home && p.startsWith(`${home}/`) ? `~${p.slice(home.length)}` : p;
}
async function homeCommand(args) {
  const { flags } = parseArgs(args, ["json", "all"]);
  const server = resolveServer();
  const cli = cliInvocation();
  const recentN = typeof flags.recent === "string" ? Math.max(parseInt(flags.recent, 10) || 5, 1) : 5;
  const override = typeof flags.project === "string" ? flags.project : void 0;
  const detected = flags.all ? null : override ? { name: override, root: process.cwd() } : detectGitProject();
  if (detected) {
    let recent = null;
    try {
      const res = await api.get("/api/sessions", {
        project: detected.name,
        min_user_messages: 2,
        forever: "true",
        limit: Math.max(recentN * 5, 25)
      });
      recent = (Array.isArray(res) ? res : []).sort((a, b) => lastActivityMs(b) - lastActivityMs(a)).slice(0, recentN);
    } catch {
      recent = null;
    }
    if (flags.json) return rawJson({ server, project: detected.name, cwd: detected.root, recent });
    const header = renderObject({
      server,
      project: detected.name,
      cwd: collapseHome2(detected.root)
    });
    const blocks2 = [header];
    if (recent === null) {
      blocks2.push("The server is not reachable. Set CLAUDE_ASSIST_SERVER or start it (cd apps/server && docker-compose up -d).");
    } else if (recent.length === 0) {
      blocks2.push(`no prior sessions found for project "${detected.name}" \u2014 run \`${cli} home --all\` for the cross-project view`);
    } else {
      blocks2.push(`recent[${recent.length}] in ${detected.name}:`);
      blocks2.push(renderList("recent", recent, RECENT_SCHEMA));
    }
    blocks2.push(
      renderHelp([
        `Run \`${cli} transcript <session-id>\` to read where you left off`,
        `Run \`${cli} search --query "<topic>" --project ${detected.name}\` to search within this repo`,
        `Run \`${cli} home --all\` for the cross-project (machines) view`,
        discoveryHelp(cli)
      ])
    );
    return renderOutput2(blocks2);
  }
  let machines = null;
  try {
    const res = await api.get("/api/machines");
    machines = Array.isArray(res) ? res : [];
  } catch {
    machines = null;
  }
  if (flags.json) return rawJson({ server, machines });
  const blocks = [renderObject({ server })];
  if (machines === null) {
    blocks.push("The server is not reachable. Set CLAUDE_ASSIST_SERVER or start it (cd apps/server && docker-compose up -d).");
  } else if (machines.length === 0) {
    blocks.push("machines: none registered");
  } else {
    blocks.push(renderList("machines", machines, MACHINE_SCHEMA));
  }
  blocks.push(
    renderHelp([
      `Run \`${cli} transcript --after <ISO> --before <ISO>\` for "what did I work on <when>?" (the primary temporal tool)`,
      `Run \`${cli} search --query "<topic>" --project <repo>\` to find sessions by topic`,
      `Run \`${cli} activity --days 7\` to see when work happened`,
      discoveryHelp(cli)
    ])
  );
  return renderOutput2(blocks);
}

// packages/sessions/src/axi/commands/search.ts
var SEARCH_HELP = `sessions-axi search [flags]

  Find past sessions by topic, tool, or file. Full-text search is weighted
  (user prompts + outlines > tools/files > project path).

  --query TEXT             full-text search query (omit to list recent sessions)
  --project PATH           filter by project path (substring match)
  --days N                 limit to the last N days (default 30)
  --since DATE             absolute start (ISO 8601 / YYYY-MM-DD); overrides --days
  --until DATE             absolute end (ISO 8601 / YYYY-MM-DD)
  --forever                no date limit (for "have we ever\u2026?" questions)
  --tools a,b              tools used \u2014 comma-separated substring matches (e.g. Bash,mcp__slack)
  --files-read frag        a read file path contains this substring
  --files-written frag     a written file path contains this substring
  --machine ID             filter by machine id (e.g. localhost, laptop)
  --min-user-messages N    hide subagent sessions (default behavior: pass 2)
  --include-empty          include sessions with no assistant output
  --limit N                max results (default 20, max 100)
  --offset N               pagination offset
  --json                   raw API JSON`;
function shortProject(p) {
  if (typeof p !== "string" || !p) return "\u2014";
  return p.split("/").filter(Boolean).pop() ?? p;
}
var SCHEMA = [
  field("id"),
  relativeTime("started_at", "started"),
  custom("project", (s) => shortProject(s.project_path)),
  custom("title", (s) => s.title ?? s.session_name ?? null),
  field("user_message_count", "user_msgs"),
  count("tools_used", "tools"),
  field("machine")
];
async function searchCommand(args) {
  const { flags } = parseArgs(args, ["json", "forever", "include-empty"]);
  const query = {};
  if (typeof flags.query === "string") query.search = flags.query;
  if (typeof flags.project === "string") query.project = flags.project;
  if (typeof flags.days === "string") query.days = flags.days;
  if (typeof flags.since === "string") query.since = validateDate(flags.since, "--since", SEARCH_HELP);
  if (typeof flags.until === "string") query.until = validateDate(flags.until, "--until", SEARCH_HELP);
  if (flags.forever) query.forever = "true";
  if (typeof flags.tools === "string") query.tools = flags.tools;
  if (typeof flags["files-read"] === "string") query.files_read = flags["files-read"];
  if (typeof flags["files-written"] === "string") query.files_written = flags["files-written"];
  if (typeof flags.machine === "string") query.machine = flags.machine;
  if (typeof flags["min-user-messages"] === "string") query.min_user_messages = flags["min-user-messages"];
  if (flags["include-empty"]) query.include_empty = "true";
  if (typeof flags.limit === "string") query.limit = flags.limit;
  if (typeof flags.offset === "string") query.offset = flags.offset;
  const rows = await api.get("/api/sessions", query);
  if (flags.json) return rawJson(rows);
  if (!Array.isArray(rows) || rows.length === 0) {
    return "sessions: 0 matching sessions found";
  }
  const cli = cliInvocation();
  return renderOutput2([
    `count: ${rows.length}${rows.length === parseInt(query.limit ?? "20", 10) ? " (limit reached \u2014 page with --offset)" : ""}`,
    renderList("sessions", rows, SCHEMA),
    renderHelp([`Run \`${cli} transcript <session-id>\` to read one`])
  ]);
}

// packages/sessions/src/axi/commands/transcript.ts
var TRANSCRIPT_HELP = `sessions-axi transcript <session-id> [flags]                 # one session
sessions-axi transcript --after DATE --before DATE [flags]   # cross-session, a time range
sessions-axi transcript <session-id> --around <uuid> [--before N] [--after M]   # explore around an anchor

  Compact, token-efficient transcript text ([U] user, [A] assistant, [T] tool).
  With a session id \u2192 that session. Without one \u2192 every session overlapping the
  given window (the primary tool for "what did I work on <when>?").

  --after DATE             start of window (ISO 8601 / YYYY-MM-DD; required when no id)
  --before DATE            end of window (ISO 8601 / YYYY-MM-DD; required when no id)
  --group project|time     cross-session grouping (default project)
  --project PATH           cross-session: filter to a project path (substring)
  --min-user-messages N    cross-session: hide subagent sessions (default 2)
  --include-tools          include [T] tool-call lines (excluded by default)

  Anchor exploration (the follow-up to a \`grep\` match):
  --around <uuid>          read a window of messages around this message uuid
  --before N / --after M   in --around mode these are message COUNTS (not dates);
                           the result lists head/tail anchors + how much remains,
                           so you can keep walking outward. --json for raw.`;
async function transcriptCommand(args) {
  const { positionals, flags } = parseArgs(args, ["include-tools", "json"]);
  const id = positionals[0];
  if (typeof flags.around === "string") {
    if (!id) {
      throw new AxiError("--around needs a <session-id>", "VALIDATION_ERROR", [TRANSCRIPT_HELP]);
    }
    const window = await api.get(`/api/sessions/${encodeURIComponent(id)}/transcript`, {
      around: flags.around,
      before: typeof flags.before === "string" ? flags.before : void 0,
      after: typeof flags.after === "string" ? flags.after : void 0
    });
    if (flags.json) return rawJson(window);
    const cli = cliInvocation();
    const out = [
      `around ${flags.around}:`,
      ...window.lines ?? [],
      `\u2195 ${window.more_before} before \xB7 ${window.more_after} after${window.truncated ? " \xB7 window truncated" : ""}`
    ];
    if (window.more_before > 0) {
      out.push(`extend back:    ${cli} transcript ${id} --around ${window.head} --before 30 --after 0`);
    }
    if (window.more_after > 0) {
      out.push(`extend forward: ${cli} transcript ${id} --around ${window.tail} --before 0 --after 30`);
    }
    return out.join("\n");
  }
  const after = typeof flags.after === "string" ? validateDate(flags.after, "--after", TRANSCRIPT_HELP) : void 0;
  const before = typeof flags.before === "string" ? validateDate(flags.before, "--before", TRANSCRIPT_HELP) : void 0;
  const includeTools = flags["include-tools"] ? "true" : void 0;
  let text;
  if (id) {
    text = await api.getText(`/api/sessions/${encodeURIComponent(id)}/transcript`, {
      after,
      before,
      include_tools: includeTools
    });
  } else {
    if (!after || !before) {
      throw new AxiError("Cross-session transcript needs both --after and --before", "VALIDATION_ERROR", [
        TRANSCRIPT_HELP
      ]);
    }
    const group = typeof flags.group === "string" ? flags.group : void 0;
    if (group && group !== "project" && group !== "time") {
      throw new AxiError(`--group must be project or time (got ${group})`, "VALIDATION_ERROR", [TRANSCRIPT_HELP]);
    }
    text = await api.getText("/api/sessions/transcript", {
      after,
      before,
      group,
      project: typeof flags.project === "string" ? flags.project : void 0,
      min_user_messages: typeof flags["min-user-messages"] === "string" ? flags["min-user-messages"] : void 0,
      include_tools: includeTools
    });
  }
  const trimmed = text.trim();
  if (!trimmed) {
    return id ? "transcript: empty (no messages in range, or unknown session)" : "transcript: no sessions found overlapping that window";
  }
  return trimmed;
}

// packages/sessions/src/axi/commands/grep.ts
var GREP_HELP = `sessions-axi grep <session-id> [flags]      # within one transcript \u2192 windowed matches
sessions-axi grep [flags]                   # no id \u2192 cross-session tool-call discovery

  Find tool calls (by name/target) or message text inside transcripts. Each hit
  returns a window of surrounding messages and anchors you can explore from with
  \`transcript <id> --around <uuid> --before N --after M\`.

  --tool SUBSTR        tool name contains SUBSTR (e.g. Bash, mcp__slack)
  --match SUBSTR       content contains SUBSTR
  --in target|text|tool|any   where --match applies (default any; cross-session: target|tool)
  --context N          messages of context each side of a per-session hit (default 1)
  --limit N            max matches (default 10 per-session / 20 cross-session)
  --include-sidechain  include subagent messages (excluded by default)
  --after <uuid>       per-session: resume scanning after this message
  --before <uuid>      per-session: stop scanning at this message
  --project PATH       cross-session: filter by project path (substring)
  --days N             cross-session: only the last N days
  --json               raw API JSON

  At least one of --tool / --match is required.`;
var CROSS_SCHEMA = [
  field("session_id", "session"),
  custom("title", (r) => r.title ?? null),
  custom("when", (r) => formatRelativeTime(r.ts)),
  field("tool"),
  truncate("target", 60),
  field("anchor")
];
async function grepCommand(args) {
  const { positionals, flags } = parseArgs(args, ["json", "include-sidechain"]);
  const id = positionals[0];
  if (!flags.tool && !flags.match) {
    throw new AxiError("Provide --tool and/or --match", "VALIDATION_ERROR", [GREP_HELP]);
  }
  return id ? grepSession(id, flags) : grepCross(flags);
}
async function grepSession(id, flags) {
  const cli = cliInvocation();
  const query = {};
  if (typeof flags.tool === "string") query.tool = flags.tool;
  if (typeof flags.match === "string") query.match = flags.match;
  if (typeof flags.in === "string") query.in = flags.in;
  if (typeof flags.context === "string") query.context = flags.context;
  if (typeof flags.limit === "string") query.limit = flags.limit;
  if (typeof flags.after === "string") query.after_uuid = flags.after;
  if (typeof flags.before === "string") query.before_uuid = flags.before;
  if (flags["include-sidechain"]) query.include_sidechain = "true";
  const res = await api.get(`/api/sessions/${encodeURIComponent(id)}/find`, query);
  if (flags.json) return rawJson(res);
  const matches = res?.matches ?? [];
  if (matches.length === 0) return "grep: 0 matches in this session";
  const blocks = [`count: ${matches.length} match${matches.length === 1 ? "" : "es"}`];
  matches.forEach((m, i) => {
    const w = m.window;
    const label = m.tool ? `${m.tool}${m.target ? ` \xB7 ${m.target.slice(0, 60)}` : ""}` : "text";
    blocks.push(
      [
        ``,
        `match ${i + 1} \u2014 ${label} \u2014 msg ${m.index} \xB7 ${formatRelativeTime(m.ts)}`,
        ...w.lines,
        `  \u2195 ${w.more_before} before \xB7 ${w.more_after} after${w.truncated ? " \xB7 window truncated" : ""}`,
        `  explore: ${cli} transcript ${id} --around ${w.head} --before 20  |  ${cli} transcript ${id} --around ${w.tail} --after 20`
      ].join("\n")
    );
  });
  const last = matches[matches.length - 1];
  blocks.push(renderHelp([`Run \`${cli} grep ${id} \u2026 --after ${last.anchor}\` for the next matches`]));
  return renderOutput2(blocks);
}
async function grepCross(flags) {
  const cli = cliInvocation();
  if (flags.in === "text") {
    throw new AxiError("Cross-session text search is not indexed", "VALIDATION_ERROR", [
      `Use \`${cli} search --query "\u2026"\` to find sessions, then \`${cli} grep <id> --match "\u2026" --in text\``
    ]);
  }
  const query = {};
  if (typeof flags.tool === "string") query.tool = flags.tool;
  if (typeof flags.match === "string") query.match = flags.match;
  if (typeof flags.in === "string") query.in = flags.in;
  if (typeof flags.project === "string") query.project = flags.project;
  if (typeof flags.days === "string") query.days = flags.days;
  if (typeof flags.limit === "string") query.limit = flags.limit;
  if (flags["include-sidechain"]) query.include_sidechain = "true";
  const rows = await api.get("/api/sessions/find", query);
  if (flags.json) return rawJson(rows);
  if (!Array.isArray(rows) || rows.length === 0) return "grep: 0 matching tool calls found";
  return renderOutput2([
    `count: ${rows.length}`,
    renderList("matches", rows, CROSS_SCHEMA),
    renderHelp([
      `Run \`${cli} transcript <session> --around <anchor> --after 20\` to read around a match`,
      `Run \`${cli} grep <session> --tool \u2026 --match \u2026\` to window matches within one session`
    ])
  ]);
}

// packages/sessions/src/axi/commands/detail.ts
var DETAILS_HELP = `sessions-axi details <session-id> [--raw] [--json]

  Session metadata (tokens, tools, files, models). --raw includes the parsed
  raw message array (large); --json returns the raw API object.`;
var SCHEMA2 = [
  field("id"),
  field("machine"),
  field("project_path", "project"),
  field("git_branch", "branch"),
  field("started_at", "started"),
  field("ended_at", "ended"),
  field("user_message_count", "user_msgs"),
  field("message_count", "messages"),
  field("input_tokens"),
  field("output_tokens"),
  field("cache_read_tokens"),
  custom("tools", (s) => Array.isArray(s.tools_used) ? s.tools_used.join(",") : "none"),
  custom("files_read", (s) => Array.isArray(s.files_touched?.reads) ? s.files_touched.reads.length : 0),
  custom("files_written", (s) => Array.isArray(s.files_touched?.writes) ? s.files_touched.writes.length : 0),
  custom("models", (s) => Array.isArray(s.models_used) ? s.models_used.join(",") : "none"),
  field("title"),
  field("outline")
];
async function detailsCommand(args) {
  const { positionals, flags } = parseArgs(args, ["json", "raw"]);
  const id = requirePositional(positionals, 0, "session id", DETAILS_HELP);
  const session = await api.get(`/api/sessions/${encodeURIComponent(id)}`, {
    with_raw_messages: flags.raw ? "true" : void 0
  });
  if (flags.json || flags.raw) return rawJson(session);
  const cli = cliInvocation();
  return renderOutput2([
    renderDetail("session", session, SCHEMA2),
    renderHelp([`Run \`${cli} transcript ${id}\` to read the conversation`])
  ]);
}

// packages/sessions/src/axi/commands/activity.ts
var ACTIVITY_HELP = `sessions-axi activity [--days N] [--json]

  When work happened \u2014 contiguous active time blocks per session (segmented by a
  30-minute gap). Use for "when was I working?" / "how much time on X?". Default
  look-back is 7 days.`;
var SCHEMA3 = [
  field("id"),
  custom("project", (s) => s.project_name ?? s.project_path ?? "\u2014"),
  custom("title", (s) => s.title ?? s.session_name ?? null),
  field("total_active_minutes", "active_min"),
  custom("ranges", (s) => Array.isArray(s.activity_ranges) ? s.activity_ranges.length : 0)
];
async function activityCommand(args) {
  const { flags } = parseArgs(args, ["json"]);
  const rows = await api.get("/api/sessions/activity", {
    days: typeof flags.days === "string" ? flags.days : void 0
  });
  if (flags.json) return rawJson(rows);
  if (!Array.isArray(rows) || rows.length === 0) return "activity: no active sessions in range";
  const totalMin = rows.reduce((sum, r) => sum + (r.total_active_minutes ?? 0), 0);
  return renderOutput2([
    `count: ${rows.length} sessions, ${Math.round(totalMin / 60 * 10) / 10}h total active`,
    renderList("activity", rows, SCHEMA3)
  ]);
}

// packages/sessions/src/axi/commands/stats.ts
var STATS_HELP = `sessions-axi stats [--days N] [--machine ID] [--json]

  Usage statistics over the last N days (default 30): session/message/token
  totals, top tools, top models, and per-machine counts.`;
var TOOL_SCHEMA = [field("tool"), field("count")];
var MODEL_SCHEMA = [
  field("model"),
  field("session_count", "sessions"),
  field("input_tokens", "in"),
  field("output_tokens", "out"),
  field("cache_read_tokens", "cache_read")
];
var MACHINE_SCHEMA2 = [field("machine_id", "machine"), field("session_count", "sessions")];
async function statsCommand(args) {
  const { flags } = parseArgs(args, ["json"]);
  const stats = await api.get("/api/sessions/stats", {
    days: typeof flags.days === "string" ? flags.days : void 0,
    machine: typeof flags.machine === "string" ? flags.machine : void 0
  });
  if (flags.json) return rawJson(stats);
  return renderOutput2([
    renderObject({
      period_days: stats.period_days,
      total_sessions: stats.total_sessions,
      active_days: stats.active_days,
      total_messages: stats.total_messages,
      avg_messages: stats.avg_messages,
      input_tokens: stats.total_input_tokens,
      output_tokens: stats.total_output_tokens,
      unique_projects: stats.unique_projects
    }),
    Array.isArray(stats.top_tools) && stats.top_tools.length ? renderList("top_tools", stats.top_tools, TOOL_SCHEMA) : "",
    Array.isArray(stats.top_models) && stats.top_models.length ? renderList("top_models", stats.top_models, MODEL_SCHEMA) : "",
    Array.isArray(stats.sessions_per_machine) && stats.sessions_per_machine.length ? renderList("per_machine", stats.sessions_per_machine, MACHINE_SCHEMA2) : ""
  ]);
}

// packages/sessions/src/axi/commands/machines.ts
var MACHINES_HELP = `sessions-axi machines [--json]

  Registered machines and their sync status.`;
var SCHEMA4 = [
  field("machine_id", "machine"),
  field("hostname"),
  { type: "boolYesNo", key: "is_localhost", as: "localhost" },
  field("session_count", "sessions"),
  relativeTime("last_sync_at", "last_sync")
];
async function machinesCommand(args) {
  const { flags } = parseArgs(args, ["json"]);
  const rows = await api.get("/api/machines");
  if (flags.json) return rawJson(rows);
  if (!Array.isArray(rows) || rows.length === 0) return "machines: none registered";
  return renderOutput2([`count: ${rows.length}`, renderList("machines", rows, SCHEMA4)]);
}

// packages/sessions/src/axi/commands/manage.ts
var OUTLINES_HELP = `sessions-axi outlines [<session-id>...] [--json]
sessions-axi outlines progress [--json]

  Generate AI outlines for sessions missing or with stale ones (needs the
  server's model invoker). With no ids, processes all pending.
  \`outlines progress\` reports background generation status.`;
async function outlinesCommand(args) {
  const { positionals, flags } = parseArgs(args, ["json"]);
  if (positionals[0] === "progress") {
    const progress = await api.get("/api/sessions/outlines/progress");
    if (flags.json) return rawJson(progress);
    return renderObject(progress ?? { status: "no progress data" });
  }
  const sessionIds = positionals.filter(Boolean);
  const result = await api.post("/api/sessions/outlines", sessionIds.length ? { sessionIds } : {});
  if (flags.json) return rawJson(result);
  const cli = cliInvocation();
  return renderOutput2([
    renderObject(result ?? { status: "queued" }),
    renderHelp([`Run \`${cli} outlines progress\` to watch generation`])
  ]);
}
var SYNC_HELP = `sessions-axi sync [--force] [--json]

  Trigger an immediate sync of local (~/.claude) sessions. --force re-parses all
  sessions even when the content hash is unchanged (use after a parser upgrade).`;
async function syncCommand(args) {
  const { flags } = parseArgs(args, ["json", "force"]);
  const result = await api.post("/api/sessions/sync", void 0, flags.force ? { force: "true" } : void 0);
  if (flags.json) return rawJson(result);
  return renderObject(result ?? { status: "done" });
}
var SHARE_HELP = `sessions-axi share <session-id> [--json]

  Mint a shareable auth code granting read access to a session's transcript.`;
async function shareCommand(args) {
  const { positionals, flags } = parseArgs(args, ["json"]);
  const id = requirePositional(positionals, 0, "session id", SHARE_HELP);
  const result = await api.post(`/api/sessions/${encodeURIComponent(id)}/share`);
  if (flags.json) return rawJson(result);
  return renderObject({ session: id, auth_code: result?.auth_code ?? null });
}

// packages/sessions/src/axi/cli.ts
var VERSION = true ? "2163176" : "dev";
var CLI = cliInvocation();
var TOP_HELP = `usage: ${CLI} [command] [args] [flags]
       ${CLI}                 # no args \u2192 home (recent activity + next steps)

commands:

${commandReferenceText()}

flags: --help, -v/--version, --json (raw output on most commands)

env: CLAUDE_ASSIST_SERVER (default http://localhost:2529)

examples:
  ${CLI}
  ${CLI} transcript --after 2026-06-22T00:00:00Z --before 2026-06-23T00:00:00Z
  ${CLI} search --query "auth refactor" --project claude-assist --min-user-messages 2
  ${CLI} search --tools mcp__plugin_slack --files-written routes.ts
  ${CLI} stats --days 7
`;
var HOME_HELP = `sessions-axi [home] [--all] [--project NAME] [--recent N] [--json]

  The no-arg view. Inside a git repo it leads with that repo's most recent
  sessions (ordered by last activity); otherwise it lists registered machines.

  --all            force the cross-project (machines) view even inside a repo
  --project NAME   override repo detection with an explicit project substring
  --recent N       how many recent sessions to show (default 5)
  --json           raw JSON`;
var COMMAND_HELP = {
  home: HOME_HELP,
  search: SEARCH_HELP,
  grep: GREP_HELP,
  transcript: TRANSCRIPT_HELP,
  details: DETAILS_HELP,
  activity: ACTIVITY_HELP,
  stats: STATS_HELP,
  machines: MACHINES_HELP,
  outlines: OUTLINES_HELP,
  sync: SYNC_HELP,
  share: SHARE_HELP
};
var COMMANDS = {
  // Also exposed as a command so its flags can be passed (the bare invocation
  // hits the same handler via the `home` option below, but the SDK rejects
  // flags that precede a command).
  home: homeCommand,
  search: searchCommand,
  grep: grepCommand,
  transcript: transcriptCommand,
  details: detailsCommand,
  activity: activityCommand,
  stats: statsCommand,
  machines: machinesCommand,
  outlines: outlinesCommand,
  sync: syncCommand,
  share: shareCommand
};
async function main(argv) {
  await runAxiCli({
    description: DESCRIPTION,
    version: VERSION,
    ...argv ? { argv } : {},
    topLevelHelp: TOP_HELP,
    home: homeCommand,
    commands: COMMANDS,
    getCommandHelp: (command) => COMMAND_HELP[command]
  });
}

// packages/sessions/src/axi/bin.ts
await main();
