#!/usr/bin/env node
// GENERATED by scripts/build-cli.ts from src/axi/ — do not edit. Run `bun run build:cli`.

// node_modules/.bun/axi-sdk-js@0.1.7/node_modules/axi-sdk-js/dist/cli.js
import { basename } from "node:path";

// node_modules/.bun/axi-sdk-js@0.1.7/node_modules/axi-sdk-js/dist/errors.js
var AxiError = class extends Error {
  code;
  suggestions;
  constructor(message, code, suggestions = []) {
    super(message);
    this.code = code;
    this.suggestions = suggestions;
    this.name = "AxiError";
  }
};
function exitCodeForError(error) {
  if (error instanceof AxiError && error.code === "VALIDATION_ERROR") {
    return 2;
  }
  return 1;
}

// node_modules/.bun/axi-sdk-js@0.1.7/node_modules/axi-sdk-js/dist/output.js
import { homedir } from "node:os";

// node_modules/.bun/@toon-format+toon@2.3.0/node_modules/@toon-format/toon/dist/index.mjs
var NULL_LITERAL = "null";
var DELIMITERS = {
  comma: ",",
  tab: "	",
  pipe: "|"
};
var DEFAULT_DELIMITER = DELIMITERS.comma;
function escapeString(value) {
  return value.replace(/\\/g, `\\\\`).replace(/"/g, `\\"`).replace(/\n/g, `\\n`).replace(/\r/g, `\\r`).replace(/\t/g, `\\t`).replace(/[\u0000-\u001F]/g, (c) => `\\u${c.charCodeAt(0).toString(16).padStart(4, "0")}`);
}
function isBooleanOrNullLiteral(token) {
  return token === "true" || token === "false" || token === "null";
}
function normalizeValue(value) {
  if (value === null) return null;
  if (typeof value === "object" && value !== null && "toJSON" in value && typeof value.toJSON === "function") {
    const next = value.toJSON();
    if (next !== value) return normalizeValue(next);
  }
  if (typeof value === "string" || typeof value === "boolean") return value;
  if (typeof value === "number") {
    if (Object.is(value, -0)) return 0;
    if (!Number.isFinite(value)) return null;
    return value;
  }
  if (typeof value === "bigint") {
    if (value >= Number.MIN_SAFE_INTEGER && value <= Number.MAX_SAFE_INTEGER) return Number(value);
    return value.toString();
  }
  if (value instanceof Date) return value.toISOString();
  if (Array.isArray(value)) return value.map(normalizeValue);
  if (value instanceof Set) return Array.from(value).map(normalizeValue);
  if (value instanceof Map) return Object.fromEntries(Array.from(value, ([k, v]) => [String(k), normalizeValue(v)]));
  if (isPlainObject(value)) {
    const encodedValues = {};
    for (const key in value) if (Object.hasOwn(value, key)) encodedValues[key] = normalizeValue(value[key]);
    return encodedValues;
  }
  return null;
}
function isJsonPrimitive(value) {
  return value === null || typeof value === "string" || typeof value === "number" || typeof value === "boolean";
}
function isJsonArray(value) {
  return Array.isArray(value);
}
function isJsonObject(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}
function isEmptyObject(value) {
  return Object.keys(value).length === 0;
}
function isPlainObject(value) {
  if (value === null || typeof value !== "object") return false;
  const prototype = Object.getPrototypeOf(value);
  return prototype === null || prototype === Object.prototype;
}
function isArrayOfPrimitives(value) {
  return value.length === 0 || value.every((item) => isJsonPrimitive(item));
}
function isArrayOfArrays(value) {
  return value.length === 0 || value.every((item) => isJsonArray(item));
}
function isArrayOfObjects(value) {
  return value.length === 0 || value.every((item) => isJsonObject(item));
}
var NUMERIC_LIKE_PATTERN = /^-?\d+(?:\.\d+)?(?:e[+-]?\d+)?$/i;
var LEADING_ZERO_PATTERN = /^0\d+$/;
function isValidUnquotedKey(key) {
  return /^[A-Z_][\w.]*$/i.test(key);
}
function isIdentifierSegment(key) {
  return /^[A-Z_]\w*$/i.test(key);
}
function isSafeUnquoted(value, delimiter = DEFAULT_DELIMITER) {
  if (!value) return false;
  if (value !== value.trim()) return false;
  if (isBooleanOrNullLiteral(value) || isNumericLike(value)) return false;
  if (value.includes(":")) return false;
  if (value.includes('"') || value.includes("\\")) return false;
  if (/[[\]{}]/.test(value)) return false;
  if (/[\u0000-\u001F]/.test(value)) return false;
  if (value.includes(delimiter)) return false;
  if (value.startsWith("-")) return false;
  return true;
}
function isNumericLike(value) {
  return NUMERIC_LIKE_PATTERN.test(value) || LEADING_ZERO_PATTERN.test(value);
}
function tryFoldKeyChain(key, value, siblings, options, rootLiteralKeys, pathPrefix, flattenDepth) {
  if (options.keyFolding !== "safe") return;
  if (!isJsonObject(value)) return;
  const { segments, tail, leafValue } = collectSingleKeyChain(key, value, flattenDepth ?? options.flattenDepth);
  if (segments.length < 2) return;
  if (!segments.every((seg) => isIdentifierSegment(seg))) return;
  const foldedKey = buildFoldedKey(segments);
  const absolutePath = pathPrefix ? `${pathPrefix}.${foldedKey}` : foldedKey;
  if (siblings.includes(foldedKey)) return;
  if (rootLiteralKeys && rootLiteralKeys.has(absolutePath)) return;
  return {
    foldedKey,
    remainder: tail,
    leafValue,
    segmentCount: segments.length
  };
}
function collectSingleKeyChain(startKey, startValue, maxDepth) {
  const segments = [startKey];
  let currentValue = startValue;
  while (segments.length < maxDepth) {
    if (!isJsonObject(currentValue)) break;
    const keys = Object.keys(currentValue);
    if (keys.length !== 1) break;
    const nextKey = keys[0];
    const nextValue = currentValue[nextKey];
    segments.push(nextKey);
    currentValue = nextValue;
  }
  if (!isJsonObject(currentValue) || isEmptyObject(currentValue)) return {
    segments,
    tail: void 0,
    leafValue: currentValue
  };
  return {
    segments,
    tail: currentValue,
    leafValue: currentValue
  };
}
function buildFoldedKey(segments) {
  return segments.join(".");
}
function encodePrimitive(value, delimiter) {
  if (value === null) return NULL_LITERAL;
  if (typeof value === "boolean") return String(value);
  if (typeof value === "number") return String(value);
  return encodeStringLiteral(value, delimiter);
}
function encodeStringLiteral(value, delimiter = DEFAULT_DELIMITER) {
  if (isSafeUnquoted(value, delimiter)) return value;
  return `"${escapeString(value)}"`;
}
function encodeKey(key) {
  if (isValidUnquotedKey(key)) return key;
  return `"${escapeString(key)}"`;
}
function encodeAndJoinPrimitives(values, delimiter = DEFAULT_DELIMITER) {
  return values.map((v) => encodePrimitive(v, delimiter)).join(delimiter);
}
function formatHeader(length, options) {
  const key = options?.key;
  const fields = options?.fields;
  const delimiter = options?.delimiter ?? ",";
  let header = "";
  if (key != null) header += encodeKey(key);
  header += `[${length}${delimiter !== DEFAULT_DELIMITER ? delimiter : ""}]`;
  if (fields) {
    const quotedFields = fields.map((f) => encodeKey(f));
    header += `{${quotedFields.join(delimiter)}}`;
  }
  header += ":";
  return header;
}
function* encodeJsonValue(value, options, depth) {
  if (isJsonPrimitive(value)) {
    const encodedPrimitive = encodePrimitive(value, options.delimiter);
    if (encodedPrimitive !== "") yield encodedPrimitive;
    return;
  }
  if (isJsonArray(value)) yield* encodeArrayLines(void 0, value, depth, options);
  else if (isJsonObject(value)) yield* encodeObjectLines(value, depth, options);
}
function* encodeObjectLines(value, depth, options, rootLiteralKeys, pathPrefix, remainingDepth) {
  const keys = Object.keys(value);
  if (depth === 0 && !rootLiteralKeys) rootLiteralKeys = new Set(keys.filter((k) => k.includes(".")));
  const effectiveFlattenDepth = remainingDepth ?? options.flattenDepth;
  for (const [key, val] of Object.entries(value)) yield* encodeKeyValuePairLines(key, val, depth, options, keys, rootLiteralKeys, pathPrefix, effectiveFlattenDepth);
}
function* encodeKeyValuePairLines(key, value, depth, options, siblings, rootLiteralKeys, pathPrefix, flattenDepth) {
  const currentPath = pathPrefix ? `${pathPrefix}.${key}` : key;
  const effectiveFlattenDepth = flattenDepth ?? options.flattenDepth;
  if (options.keyFolding === "safe" && siblings) {
    const foldResult = tryFoldKeyChain(key, value, siblings, options, rootLiteralKeys, pathPrefix, effectiveFlattenDepth);
    if (foldResult) {
      const { foldedKey, remainder, leafValue, segmentCount } = foldResult;
      const encodedFoldedKey = encodeKey(foldedKey);
      if (remainder === void 0) {
        if (isJsonPrimitive(leafValue)) {
          yield indentedLine(depth, `${encodedFoldedKey}: ${encodePrimitive(leafValue, options.delimiter)}`, options.indent);
          return;
        } else if (isJsonArray(leafValue)) {
          yield* encodeArrayLines(foldedKey, leafValue, depth, options);
          return;
        } else if (isJsonObject(leafValue) && isEmptyObject(leafValue)) {
          yield indentedLine(depth, `${encodedFoldedKey}:`, options.indent);
          return;
        }
      }
      if (isJsonObject(remainder)) {
        yield indentedLine(depth, `${encodedFoldedKey}:`, options.indent);
        const remainingDepth = effectiveFlattenDepth - segmentCount;
        const foldedPath = pathPrefix ? `${pathPrefix}.${foldedKey}` : foldedKey;
        yield* encodeObjectLines(remainder, depth + 1, options, rootLiteralKeys, foldedPath, remainingDepth);
        return;
      }
    }
  }
  const encodedKey = encodeKey(key);
  if (isJsonPrimitive(value)) yield indentedLine(depth, `${encodedKey}: ${encodePrimitive(value, options.delimiter)}`, options.indent);
  else if (isJsonArray(value)) yield* encodeArrayLines(key, value, depth, options);
  else if (isJsonObject(value)) {
    yield indentedLine(depth, `${encodedKey}:`, options.indent);
    if (!isEmptyObject(value)) yield* encodeObjectLines(value, depth + 1, options, rootLiteralKeys, currentPath, effectiveFlattenDepth);
  }
}
function* encodeArrayLines(key, value, depth, options) {
  if (value.length === 0) {
    yield indentedLine(depth, key != null ? `${encodeKey(key)}: []` : "[]", options.indent);
    return;
  }
  if (isArrayOfPrimitives(value)) {
    yield indentedLine(depth, encodeInlineArrayLine(value, options.delimiter, key), options.indent);
    return;
  }
  if (isArrayOfArrays(value)) {
    if (value.every((arr) => isArrayOfPrimitives(arr))) {
      yield* encodeArrayOfArraysAsListItemsLines(key, value, depth, options);
      return;
    }
  }
  if (isArrayOfObjects(value)) {
    const header = extractTabularHeader(value);
    if (header) yield* encodeArrayOfObjectsAsTabularLines(key, value, header, depth, options);
    else yield* encodeMixedArrayAsListItemsLines(key, value, depth, options);
    return;
  }
  yield* encodeMixedArrayAsListItemsLines(key, value, depth, options);
}
function* encodeArrayOfArraysAsListItemsLines(prefix, values, depth, options) {
  yield indentedLine(depth, formatHeader(values.length, {
    key: prefix,
    delimiter: options.delimiter
  }), options.indent);
  for (const arr of values) if (isArrayOfPrimitives(arr)) {
    const arrayLine = encodeInlineArrayLine(arr, options.delimiter);
    yield indentedListItem(depth + 1, arrayLine, options.indent);
  }
}
function encodeInlineArrayLine(values, delimiter, prefix) {
  const header = formatHeader(values.length, {
    key: prefix,
    delimiter
  });
  const joinedValue = encodeAndJoinPrimitives(values, delimiter);
  if (values.length === 0) return header;
  return `${header} ${joinedValue}`;
}
function* encodeArrayOfObjectsAsTabularLines(prefix, rows, header, depth, options) {
  yield indentedLine(depth, formatHeader(rows.length, {
    key: prefix,
    fields: header,
    delimiter: options.delimiter
  }), options.indent);
  yield* writeTabularRowsLines(rows, header, depth + 1, options);
}
function extractTabularHeader(rows) {
  if (rows.length === 0) return;
  const firstRow = rows[0];
  const firstKeys = Object.keys(firstRow);
  if (firstKeys.length === 0) return;
  if (isTabularArray(rows, firstKeys)) return firstKeys;
}
function isTabularArray(rows, header) {
  for (const row of rows) {
    if (Object.keys(row).length !== header.length) return false;
    for (const key of header) {
      if (!(key in row)) return false;
      if (!isJsonPrimitive(row[key])) return false;
    }
  }
  return true;
}
function* writeTabularRowsLines(rows, header, depth, options) {
  for (const row of rows) yield indentedLine(depth, encodeAndJoinPrimitives(header.map((key) => row[key]), options.delimiter), options.indent);
}
function* encodeMixedArrayAsListItemsLines(prefix, items, depth, options) {
  yield indentedLine(depth, formatHeader(items.length, {
    key: prefix,
    delimiter: options.delimiter
  }), options.indent);
  for (const item of items) yield* encodeListItemValueLines(item, depth + 1, options);
}
function* encodeObjectAsListItemLines(obj, depth, options) {
  if (isEmptyObject(obj)) {
    yield indentedLine(depth, "-", options.indent);
    return;
  }
  const entries = Object.entries(obj);
  const [firstKey, firstValue] = entries[0];
  const restEntries = entries.slice(1);
  if (isJsonArray(firstValue) && isArrayOfObjects(firstValue)) {
    const header = extractTabularHeader(firstValue);
    if (header) {
      yield indentedListItem(depth, formatHeader(firstValue.length, {
        key: firstKey,
        fields: header,
        delimiter: options.delimiter
      }), options.indent);
      yield* writeTabularRowsLines(firstValue, header, depth + 2, options);
      if (restEntries.length > 0) yield* encodeObjectLines(Object.fromEntries(restEntries), depth + 1, options);
      return;
    }
  }
  const encodedKey = encodeKey(firstKey);
  if (isJsonPrimitive(firstValue)) yield indentedListItem(depth, `${encodedKey}: ${encodePrimitive(firstValue, options.delimiter)}`, options.indent);
  else if (isJsonArray(firstValue)) if (firstValue.length === 0) yield indentedListItem(depth, `${encodedKey}: []`, options.indent);
  else if (isArrayOfPrimitives(firstValue)) yield indentedListItem(depth, `${encodedKey}${encodeInlineArrayLine(firstValue, options.delimiter)}`, options.indent);
  else {
    yield indentedListItem(depth, `${encodedKey}${formatHeader(firstValue.length, { delimiter: options.delimiter })}`, options.indent);
    for (const item of firstValue) yield* encodeListItemValueLines(item, depth + 2, options);
  }
  else if (isJsonObject(firstValue)) {
    yield indentedListItem(depth, `${encodedKey}:`, options.indent);
    if (!isEmptyObject(firstValue)) yield* encodeObjectLines(firstValue, depth + 2, options);
  }
  if (restEntries.length > 0) yield* encodeObjectLines(Object.fromEntries(restEntries), depth + 1, options);
}
function* encodeListItemValueLines(value, depth, options) {
  if (isJsonPrimitive(value)) yield indentedListItem(depth, encodePrimitive(value, options.delimiter), options.indent);
  else if (isJsonArray(value)) if (isArrayOfPrimitives(value)) yield indentedListItem(depth, encodeInlineArrayLine(value, options.delimiter), options.indent);
  else {
    yield indentedListItem(depth, formatHeader(value.length, { delimiter: options.delimiter }), options.indent);
    for (const item of value) yield* encodeListItemValueLines(item, depth + 1, options);
  }
  else if (isJsonObject(value)) yield* encodeObjectAsListItemLines(value, depth, options);
}
function indentedLine(depth, content, indentSize) {
  return " ".repeat(indentSize * depth) + content;
}
function indentedListItem(depth, content, indentSize) {
  return indentedLine(depth, "- " + content, indentSize);
}
function applyReplacer(root, replacer) {
  const replacedRoot = replacer("", root, []);
  if (replacedRoot === void 0) return transformChildren(root, replacer, []);
  return transformChildren(normalizeValue(replacedRoot), replacer, []);
}
function transformChildren(value, replacer, path) {
  if (isJsonObject(value)) return transformObject(value, replacer, path);
  if (isJsonArray(value)) return transformArray(value, replacer, path);
  return value;
}
function transformObject(obj, replacer, path) {
  const result = {};
  for (const [key, value] of Object.entries(obj)) {
    const childPath = [...path, key];
    const replacedValue = replacer(key, value, childPath);
    if (replacedValue === void 0) continue;
    result[key] = transformChildren(normalizeValue(replacedValue), replacer, childPath);
  }
  return result;
}
function transformArray(arr, replacer, path) {
  const result = [];
  for (let i = 0; i < arr.length; i++) {
    const value = arr[i];
    const childPath = [...path, i];
    const replacedValue = replacer(String(i), value, childPath);
    if (replacedValue === void 0) continue;
    const normalizedValue = normalizeValue(replacedValue);
    result.push(transformChildren(normalizedValue, replacer, childPath));
  }
  return result;
}
function encode(input, options) {
  return Array.from(encodeLines(input, options)).join("\n");
}
function encodeLines(input, options) {
  const normalizedValue = normalizeValue(input);
  const resolvedOptions = resolveOptions(options);
  return encodeJsonValue(resolvedOptions.replacer ? applyReplacer(normalizedValue, resolvedOptions.replacer) : normalizedValue, resolvedOptions, 0);
}
function resolveOptions(options) {
  return {
    indent: options?.indent ?? 2,
    delimiter: options?.delimiter ?? DEFAULT_DELIMITER,
    keyFolding: options?.keyFolding ?? "off",
    flattenDepth: options?.flattenDepth ?? Number.POSITIVE_INFINITY,
    replacer: options?.replacer
  };
}

// node_modules/.bun/axi-sdk-js@0.1.7/node_modules/axi-sdk-js/dist/output.js
function collapseHomeDirectory(path, homeDir = homedir()) {
  if (!path.startsWith(homeDir)) {
    return path;
  }
  return `~${path.slice(homeDir.length)}`;
}
function homeHeaderOutput(options) {
  return {
    bin: collapseHomeDirectory(options.execPath ?? process.argv[1] ?? "", options.homeDir),
    description: options.description
  };
}
function errorOutput(message, code, suggestions = []) {
  const output = {
    error: message,
    code
  };
  if (suggestions.length > 0) {
    output.help = suggestions;
  }
  return output;
}
function renderOutput(output) {
  if (typeof output === "string") {
    return output;
  }
  return encode(output);
}
function renderError(message, code, suggestions = []) {
  return renderOutput(errorOutput(message, code, suggestions));
}

// node_modules/.bun/axi-sdk-js@0.1.7/node_modules/axi-sdk-js/dist/cli.js
function defaultFormatError(error) {
  if (error instanceof AxiError) {
    return {
      output: `${renderError(error.message, error.code, error.suggestions)}
`,
      exitCode: exitCodeForError(error)
    };
  }
  const message = error instanceof Error ? error.message : String(error);
  return {
    output: `${renderError(message, "UNKNOWN")}
`,
    exitCode: 1
  };
}
function defaultUnknownCommand(command) {
  return `${renderError(`Unknown command: ${command}`, "VALIDATION_ERROR", [
    "Run `--help` to see available commands"
  ])}
`;
}
async function runAxiCli(options) {
  options.initialize?.();
  const stdout = options.stdout ?? process.stdout;
  const argv = options.argv ?? process.argv.slice(2);
  if (argv.length === 1 && argv[0] === "--help") {
    stdout.write(options.topLevelHelp);
    return;
  }
  if (argv.length === 1 && isVersionFlag(argv[0])) {
    if (!options.version) {
      stdout.write(`${renderError("Version is not configured for this tool", "VALIDATION_ERROR")}
`);
      process.exitCode = 2;
      return;
    }
    stdout.write(`${options.version}
`);
    return;
  }
  const command = argv[0];
  if (!command) {
    const context2 = await options.resolveContext?.({
      command: void 0,
      args: []
    });
    await runHandler(options.home, [], context2, stdout, options, true);
    return;
  }
  if (command.startsWith("-")) {
    stdout.write(renderLeadingFlagError(command));
    process.exitCode = 2;
    return;
  }
  const args = argv.slice(1);
  if (args.includes("--help")) {
    const help = options.getCommandHelp?.(command);
    if (help) {
      stdout.write(help);
      return;
    }
  }
  const handler = options.commands[command];
  if (!handler) {
    stdout.write((options.renderUnknownCommand ?? defaultUnknownCommand)(command));
    process.exitCode = 2;
    return;
  }
  const context = await options.resolveContext?.({ command, args });
  await runHandler(handler, args, context, stdout, options, false);
}
async function runHandler(handler, args, context, stdout, options, isHomeView) {
  try {
    const output = await handler(args, context);
    stdout.write(`${renderCommandOutput(output, options, isHomeView)}
`);
  } catch (error) {
    const formatted = (options.formatError ?? defaultFormatError)(error);
    stdout.write(formatted.output);
    process.exitCode = formatted.exitCode;
  }
}
function renderLeadingFlagError(flag) {
  const bin = basename(process.argv[1] ?? "tool") || "tool";
  return `${renderError("Flags must come after the command", "VALIDATION_ERROR", [
    `Run \`${bin} <command> [args] [flags]\``,
    `Move \`${flag}\` after the command instead of before it`
  ])}
`;
}
function isVersionFlag(flag) {
  return flag === "-v" || flag === "-V" || flag === "--version";
}
function renderCommandOutput(output, options, isHomeView) {
  if (!isHomeView) {
    return renderOutput(output);
  }
  const header = homeHeaderOutput({ description: options.description });
  if (typeof output === "string") {
    return `${renderOutput(header)}
${output}`;
  }
  return renderOutput(mergeHomeHeader(header, output));
}
function mergeHomeHeader(header, output) {
  const rest = { ...output };
  delete rest.bin;
  delete rest.description;
  return {
    ...header,
    ...rest
  };
}

// packages/google/src/axi/gmail/reference.ts
var DESCRIPTION = "Manage Gmail sync, triage, and actions \u2014 search the inbox, check triage progress, trigger sync/triage, review per-message AI analysis, preview the daily digest, and confirm-to-execute staged label/archive/spam actions.";
var COMMAND_GROUPS = [
  {
    group: "Inbox",
    commands: [
      {
        usage: "emails [--account ID] [--status discovered|new|triaged] [--type a,b] [--search TEXT] [--with NAME] [--days N] [--limit N] [--offset N]",
        summary: "search/filter emails (most recent first); --type matches analysis message_type, --with matches from/to"
      },
      { usage: "email <id>", summary: "full detail for one email including its AI analysis" },
      { usage: "stats [--account ID] [--days N]", summary: "counts by workflow status, message type, and sender type" }
    ]
  },
  {
    group: "Pipeline",
    commands: [
      { usage: "sync [--account ID] [--full]", summary: "trigger Gmail sync (async; --full re-reads history). Watch via accounts" },
      { usage: "triage [<email-id>] [--account ID] [--limit N] [--force]", summary: "triage one email (id) or a batch of pending ones (needs ANTHROPIC_API_KEY)" },
      { usage: "triage progress", summary: "discovered/new/triaged/error counts for the last 7 days" },
      { usage: "bulk-action <action> <email-id>...", summary: "run a bulk action over emails (e.g. force-retriage)" }
    ]
  },
  {
    group: "Actions",
    commands: [
      { usage: "digest", summary: "preview the daily confirm-to-execute digest (staged actions grouped by section)" },
      { usage: "execute <email-id>... [--no-labels] [--no-actions]", summary: "apply staged plans: AI/* + TODO/* labels and archive/spam moves (deterministic; spam is quarantined, never deleted)" }
    ]
  }
];
function commandReferenceText() {
  return COMMAND_GROUPS.map((g) => {
    const items = g.commands.map((c) => `  ${c.usage}
      ${c.summary}`).join("\n");
    return `${g.group}:
${items}`;
  }).join("\n\n");
}
function discoveryHelp(invocation) {
  return `Run \`${invocation} --help\` for the full command list, or \`${invocation} <command> --help\` for usage on any command`;
}

// packages/google/src/axi/invocation.ts
import { accessSync, constants } from "node:fs";
import { homedir as homedir2 } from "node:os";
import { fileURLToPath } from "node:url";
var cached;
function cliInvocation() {
  if (cached) return cached;
  let bundle;
  try {
    bundle = fileURLToPath(import.meta.url);
  } catch {
    bundle = process.argv[1] ?? "google-axi";
  }
  const shim = bundle.replace(/\.mjs$/, "");
  try {
    if (shim !== bundle) {
      accessSync(shim, constants.X_OK);
      cached = quote(collapseHome(shim));
      return cached;
    }
  } catch {
  }
  cached = `node ${quote(collapseHome(bundle))}`;
  return cached;
}
function collapseHome(p) {
  const home = homedir2();
  return home && p.startsWith(`${home}/`) ? `~${p.slice(home.length)}` : p;
}
function quote(p) {
  return /\s/.test(p) ? `"${p}"` : p;
}

// packages/google/src/axi/client.ts
var DEFAULT_SERVER = "http://localhost:2529";
function resolveServer() {
  const env = process.env.CLAUDE_ASSIST_SERVER?.trim();
  return (env || DEFAULT_SERVER).replace(/\/+$/, "");
}
function buildUrl(server, path, query) {
  let url = `${server}${path}`;
  if (query) {
    const qs = new URLSearchParams();
    for (const [k, v] of Object.entries(query)) {
      if (v === void 0 || v === null || v === "") continue;
      if (Array.isArray(v)) {
        for (const item of v) if (item !== void 0 && item !== null && item !== "") qs.append(k, String(item));
      } else {
        qs.append(k, String(v));
      }
    }
    const s = qs.toString();
    if (s) url += `?${s}`;
  }
  return url;
}
function suggestForStatus(status) {
  if (status === 404) return ["Check the id \u2014 try `search` to look one up"];
  if (status === 400) return ["Check required params and value formats for this command"];
  if (status === 503) return ["The server is up but this feature may be disabled (e.g. ANTHROPIC_API_KEY not set)"];
  return [];
}
async function send(method, path, opts = {}) {
  const server = resolveServer();
  const url = buildUrl(server, path, opts.query);
  const hasBody = opts.body !== void 0 && opts.body !== null;
  const init = { method, headers: hasBody ? { "Content-Type": "application/json" } : {} };
  if (hasBody) init.body = JSON.stringify(opts.body);
  let res;
  try {
    res = await fetch(url, init);
  } catch (err) {
    throw new AxiError(
      `Cannot reach claude-assist server at ${server} (${err.message})`,
      "HTTP_ERROR",
      ["Set CLAUDE_ASSIST_SERVER or start the server (cd apps/server && docker-compose up -d)"]
    );
  }
  return res;
}
async function parseError(res) {
  const text = await res.text();
  let message = res.statusText || `HTTP ${res.status}`;
  if (text) {
    try {
      const data = JSON.parse(text);
      if (data && typeof data === "object" && data.error) message = data.error;
      else if (data && typeof data === "object" && data.message) message = data.message;
    } catch {
      message = text.slice(0, 200);
    }
  }
  throw new AxiError(`API error (${res.status}): ${message}`, "HTTP_ERROR", suggestForStatus(res.status));
}
var api = {
  async get(path, query) {
    const res = await send("GET", path, { query });
    if (!res.ok) await parseError(res);
    const text = await res.text();
    if (!text) return null;
    try {
      return JSON.parse(text);
    } catch {
      return text;
    }
  },
  /** GET an endpoint that returns text/plain (e.g. transcripts). */
  async getText(path, query) {
    const res = await send("GET", path, { query });
    if (!res.ok) await parseError(res);
    return res.text();
  },
  async post(path, body, query) {
    return mutate("POST", path, body, query);
  },
  async patch(path, body) {
    return mutate("PATCH", path, body);
  },
  async del(path) {
    return mutate("DELETE", path);
  }
};
async function mutate(method, path, body, query) {
  const res = await send(method, path, { body, query });
  if (!res.ok) await parseError(res);
  const text = await res.text();
  if (!text) return null;
  try {
    return JSON.parse(text);
  } catch {
    return text;
  }
}

// packages/google/src/axi/args.ts
function parseArgs(args, booleanFlags = []) {
  const positionals = [];
  const flags = {};
  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg.startsWith("--")) {
      const name = arg.slice(2);
      if (booleanFlags.includes(name)) {
        flags[name] = true;
      } else {
        const value = args[++i];
        if (value === void 0) {
          throw new AxiError(`Flag --${name} requires a value`, "VALIDATION_ERROR");
        }
        flags[name] = value;
      }
    } else {
      positionals.push(arg);
    }
  }
  return { positionals, flags };
}
function requirePositional(positionals, index, label, usage) {
  const v = positionals[index];
  if (!v) throw new AxiError(`${label} is required`, "VALIDATION_ERROR", [usage]);
  return v;
}
function rawJson(data) {
  return JSON.stringify(data, null, 2);
}

// packages/google/src/axi/toon.ts
function field(key, as) {
  return { type: "field", key, as };
}
function relativeTime(key, as) {
  return { type: "relativeTime", key, as };
}
function truncate(key, limit, as) {
  return { type: "truncate", key, limit, as };
}
function custom(as, fn) {
  return { type: "custom", as, fn };
}
function outputKey(def) {
  if (def.type === "custom") return def.as;
  return def.as ?? def.key;
}
function extract(item, schema) {
  const result = {};
  for (const def of schema) {
    const key = outputKey(def);
    switch (def.type) {
      case "field":
        result[key] = item[def.key] ?? null;
        break;
      case "pluck":
        result[key] = item[def.key]?.[def.subkey] ?? null;
        break;
      case "joinArray": {
        const arr = item[def.key];
        if (Array.isArray(arr) && arr.length > 0) {
          result[key] = arr.map(
            (x) => def.subkey && x && typeof x === "object" ? x[def.subkey] : x
          ).join(",");
        } else {
          result[key] = def.empty ?? "none";
        }
        break;
      }
      case "count": {
        const arr = item[def.key];
        result[key] = Array.isArray(arr) ? arr.length : 0;
        break;
      }
      case "relativeTime":
        result[key] = formatRelativeTime(item[def.key]);
        break;
      case "dateOnly":
        result[key] = formatDateOnly(item[def.key]);
        break;
      case "boolYesNo":
        result[key] = item[def.key] ? "yes" : "no";
        break;
      case "truncate":
        result[key] = truncateText(item[def.key], def.limit).value;
        break;
      case "custom":
        result[key] = def.fn(item);
        break;
    }
  }
  return result;
}
function renderList(label, items, schema) {
  return encode({ [label]: items.map((item) => extract(item, schema)) });
}
function renderDetail(label, item, schema) {
  return encode({ [label]: extract(item, schema) });
}
function renderObject(obj) {
  return encode(obj);
}
function renderHelp(lines) {
  const clean = lines.filter(Boolean);
  if (clean.length === 0) return "";
  return `help[${clean.length}]:
${clean.map((l) => `  ${l}`).join("\n")}`;
}
function renderOutput2(blocks) {
  return blocks.filter(Boolean).join("\n");
}
var DEFAULT_TRUNCATE = 280;
function truncateText(text, limit = DEFAULT_TRUNCATE) {
  if (typeof text !== "string") return { value: text ?? null, truncated: false, total: 0 };
  if (text.length <= limit) return { value: text, truncated: false, total: text.length };
  return {
    value: `${text.slice(0, limit)}\u2026 (truncated, ${text.length} chars total)`,
    truncated: true,
    total: text.length
  };
}
function formatDateOnly(value) {
  if (!value) return null;
  const d = new Date(value);
  if (isNaN(d.getTime())) return String(value);
  return d.toISOString().slice(0, 10);
}
function formatRelativeTime(value) {
  if (!value) return "unknown";
  const then = new Date(value).getTime();
  if (isNaN(then)) return "unknown";
  const diffSec = Math.floor((Date.now() - then) / 1e3);
  const past = diffSec >= 0;
  const s = Math.abs(diffSec);
  const fmt = (n, unit) => past ? `${n}${unit} ago` : `in ${n}${unit}`;
  if (s < 60) return past ? "just now" : "soon";
  const min = Math.floor(s / 60);
  if (min < 60) return fmt(min, "m");
  const hr = Math.floor(min / 60);
  if (hr < 24) return fmt(hr, "h");
  const day = Math.floor(hr / 24);
  if (day < 30) return fmt(day, "d");
  const mon = Math.floor(day / 30);
  if (mon < 12) return fmt(mon, "mo");
  return fmt(Math.floor(mon / 12), "y");
}

// packages/google/src/axi/gmail/commands/home.ts
var SCHEMA = [
  field("identifier", "account"),
  field("email"),
  { type: "boolYesNo", key: "has_credentials", as: "authed" },
  relativeTime("email_last_sync_at", "last_sync"),
  field("new_7d", "new"),
  field("triaged_7d", "triaged"),
  field("status")
];
function liveStatus(account) {
  if (account.email_sync_status?.syncing) return "syncing";
  if (account.email_triage_status?.triaging) return "triaging";
  return "idle";
}
async function homeCommand(args) {
  const { flags } = parseArgs(args, ["json"]);
  const server = resolveServer();
  const cli = cliInvocation();
  let rows = null;
  try {
    const accounts = await api.get("/api/google/accounts");
    const list = Array.isArray(accounts) ? accounts : [];
    const stats = await Promise.all(
      list.map(
        (a) => api.get("/api/google/emails/stats", { account: a.identifier, days: 7 }).catch(() => null)
      )
    );
    rows = list.map((a, i) => ({
      ...a,
      new_7d: stats[i]?.byStatus?.new ?? 0,
      triaged_7d: stats[i]?.byStatus?.triaged ?? 0,
      status: liveStatus(a)
    }));
  } catch {
    rows = null;
  }
  if (flags.json) return rawJson({ server, accounts: rows });
  const blocks = [renderObject({ server })];
  if (rows === null) {
    blocks.push("The server is not reachable. Set CLAUDE_ASSIST_SERVER or start it (cd apps/server && docker-compose up -d).");
  } else if (rows.length === 0) {
    blocks.push("accounts: none configured \u2014 set one up with `google-axi account create`");
  } else {
    blocks.push(renderList("accounts", rows, SCHEMA));
  }
  blocks.push(
    renderHelp([
      `Run \`${cli} emails --status new\` to see untriaged email`,
      `Run \`${cli} triage\` to triage pending email, then \`${cli} triage progress\``,
      `Run \`${cli} sync\` to pull new mail; manage accounts with \`google-axi accounts\``,
      discoveryHelp(cli)
    ])
  );
  return renderOutput2(blocks);
}

// packages/google/src/axi/gmail/commands/emails.ts
var EMAILS_HELP = `gmail-axi emails [flags]

  Search and filter synced emails, most recent first.

  --account ID      filter to one account (its identifier, e.g. owner)
  --status STATUS   workflow status: discovered | new | triaged
  --type a,b        analysis message_type(s), comma-separated (e.g. newsletter,alert)
  --search TEXT     full-text search over subject/body
  --with NAME       match a participant in from/to (substring)
  --days N          look back N days (default 30)
  --limit N         max results (default 50, max 500)
  --offset N        pagination offset
  --json            raw API JSON`;
var LIST_SCHEMA = [
  field("id"),
  relativeTime("date"),
  custom("from", (e) => e.from_name || e.from_address || "\u2014"),
  truncate("subject", 80),
  custom("type", (e) => e.analysis?.message_type ?? "\u2014"),
  field("workflow_status", "status"),
  field("account_identifier", "account")
];
async function emailsCommand(args) {
  const { flags } = parseArgs(args, ["json"]);
  const query = {};
  if (typeof flags.account === "string") query.account = flags.account;
  if (typeof flags.status === "string") query.workflow_status = flags.status;
  if (typeof flags.type === "string") query.message_type = flags.type;
  if (typeof flags.search === "string") query.search = flags.search;
  if (typeof flags.with === "string") query.with = flags.with;
  if (typeof flags.days === "string") query.days = flags.days;
  if (typeof flags.limit === "string") query.limit = flags.limit;
  if (typeof flags.offset === "string") query.offset = flags.offset;
  const rows = await api.get("/api/google/emails", query);
  if (flags.json) return rawJson(rows);
  if (!Array.isArray(rows) || rows.length === 0) return "emails: 0 matching emails found";
  const cli = cliInvocation();
  return renderOutput2([
    `count: ${rows.length}`,
    renderList("emails", rows, LIST_SCHEMA),
    renderHelp([`Run \`${cli} email <id>\` for full detail and AI analysis`])
  ]);
}
var DETAIL_SCHEMA = [
  field("id"),
  field("date"),
  custom("from", (e) => `${e.from_name ?? ""} <${e.from_address ?? ""}>`.trim()),
  custom("to", (e) => Array.isArray(e.to_addresses) ? e.to_addresses.join(", ") : e.to_addresses ?? "\u2014"),
  field("subject"),
  truncate("snippet", 500),
  field("workflow_status", "status"),
  field("triaged_at"),
  field("account_identifier", "account"),
  custom("message_type", (e) => e.analysis?.message_type ?? null),
  custom("sender_type", (e) => e.analysis?.sender_type ?? null)
];
async function emailCommand(args) {
  const { positionals, flags } = parseArgs(args, ["json"]);
  const id = requirePositional(positionals, 0, "email id", "gmail-axi email <id>");
  const email = await api.get(`/api/google/emails/${encodeURIComponent(id)}`);
  if (flags.json) return rawJson(email);
  return renderOutput2([
    renderDetail("email", email, DETAIL_SCHEMA),
    email.analysis ? rawJson({ analysis: email.analysis }) : ""
  ]);
}

// packages/google/src/axi/gmail/commands/stats.ts
var STATS_HELP = `gmail-axi stats [--account ID] [--days N] [--json]

  Email counts over the last N days (default 7), broken down by workflow status,
  analysis message type, and sender type.`;
async function statsCommand(args) {
  const { flags } = parseArgs(args, ["json"]);
  const stats = await api.get("/api/google/emails/stats", {
    account: typeof flags.account === "string" ? flags.account : void 0,
    days: typeof flags.days === "string" ? flags.days : void 0
  });
  if (flags.json) return rawJson(stats);
  return renderOutput2([
    renderObject({ days: stats.days }),
    renderObject({ by_status: stats.byStatus ?? {} }),
    renderObject({ by_message_type: stats.byMessageType ?? {} }),
    renderObject({ by_sender_type: stats.bySenderType ?? {} })
  ]);
}

// packages/google/src/axi/gmail/commands/pipeline.ts
var SYNC_HELP = `gmail-axi sync [--account ID] [--full] [--json]

  Trigger a Gmail sync (async \u2014 returns immediately). Without --account, syncs
  every account with stored credentials. --full re-reads full history instead of
  incremental. Watch progress via \`google-axi accounts\`.`;
async function syncCommand(args) {
  const { flags } = parseArgs(args, ["json", "full"]);
  const body = {};
  if (typeof flags.account === "string") body.account = flags.account;
  if (flags.full) body.full = true;
  const result = await api.post("/api/google/emails/sync", body);
  if (flags.json) return rawJson(result);
  return renderObject(result ?? { status: "requested" });
}
var TRIAGE_HELP = `gmail-axi triage [<email-id>] [--account ID] [--limit N] [--force] [--json]
gmail-axi triage progress [--json]

  With an <email-id>, triage that single email synchronously. With no id, kick
  off an async batch over pending ('new') emails \u2014 or 'new'+'triaged' with
  --force. \`triage progress\` reports recent counts. Needs ANTHROPIC_API_KEY.`;
async function triageCommand(args) {
  const { positionals, flags } = parseArgs(args, ["json", "force"]);
  if (positionals[0] === "progress") {
    const progress = await api.get("/api/google/emails/triage/progress");
    if (flags.json) return rawJson(progress);
    return renderObject(progress ?? {});
  }
  const cli = cliInvocation();
  if (positionals[0]) {
    const id = positionals[0];
    const result2 = await api.post(`/api/google/emails/${encodeURIComponent(id)}/triage`);
    if (flags.json) return rawJson(result2);
    return renderObject(result2 ?? { triaged: id });
  }
  const body = {};
  if (typeof flags.account === "string") body.account = flags.account;
  if (typeof flags.limit === "string") body.limit = parseInt(flags.limit, 10);
  if (flags.force) body.force = true;
  const result = await api.post("/api/google/emails/triage", body);
  if (flags.json) return rawJson(result);
  return renderOutput2([
    renderObject(result ?? { status: "started" }),
    renderHelp([`Run \`${cli} triage progress\` to watch`])
  ]);
}
var BULK_ACTION_HELP = `gmail-axi bulk-action <action> <email-id>... [--json]

  Run a bulk action over a list of email ids. Supported: force-retriage
  (re-runs AI triage). Other actions are accepted as no-op placeholders.`;
async function bulkActionCommand(args) {
  const { positionals, flags } = parseArgs(args, ["json"]);
  const action = requirePositional(positionals, 0, "action", BULK_ACTION_HELP);
  const ids = positionals.slice(1).map((s) => parseInt(s, 10)).filter((n) => !Number.isNaN(n));
  if (ids.length === 0) {
    throw new AxiError("At least one email id is required", "VALIDATION_ERROR", [BULK_ACTION_HELP]);
  }
  const result = await api.post("/api/google/emails/bulk-action", { action, emailIds: ids });
  if (flags.json) return rawJson(result);
  return renderObject(result ?? { action, count: ids.length });
}

// packages/google/src/axi/gmail/commands/actions.ts
var EXECUTE_HELP = `gmail-axi execute <email-id>... [--no-labels] [--no-actions] [--json]

  Confirm-to-execute the staged triage plans for the given emails: apply the
  planned AI/* + TODO/* labels and any archive/spam move. Deterministic \u2014 no
  model call. Nothing is applied to Gmail until you run this.
    --no-labels   apply only the archive/spam move (skip label changes)
    --no-actions  apply only labels; leave the message where it is
  Spam moves the message to Gmail's Spam folder; it is never deleted.`;
async function executeCommand(args) {
  const { positionals, flags } = parseArgs(args, ["json", "no-labels", "no-actions"]);
  const ids = positionals.map((s) => parseInt(s, 10)).filter((n) => !Number.isNaN(n));
  if (ids.length === 0) {
    throw new AxiError("At least one email id is required", "VALIDATION_ERROR", [EXECUTE_HELP]);
  }
  const body = { email_ids: ids };
  if (flags["no-labels"]) body.apply_labels = false;
  if (flags["no-actions"]) body.apply_gmail_action = false;
  const result = await api.post("/api/google/emails/execute", body);
  if (flags.json) return rawJson(result);
  return renderObject(result ?? { requested: ids.length });
}
var DIGEST_HELP = `gmail-axi digest [--json]

  Preview the daily confirm-to-execute digest: triaged-but-unexecuted email
  grouped by section, each with its planned action, plus the email-id list you
  would hand to \`gmail-axi execute\`. Read-only \u2014 dispatching the digest to
  Slack runs on its own schedule.`;
async function digestCommand(args) {
  const { flags } = parseArgs(args, ["json"]);
  const result = await api.get("/api/google/emails/digest");
  if (flags.json) return rawJson(result);
  return renderObject(result ?? {});
}

// packages/google/src/axi/gmail/cli.ts
var VERSION = true ? "deb5d80" : "dev";
var CLI = cliInvocation();
var TOP_HELP = `usage: ${CLI} [command] [args] [flags]
       ${CLI}                 # no args \u2192 home (inbox pipeline + next steps)

commands:

${commandReferenceText()}

flags: --help, -v/--version, --json (raw output)

env: CLAUDE_ASSIST_SERVER (default http://localhost:2529)

examples:
  ${CLI}
  ${CLI} emails --status new --limit 20
  ${CLI} triage --limit 25
  ${CLI} email 12345
`;
var COMMAND_HELP = {
  emails: EMAILS_HELP,
  email: `gmail-axi email <id> [--json]

  Full detail for one email including its AI analysis.`,
  stats: STATS_HELP,
  sync: SYNC_HELP,
  triage: TRIAGE_HELP,
  "bulk-action": BULK_ACTION_HELP,
  execute: EXECUTE_HELP,
  digest: DIGEST_HELP
};
var COMMANDS = {
  emails: emailsCommand,
  email: emailCommand,
  stats: statsCommand,
  sync: syncCommand,
  triage: triageCommand,
  "bulk-action": bulkActionCommand,
  execute: executeCommand,
  digest: digestCommand
};
async function main(argv) {
  await runAxiCli({
    description: DESCRIPTION,
    version: VERSION,
    ...argv ? { argv } : {},
    topLevelHelp: TOP_HELP,
    home: homeCommand,
    commands: COMMANDS,
    getCommandHelp: (command) => COMMAND_HELP[command]
  });
}

// packages/google/src/axi/bin-gmail.ts
await main();
